### ISSUE TITLE
turbine field in generator_eia860 doesn't exist after 2013

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#100]
The turbine field in the generator_eia860 table only exists prior to 2013, so if you try and initialize the DB for only years after 2013, you'll get a KeyError for turbines. This shouldn't break the whole ingest of the database table -- need to ensure that that column is created even if it's not going to be populated with anything.

**Comment by cmgosnell** [comment]
this got somewhat taken care of with EIA normalization and Issue #135
