### ISSUE TITLE
Refine FERC small plant table pudl_ids

### ISSUE THREAD

**Issue by aesharpe** [catalyst-cooperative/pudl#1008]
Map pudl ids for this table so that it can be merged with EIA technology descriptions. Steve doing this manually.

**Comment by cmgosnell** [comment]
@swinter2011  / @aesharpe was this completed? or is this still relevant?

**Comment by aesharpe** [comment]
> @swinter2011 / @aesharpe was this completed? or is this still relevant?

Steve did this but they are not incorporated into the greater PUDL yet. That warrants a different issue though, we can close this.
