### ISSUE TITLE
Complete fuel consumption coverage for heat rate calculations

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#1026]
Create a process analogous to Christina's work on the net generation side of things for combining fuel consumption from the `boiler_fuel_eia923` table and the `generation_fuel_eia923` table along with prime mover codes and boiler information from the boiler and generator tables as needed.

This will feed into the completed heat rate calculations for Greg.

**Comment by cmgosnell** [comment]
too vauge/dupe of #1113
