### ISSUE TITLE
pudl_setup does not update ~/.pudl.yml if called more than one time

### ISSUE THREAD

**Issue by TrentonBush** [catalyst-cooperative/pudl#1032]
### Describe the bug
I made a workspace directory and called `pudl_setup <workspace_dir_1>`. Then I changed my mind about the location, made a new directory and called `pudl_setup <workspace_dir_2>`. This successfully created all the contents, but did not update `~/.pudl.yml` to reflect the new (second) location. It still referenced `<workspace_dir_1>`.

### Bug Severity
How badly is this bug affecting you?
 - **Low:** The bug isn't causing me problems, but something's still wrong here.

### To Reproduce
cd <test_location>
mkdir ./test_dir_1
pudl_setup ./test_dir_1
cat ~/.pudl.yml

mkdir ./test_dir_2
pudl_setup ./test_dir_1
cat ~/.pudl.yml

### Expected behavior
expected pudl_setup to adjust all config to point to the new location

### Software Environment?
 - OS: Ubuntu 20.04
 - How did you install PUDL? clone; hash 2a0fe38f

**Comment by zaneselvans** [comment]
Did you try running `pudl_setup --clobber` by chance? I think that will overwrite the contents of your `.pudl.yml` file, but I'm not sure.

I suspect it would be better to manage these paths with environment variables in the long run.

**Comment by TrentonBush** [comment]
whoooops! yes --clobber does the trick. Missed that somehow.
