### ISSUE TITLE
Check line mappings in 2016 FERC Form 1 for historical consistency

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#104]
FERC Form 1 for 2016 is out! This means we need to check and make sure that the line-to-field mapping that we've created for some of the database tables is still valid for 2016.  These tables include Plant in Service and Accumulated Depreciation.  The issue here is that if a new line (e.g. battery storage) is inserted into the "Plant in Service" table, then the *line* number on the form, which is associated with all of the data fields which follow that field may shift by one, meaning we'll be mapping the numbers from the wrong line to a given database field.

A similar issue (#55) needs to be addressed in the FERC data from 2004-2006 (where we know there are some lines that don't match up)

**Comment by swinter2011** [comment]
There's an additional table in 2016 - the "Regional Transmission Service Revenues (Account 457.1)" which was previously part of Line 42, "Electric Operating Revenues".

Fuel and Steam are both unchanged.

**Comment by zaneselvans** [comment]
Do you mean a whole new FERC table? Or just a new division of lines?  What table is that in?  I thought we'd also identified some inter-year changes where things like electricity storage had been added as a line-item.  No?
