### ISSUE TITLE
Plan for addressing gaps in small generators table technology type

### ISSUE THREAD

**Issue by aesharpe** [catalyst-cooperative/pudl#1042]
Once we've successfully mapped technology descriptions onto the ferc1 small generators table, we'll need to determine how to fill in the gaps--manually?

**Comment by cmgosnell** [comment]
@aesharpe I'm assuming this is still no longer relevant bc of our use of FERC-EIA connection

**Comment by aesharpe** [comment]
> @aesharpe I'm assuming this is still no longer relevant bc of our use of FERC-EIA connection

Yes, you're probably right
