### ISSUE TITLE
move EIA (plant part list) to FERC1 plant granular connection into PUDL

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/pudl#1064]
In partnership with RMI, we've developed a granular connection between FERC plant records (which are a combination of whole plants, units, generators, portions of plants based on utility ownership, etc.) to their appropriate collection of EIA generators/owners.

This currently happens in [this module](https://github.com/catalyst-cooperative/rmi-ferc1-eia/blob/main/src/pudl_rmi/connect_ferc1_to_eia.py). I'd like to move this record linkage processing into PUDL's output/analysis layer.

A prerequisite for this issue is #952.

**Comment by zaneselvans** [comment]
@cmgosnell @katie-lamb this is about to get merged in with #2224 right?
