### ISSUE TITLE
Assign PUDL IDs to EIA 860/923 old entities (2001-2008) and map them to FERC entities

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#1069]
Integration of the EIA 923 data from 2001-2008 (see PR #1035) has added some new EIA plants and utilities that previously didn't appear, and so they are now showing up as unmapped in the PUDL plant / utility ID tables. In total there appear to be:
* 228 unmapped plants
* 387 unmapped utilities

These plants and utilities need to be added to the manual PUDL ID mapping, and associated with the corresponding FERC plants and utilities which previously could not be mapped.

There will very likely be additional unmapped plants and utilities which appear as a result of the 2001-2003 EIA 860 data being integrated as well. It probably makes sense to do all the mapping for 2001-2008 at the same time. See also #848

**Comment by zaneselvans** [comment]
@bendnorman since you're working on #848 right now, you might want to look at this as the next thing to work on. We'll need to link up all the FERC/EIA utilities and plants for these older years once you've got them integrated.

**Comment by bendnorman** [comment]
I reran `devtools/ferc1-eia-glue/ferc1-eia-glue.ipynb` on EIA 923 and 860 2001-2019. In total there appear to be:

- 253 unmapped EIA plants.
- 6491 unmapped EIA utilities.
- 2594 unmapped utilities with plants/ownership.

@zaneselvans how did you get 387 unmapped utilities? I double-checked the data on datasette and there are [12790 unique](https://data.catalyst.coop/pudl?sql=select+count%28distinct%28utility_id_eia%29%29+from+utilities_entity_eia%3B) `utility_id_eia`'s and there are only 6776 mapped utilities in `mapping_eia923_ferc1.xlsx`. 

I sent csvs of the unmapped utilities and plants to @stevenbwinter. I think many of the unmapped utilities have very small total capacities.

**Comment by zaneselvans** [comment]
Please also review / try to fix the PUDL IDs from #736 into this.

**Comment by bendnorman** [comment]
I think the unmapped csvs slipped through the cracks. I reran the ferc1-eia-glue notebook to produce the unmapped data with the 2001 - 2019 EIA data. We are waiting for the 923 data before we map the 2020 data. The outputs live in this zipfile on [google drive](https://drive.google.com/file/d/1nIPHVBDK0gXrEr3idu_HRze6AbiwoflE/view?usp=sharing).

**Comment by zaneselvans** [comment]
I've re-run it with the 2020 EIA and FERC 1 data as well and uploaded the CSVs [to google drive](https://drive.google.com/file/d/1ttUJXmhPxM0I09Ua87WxI9xVyK4iswEP/view?usp=sharing)

**Comment by TrentonBush** [comment]
I re-ran it with data from 2001-2020 plus 860m data from july 2021. I uploaded to the same [google drive ](https://drive.google.com/file/d/1xAO7sofZK7lRaFMn3_a6ZTyHNYIFbeNl/view?usp=sharing)folder
