### ISSUE TITLE
Review Uday's total mapping spreadsheet

### ISSUE THREAD

**Issue by aesharpe** [catalyst-cooperative/pudl#1079]
Uday looked at my original total mapping for the FERC1 steam table and found that there were likely more nuances than a programatic approach could tackle efficiently. 

## Thoughts on aggregation:

Good indication that a row needs help when it contains: 
- totals
- "share"

**Comment by cmgosnell** [comment]
hey @aesharpe ! is this still relevant? can we close it or does it need to stick around?

**Comment by aesharpe** [comment]
> hey @aesharpe ! is this still relevant? can we close it or does it need to stick around?

Yes, still relevant just way in the backlog

**Comment by aesharpe** [comment]
A bit obsolete at this point, closing
