### ISSUE TITLE
Download CEMS Data

### ISSUE THREAD

**Issue by briannacote** [catalyst-cooperative/pudl#1099]
Hi PUDL Team!

It's been a while since I used your products. Historically I used it for EPA CEMS data download. The last time I did this was with 2018 CEMS data. At the time, I made a single year in an sqlite file. I know at that time you had started using Parquet as well. 

I am curious if you can help me get set up again if possible? I went through the documentation but it's not clear on what to do. Many of the Datasette links are broken for the EPA CEMS. I also got Docker going but wasn't sure what to do there nor could I find the examples the website mentioned.

I know some of this is a simple ask. Things have changed so much since last I used your system. Here's the SQL statement I used long ago to give you an idea of my use case:

```
   SELECT
   h.plant_id_eia,
   h.unitid,
   h.operating_datetime_utc,
   h.gross_load_mw,
   h.so2_mass_lbs,
   h.nox_rate_lbs_mmbtu,
   h.nox_mass_lbs,
   h.co2_mass_tons,
   h.heat_content_mmbtu

   from hourly_emissions_epacems h
   where plant_id_eia = 3
   and operating_datetime_utc >= '2018-01-01'
   and operating_datetime_utc <= '2019-12-31'
   order by plant_id_eia,  unitid, operating_datetime_utc
```

Thanks for the help,
Brianna

**Comment by briannacote** [comment]
Hi Folks,

I am having issues running the example scripts you sent. Most likely it's either an environment setup problem. I also have an older version of PUDL on my machine from your previous setup that could be causing interference.

Are there any instructions for those without blank slates to walk through? Is there a good way to start fresh altogether?

Thank you,
Brianna

**Comment by briannacote** [comment]
PS. I'm happy to help hop on a quick call if that's possible. It might be easier to troubleshoot and get the latest version of you system going. Thanks again.

**Comment by TrentonBush** [comment]
Hi Brianna,
Thanks for your interest in PUDL's CEMS data and for reaching out. Yes, there has been a lot of change since 2018!

We've recently been tinkering with CEMS data access and unfortunately we haven't made an API for it yet. Right now the CEMS parquet files don't have a SQL-based access method, so you'll have to use pandas/dask.

Since you have docker running, I think the easiest way is to enter the jupyter environment with `docker-compose up` then use something like this:

```
import pandas as pd
import pudl

pudl_settings = pudl.workspace.setup.get_defaults()
CEMS_PATH = pathlib.Path(pudl_settings["parquet_dir"]) / "epacems"

my_columns = [
"plant_id_eia",
"unitid",
"operating_datetime_utc",
"gross_load_mw",
"so2_mass_lbs",
"nox_rate_lbs_mmbtu",
"nox_mass_lbs",
"co2_mass_tons",
"heat_content_mmbtu"
]

my_plant_id = 3
years_of_interest = [2018, 2019] # list of integers. For a long range, use list(range(start, stop+1))
states = ['AL'] # list of state abbreviations. For all states, pass None

# load all data from those states and years
cems_data = pd.read_parquet(
    CEMS_PATH,
    use_nullable_dtypes=True,
    columns=my_columns,
    filters=pudl.output.epacems.year_state_filter(
        states=states,
        years=years_of_interest
    )
)

# subset and sort
cems_for_my_plant = cems_data.query('plant_id_eia == @my_plant_id').sort_values(by=['plant_id_eia',  'unitid', 'operating_datetime_utc'])
```

To look up the state of a single plant, replace the `states` assignment above with with this:
```
pudl_engine = sa.create_engine(pudl_settings['pudl_db'])
pudl_out = pudl.output.pudltabl.PudlTabl(
    freq=mcoe_freq,
    start_date=mcoe_start_date,
    end_date=mcoe_end_date,
    pudl_engine=pudl_engine,
)
states = pudl.output.epacems.get_plant_states(my_single_plant_id, pudl_out)
```

**Comment by briannacote** [comment]
Thanks very much, Trenton! I was able to get the notebooks working. I will have to try it through a regular script versus a notebook. That originally was throwing a fair few errors. But I'll try it in the Docker environment along with what you mentioned. Through the Jupyter notebook I was able to pull the data I needed using the dask and code snippets you had there.

All the Best,
Bri
