### ISSUE TITLE
Unit tests for pudl.helpers.clean_merge_asof()

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#1106]
Create a set of unit tests for the `pudl.helpers.clean_merge_asof()` function that is deeply integrated into the denormalized output functions and the mcoe analysis.

## Test Cases
* [ ] **simple monthly**: monthly data + yearly attributes covering the same entities and set of years.
* [ ] **simple yearly**: yearly data + yearly attributes covering the same entities and set of years.
* [ ] **monthly across years**: make sure that months don't merge to the wrong year if there's a gap.
* [ ] **yearly across years**: make sure that years don't merge to the wrong year if there's a gap.
* [ ] **leap years**: do we get the same correct behaviors in 365 and 366 day years?
* [ ] **duplicate keys**: what happens if we have duplicate merge keys in one or the other dataframes?
* [ ] **missing data**: what happens if we're missing some of the more granular data?
* [ ] **missing entities**: what happens if we're missing some of the less granular entities / attributes?

**Comment by zaneselvans** [comment]
@TrentonBush I am really struggling to construct test data frames for this in a way that seems clean and reliable and easy to understand but that will still have data that isn't too simple. Like to have two years, with two plants, each of which has two generators is already 8 rows, and then to bring in monthly data for 2 years means it's suddenly 96 rows total, with more data required. But making all the data just be constant, it won't break sometimes when it should break. Like do I need a function that can take generator attributes and dates and return a predictable but varying time series? What is this kind of test supposed to look like?

**Comment by zaneselvans** [comment]
Some of my unsatisfying attempts to create input data....


```py
report_date_monthly = pd.date_range(
    start="2019-01-01",
    end="2020-12-31",
    freq="MS",
    name="report_date",
)

report_date_annual = pd.date_range(
    start="2019-01-01",
    end="2020-12-31",
    freq="AS",
    name="report_date",
)

report_year_integer = pd.Series(range(2019, 2021))
report_year_integer.name = "report_year"
data_monthly = pd.DataFrame(
    data={"test_data": np.arange(float(len(report_date_monthly)))},
    index=report_date_monthly,
).reset_index()

# Generator Entities
gens_entity = pd.DataFrame.from_records([
    {"plant_id": 1, "gen_id": "1A", "state": "WY", "capacity": 1000.0, "fuel": "coal"},
    {"plant_id": 1, "gen_id": "1B", "state": "WY", "capacity": 50.0, "fuel": "oil"},
    {"plant_id": 2, "gen_id": "2A", "state": "CO", "capacity": 500.0, "fuel": "coal"},
    {"plant_id": 2, "gen_id": "2B", "state": "CO", "capacity": 250.0, "fuel": "gas"},
]).astype({
    "plant_id": pd.Int64Dtype(),
    "gen_id": pd.StringDtype(),
    "state": pd.StringDtype(),
    "capacity": float,
    "fuel": pd.StringDtype(),
})

# Annual Plants
plants_annual = pd.DataFrame.from_records([
    {"report_date": "2019-01-01", "plant_id": 1, "plant_name": "Plant 1 2019"},
    {"report_date": "2019-01-01", "plant_id": 2, "plant_name": "Plant 2 2019"},
    {"report_date": "2020-01-01", "plant_id": 1, "plant_name": "Plant 1 2020"},
    {"report_date": "2020-01-01", "plant_id": 2, "plant_name": "Plant 2 2020"},
]).astype({
    "report_date": "datetime64[ns]",
    "plant_id": pd.Int64Dtype(),
    "plant_name": pd.StringDtype(),
})

# Annual Generators
gens_annual = pd.merge(plants_annual, gens_entity)
```

**Comment by TrentonBush** [comment]
Those are a lot of test cases to consider! The good news is that this function is a thin wrapper on pandas' merge_asof. Are these test cases really testing our code or are they redundant with pandas' own tests of merge_asof?

They have a [long test suite](https://github.com/pandas-dev/pandas/blob/5cd594f137f91a0c3c97353066029d5dcc775c9a/pandas/tests/reshape/merge/test_merge_asof.py) for merge_asof. I think we should just look to see if these test cases are already covered there.

**Comment by TrentonBush** [comment]
Here's an example df generator:
```python:
def df_from_product(inputs: Dict[str, Sequence]):
    """Make a dataframe from cartesian product of input sequences.
    A special input named 'values' (optional) is directly assigned
    to the 'values' column. Otherwise the column
    is sequential integers.

    Args:
        inputs (Dict[str, Sequence]): dataframe column names mapped
            to their unique values. 'values' key is special, see above.

    Return:
        df (pd.DataFrame): cartesian product dataframe
    """
    values = inputs.pop('values', None)
    names, iterables = inputs.items()
    df = pd.MultiIndex.from_product(
        iterables, names=names).to_frame(index=False)
    if values is None:  # set to int range
        df.index = df.index.rename('values')
        df = df.reset_index()
    else:
        df['values'] = values
    return df
```
 and usage:
```
inputs = dict(
        timestamps=pd.date_range(
            start="2019-06-01",
            end="2020-5-31",
            freq="MS",
        ),
        id1=[1, 2],
        id2=['a', 'b'],
)
df_monthly = df_from_product(inputs)
```

**Comment by zaneselvans** [comment]
All of @cmgosnell, @TrentonBush and I think it will be better to replace this function with something that just uses the `year`, `month`, `day` components as integer merge fields. `clean_merge_asof()` doesn't seem to be the source of any problems at the moment, these unit tests seem like they'll be a pain, and I'm gonna replace it anyway, so I'm going to close this for now. Not great but... oh well.
