### ISSUE TITLE
ferc1_to_sqlite enables loading multiple versions of the same year

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/pudl#1108]
### Describe the bug
the `ferc1_to_sqlite` script/ `pudl.extract.ferc1.dbf2sqlite()` enables loading of multiple version of the same year. I accidentally loaded two 2019's, but I could have loaded 17 2019's.

I assume you could do the same thing with tables.

### Bug Severity
How badly is this bug affecting you?
 - **Low:** The bug isn't causing me problems, but something's still wrong here.

### To Reproduce
running `ferc1_to_sqlite` at the command line, pointing to a settings file with multiple instances of the same year.

Or running `pudl.extract.ferc1.dbf2sqlite(["table1", "table1"], [2020, 2020, 2020], refyear, pudl_settings)` #2020Foreverrrr :scream_face:

### Expected behavior
It should either break or kindly de-duplicate your list of years/tables. I think I'd prefer the latter.

**Comment by zaneselvans** [comment]
This issue was addressed in the harvesting refactor and #1176 Epic.
