### ISSUE TITLE
Match missing PUDL Plant IDs for Imperial Irrigation District Double Weir Plant

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#116]
There appears to be an unmapped plant in the EIA860 data -- for 2011 and 2012, the Imperial Irrigation District (operator_id = 9216, util_id_pudl = 2069) Double Weir (plant_id = 56567) plant has no plant_id_pudl associated with it.

**Comment by swinter2011** [comment]
I've added this plant to the matching table.
