### ISSUE TITLE
Design tabular CES/RPS database

### ISSUE THREAD

**Issue by aesharpe** [catalyst-cooperative/pudl#1165]
## Project Description

Sloan-funded project to digitize information pertaining to state CES/RPS policy. Our goal is to make a machine readable database of RPS/CES qualifications so that energy modelers and anyone interested in comparing state RPS/CES qualifications or running tests on possible RPS assets can do so without having to gather this information manually and from such disparate sources.

[Grant Description](https://docs.google.com/document/d/1q9J49sDbwFNsbfk31p_sU0dSKiyq5TiO/edit?rtpof=true) (see section on Machine Readable Clean Energy Standards)
Harvest Tag: `[ces] Machine Reable CES`

## Problem Statement
The most granular version of this data exists in state legislature. To extract it, and glean any wholistic understanding of national trends, you have to visit individual state legislature websites, download the relevant legislation, find the relevant sections, and parse the information from sentences. 

Centralized policy repositories like the Database for State Incentives for Renewables and Efficiency (DSIRE) house broad depictions of state climate policies, but they do not include all of the nuances and qualifications of each states' RPS/CES nor is the information capable of being processed and analyzed in bulk.

#### Who Wants It?
This project is motivated by many users expressing an interest in digitized, machine readable policy data for use in modeling and other efforts. 

#### Alignment with Catalyst Goals
It aligns with our goal as a coop to make public energy data more accessible as it makes qualitative information stored in disparate legislative documents and puts it in one place that readily houses and compares all the information.

#### Priority?
This project is not related to the build-out of underlying PUDL infrastructure therefore it is not essential to core functionality and can postponed as necessary.

#### Blocking?
No

#### How do we know when we are done?
This project is complete when we have integrated an RPS/CES dataset into the PUDL database and output tables.

#### What is out of scope?
* Voluntary targets
* Future targets not yet cemented in the legislature
* Carbon-reduction/net-zero targets

**Comment by TrentonBush** [comment]
Did we get this data from NCSL? I happened to see [their CES/RPS website](https://www.ncsl.org/research/energy/renewable-portfolio-standards.aspx) has most of this info for scraping.
