### ISSUE TITLE
Migrate to new Pydantic metadata

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/pudl#1180]
## Description
@ezwelty has done a lot of the good good work to convert our disparate metadata into a flexible, useful and exportable metadata system in PR #806. However, we still have some residual dependence on metadata that is stored separately, which can and should be updated to use the new system. A lot of that stuff is still hanging out in `pudl.constants` and should be subsumed within or superceded by the new Pydantic metadata system.

## Motivation
Uniform, non-duplicative access to all of our metadata through an API will make maintenance easier, keep the code more readable, and allow us to much more easily export metadata to other formats. E.g. SQLAlchemy, Intake data catalogs, Datasette, and our documentation.

## Scope
* [x] #1186 
* [x] #1213 
* [x] #1211
* [x] #1214 
* [x] #1251  
* [x] #1269 
* [x] #1210 
* [x] #1252
* [x] #1250 
* [x] #1270 
* [x] #1410 
* [x] #1409 
* [x] #52 

## Out of Scope
* #426

**Comment by ezwelty** [comment]
> Using the metadata to integrate the revamp of the harvesting process is out of scope of this epic!

So is your idea here to replace all the existing references to `pudl.constants`, `pudl.package_data.meta`, ... throughout the code to the `pudl.metadata` objects in #806, but without yet using the `pudl.metadata.classes` to perform any operations on the dataframes going through the ETL pipeline?

**Comment by cmgosnell** [comment]
@ezwelty basically, yes! It feels like a hindrance to not have it connected to the current ETL - especially in changing names (#845) and PKs (#846). So let's hook it up and then iterate on the additional functionality.
