### ISSUE TITLE
convert new metadata into sqlachemy db schema

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/pudl#1186]
enable the creation of a sqlachemy db schema with the new metadata system.

We would need to be able to feed the converter a List of table names and it would need to return a sqlachemy metadata object w/ Tables w/ columns and their dypes, field constraints (only enums right now), pk's and fk's.

**Comment by ezwelty** [comment]
All of this is already implemented in #806.

**Comment by cmgosnell** [comment]
oh good!! great @zaneselvans got it working so wahoo
