### ISSUE TITLE
Ensure that new metadata system outputs valid datapackage.json

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/pudl#1187]
don't test the data, just validate the schema.

we are already relying on the frictionless tools for our datastore so this will not increase our dependencies.

**Comment by ezwelty** [comment]
@cmgosnell So it *is* a requirement that the metadata follow the Data Package specs to the letter? (This may currently be the case, but I thought we were moving away from Data Package long term). Or do you mean that we ensure that the metadata class `Package` can export a valid Data Package descriptor? (say `Package.to_datapackage()`, which would ensure this functionality even as the metadata diverges from Data Package)

As it is in #806, the classes define and enforce the metadata schema. All of the field/resource metadata is thus validated on `import pudl.metadata` by creating the corresponding class instances.

**Comment by cmgosnell** [comment]
@zaneselvans and i were having a disagreement about this and initially wanted this but i think we came to a different place about it. disregard this.
