### ISSUE TITLE
Integer primary keys are not automatically nullable=False

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#1194]
Under SQLAlchemy v1.4 Integer primary key fields appear not to be automatically set to `nullable=False`, and this is causing a doctest failure in `pudl.metadata.classes.Resource`.  It's easy to get rid of the failure by changing the expected output, but it seems like we might be depending on the SQLAlchemy 1.3 behavior to make sure that primary keys can't be null.

**Comment by ezwelty** [comment]
This was taken care of by my commit to PR #806 (https://github.com/catalyst-cooperative/pudl/commit/c3eba3a4f4077546fb94bf7590aa0925b911e9ae), so I believe this issue can be closed.
