### ISSUE TITLE
mcoe analysis fails due to null columns with fill_fuel_cost=False

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#1202]
The `pudl.analysis.mcoe.mcoe()` function uses `pudl.validate.no_null_cols()` and `pudl.validate.no_null_rows()` defensively to check that null rows / columns haven't been introduced through a bad merge. However, there are some columns which we might expect to be null under some circumstances. In particular `fuel_cost_from_eiaapi` should be all Null if we aren't attempting to fill in missing fuel costs with the EIA API, i.e. when we use `pudl_out.mcoe()` with `fill_fuel_cost=False`

The columns which are checked for all-null values need to be updated to reflect what we expect to find based on the input flags.

**Comment by cmgosnell** [comment]
iirc the filled in columns should not be all null if they aren't filled in because they should have originally reported data in them.

**Comment by zaneselvans** [comment]
I think this is likely an artifact of the bunches of empty-but-still-full table problem in #1203. So hopefully it just goes away.

**Comment by zaneselvans** [comment]
It turns out this was entirely due to #1203. All is well.
