### ISSUE TITLE
Check mapping of plant_id_pudl 1178 & 1179

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#121]
There's a plant named "Mansfield" in Ohio, which appears to show up in more than one plant_id_pudl -- I'm seeing it associated with pland_id_pudl 1178 (via Toledo Edison) and 1179 (Cleveland Electric).

**Comment by swinter2011** [comment]
Yep, they're subsidiaries of FirstEnergy, which had an unmapped EIA ID that I've connected to PUDL ID 1178.
