### ISSUE TITLE
Build RST data dictionaries from new metadata

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#1213]
Currently we have a script, `datapkg_to_rst` that uses the [datapackage.json](https://github.com/catalyst-cooperative/pudl/blob/main/src/pudl/package_data/meta/datapkg/datapackage.json) stored under `package_data` to create [nicely formatted data dictionaries](https://catalystcoop-pudl.readthedocs.io/en/latest/data_dictionaries/pudl_db.html) for our documentation. These are hugely valuable for users in understanding what data is in the database, and where it came from.

We need to move to generating this RST output based on the new metadata structure that lives in the `pudl.metadata` subpackage instead. This seems to be the last dependency that we have on the old metadata, and it would be nice to get it taken care of so we don't have to wonder if the two are getting out of sync (spoiler: they are).

For now, simply write a `Package.to_rst()` function that replicates our existing functionality, and split that into a (renamed) `datapkg_to_rst` script.

Information that should be made available in the documentation by way of this output:

**Tables:**
  * [x] Table names (tables should be sorted by name)
  * [x] Table descriptions (when they exist)
  * [x] Provide links to the tables in [Datasette](https://data.catalyst.coop)

**Fields:**
  * [x] Field names
  * [x] Field data type
  * [x] Field descriptions

**Doc Build Integration**
* [x] Generation of this RST output will need to be integrated into our documentation build, and run automatically whenever we run `tox -e docs` (which happens during the integration tests).

**Comment by ezwelty** [comment]
For now, I would just add a `pudl.metadata.classes.Package.to_rst()` that replicates what already exists: intro, table name, table description, link to Datasette, and a table of fields with name, type, and description. And integrating this into the documentation build. In fact, because the new `Package` is identical to the Tabular Data Package schema, the old template (`RST_TEMPLATE`) can be reused directly.

Only later, in a post-merge future, would I add `Resource.to_rst()` / `Field.to_rst()` and make the output more complex.

**Comment by zaneselvans** [comment]
Okay, I reduced the scope of this issue to just replicating existing functionality and split off enhancements into #1226

**Comment by zaneselvans** [comment]
Whoops hey @ezwelty I did this work today.

**Comment by zaneselvans** [comment]
There are some descriptions and some table definitions which currently exist in the old `datapackage.json` file that don't yet exist in the new metadata and I am in the process of migrating them over.
