### ISSUE TITLE
Initial table design for RPS policy data

### ISSUE THREAD

**Issue by aesharpe** [catalyst-cooperative/pudl#1222]
Using preliminary states Oregon and Virginia, we must look at the programmatically accessible data from DSIRE and Berkeley and brainstorm how to organize the information in a database. This includes:
-  Scoping how the data could look in PUDL. 
   - Will we need more than one db?
   - What can we represent numerically vs. qualitatively?
   - What information should we represent over time vs. statically? 
- Considering how DSIRE could update their archives/backend so as to include more easily scrape-able information.

**Comment by zaneselvans** [comment]
We might also want to consider non-tabular data structures to contain the original data if it's pretty heterogeneous. One possibility that might make sense is encoding it as JSON, with an explicit JSON Schema (so, nested dictionaries and lists with a particular overarching structure).
