### ISSUE TITLE
EPA CEMS can't process states (AK and PR) that only show up in some years

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#1264]
Alaska was added to the EPA CEMS data in 2019, and we just added it to the list of states that we attempt to process during the EPA CEMS ETL, since the files are there already. However, the current system can't deal with this because it iterates over all combinations of the values found in `epacems_states` and `epacems_years`. And since there's no AK data before 2019, it fails immediately.

```
2021-09-29 23:08:45 [    INFO] pudl.etl:439 Processing EPA CEMS data and writing it to Apache Parquet.
2021-09-29 23:08:45 [    INFO] pudl.extract.epacems:168 Processing EPA CEMS hourly data for AK-1995
Traceback (most recent call last):
  File "/home/zane/code/catalyst/pudl/src/pudl/workspace/datastore.py", line 351, in get_unique_resource
    _, content = next(res)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zane/miniconda3/envs/pudl-dev/bin/pudl_etl", line 33, in <module>
    sys.exit(load_entry_point('catalystcoop.pudl', 'console_scripts', 'pudl_etl')())
  File "/home/zane/code/catalyst/pudl/src/pudl/cli.py", line 140, in main
    pudl.etl.etl(
  File "/home/zane/code/catalyst/pudl/src/pudl/etl.py", line 764, in etl
    etl_epacems(dataset["epacems"], pudl_settings, ds_kwargs)
  File "/home/zane/code/catalyst/pudl/src/pudl/etl.py", line 444, in etl_epacems
    for df in epacems_transformed_dfs:
  File "/home/zane/code/catalyst/pudl/src/pudl/transform/epacems.py", line 228, in transform
    for raw_df in epacems_raw_dfs:
  File "/home/zane/code/catalyst/pudl/src/pudl/extract/epacems.py", line 171, in extract
    ds.get_data_frame(partition)
  File "/home/zane/code/catalyst/pudl/src/pudl/extract/epacems.py", line 109, in get_data_frame
    archive = self.datastore.get_zipfile_resource(
  File "/home/zane/code/catalyst/pudl/src/pudl/workspace/datastore.py", line 362, in get_zipfile_resource
    return zipfile.ZipFile(io.BytesIO(self.get_unique_resource(dataset, **filters)))
  File "/home/zane/code/catalyst/pudl/src/pudl/workspace/datastore.py", line 353, in get_unique_resource
    raise KeyError(f"No resources found for {dataset}: {filters}")
KeyError: "No resources found for epacems: {'year': 1995, 'state': 'ak'}"
```

For the moment I will comment out AK and PR from the list of available states.

### Possible fixes
* Specify desired state-year combinations explicitly, rather than combining states and years independently. This would work, but require a lot more information to be specified.
* If a requested data partition isn't available, just print out a logging message and move on. However, since this error is happening at the datastore level, that kind of change would have wider implications.
* We could create dummy zero length data for the year-state combinations that don't exist. This seems to be what's happening for other states that are missing early data (except EPA is doing it for us...)
* We could create a custom `MissingDataPartitionError` and have the Datastore code raise it when this happens, and pass it up to the EPA CEMS ETL code, which could deal with it appropriately (Ignore if it's AK before 2019, or PR not in 2015...) This is probably the right way to handle this. We should get better at exception handling generally and start defining our own exception classes that are more informative than the generic ones.

**Comment by bendnorman** [comment]
I think #1292 gets us closer to resolving this issue.

We could have a `pc.MISSING_PARTITIONS` dictionary that contains tuples of missing partitions for each dataset:

```python
MISSING_PARTITIONS = {
	"epacems": [("AK", 2018), ("PR", 2015)]
}
```

`GenericDatasetSettings` could then validate and exclude the missing partitions from the cartesian product of partitions. Parts of our ETL might need to be updated to extract and transform specific partitions.

**Comment by zaneselvans** [comment]
Maybe there's a more general way to think about the "working partitions" that also includes the tables. Right now we exclude certain tables in certain years via the spreadsheet maps -- lots of source tables / columns don't exist in many of the older years, or get discontinued in latter years. Or they need to come from different file formats or different original sources in different years. Like the FERC-423 / EIA-423 which contains the fuel receipts and costs data before 2008 (which is found in the EIA-923 data thereafter).

**Comment by bendnorman** [comment]
I love both of these ideas. I didn't realize some tables aren't available for certain years. Tables can easily be added to `WORKING_PARTITIONS` in our new dataset settings validation.

**Comment by zaneselvans** [comment]
@zschira This issue has some previous conversation about generalizing partitions.

**Comment by e-belfer** [comment]
Will be fixed in https://github.com/catalyst-cooperative/pudl-archiver/pull/138 because the download links are dynamically generated from API list of available state/year combos.
