### ISSUE TITLE
Generators missing from 860

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/pudl#128]
There are 152 records of plant/generator/years that exist in generation_eia923 and do not exist in generators_eia860. This corresponds to 28 plants. This is the count of generators by year that is missing:
2011: 0
2012: 20
2013: 39
2014: 48
2015: 45
 
These generators either should be dropped from 923 entirely or partially recreated in 860. Recreating the generator records in 860 would create a complete list of generators in one place but the records would be incomplete (i.e. energy source, capacity). The recreated generator records would propagate NA values through calculations that require those fields. Dropping the plants altogether on ingest would make running any subsequent functions simpler (you wouldn't have to deal with null values) but those plants would me gone.

**Comment by zaneselvans** [comment]
@cmgosnell Is this issue still relevant, given the current status of the 860/923 normalization and ID harvesting?

**Comment by cmgosnell** [comment]
this is no longer relevant because of the EIA entity tables generated from Issue #135
