### ISSUE TITLE
Exercise new harvesting process on real data

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#1281]
Once the migration to the new metadata system is sufficiently complete (#1180) and the remaining primary key and database constraint issues have been addressed (#1212,  #1249, #1247), we need to create a branch that uses the new harvesting system, and work through whatever issues come up in running the Actually Existing Data through it.

This may highlight deficiencies in the design, database schema issues, or previously unrecognized issues with the data itself that we need to address before we can merge the new harvesting into `dev` / `main`.

Hopefully this isn't a huge amount of work, but I don't think we'll know until we try it out.

**Comment by cmgosnell** [comment]
this feels like an epic, not an issue

**Comment by zaneselvans** [comment]
This is too vague / overly broad. We will break Harvesting down into smaller things as we start that epic.
