### ISSUE TITLE
Each dataset should be listed at most one time.

### ISSUE THREAD

**Issue by bendnorman** [catalyst-cooperative/pudl#1324]
Turns out [PyYaml allows duplicate](https://github.com/yaml/pyyaml/issues/165) keys even though YAML specifies they should be. 

If we are passionate about enforcing unique keys we could implement [this work around](https://gist.github.com/pypt/94d747fe5180851196eb).

**Comment by zaneselvans** [comment]
We're validating our settings with Pydantic now, and settings will change significantly with use of Dagster.
