### ISSUE TITLE
Estimate delivered fuel costs when not reported

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#137]
The EIA 923 Fuel Receipts and Costs table gives delivered fuel costs on a $/mmBTU basis, but not for all plants. Especially in the case of natural gas plants, these values are often left blank.  However, for evaluating the O&M costs, we really need to the fuel costs.  We should be able to come up with decent estimates, given the other information we have access to.

## Coal
* Date of the delivery.
* Heat content of the coal (mmBTU/unit)
* State & mine of origin for the coal.
* Supplier of the coal (Peabody, Alpha Natural, etc.)
* Type of coal (BIT, ANT, SUB, LIG, etc.)
* Location of the plant it was delivered to.
* State that the coal was delivered to.
* Method of delivery (truck, conveyor, rail, etc.)
* Delivered costs of that type of coal from those mines at that time elsewhere in the state.

## Gas
* Date of the delivery
* Average delivered cost of natural gas for utilities in that month.
* State & location of the plant the gas was delivered to.
* Comparable delivered gas costs elsewhere in the same region at the same time.

It may be possible to feed a bunch of these variables into a machine learning algorithm, and let it figure out the best way to estimate, based on training data (where we know what the fuel costs should be and can check whether it's right or not). Or it may be good enough to just come up with a reasonable estimator on our own.

In either case, we need to test how well our estimation works, based on the records we have with actual delivered fuel costs.

**Comment by cmgosnell** [comment]
we do this now in our outputs in [this function](https://catalystcoop-pudl.readthedocs.io/en/latest/api/pudl.output.eia923.html#pudl.output.eia923.fuel_receipts_costs_eia923) via [EIA's state average's](https://catalystcoop-pudl.readthedocs.io/en/latest/api/pudl.output.eia923.html#pudl.output.eia923.get_fuel_cost_avg_eiaapi) from its API.
