### ISSUE TITLE
Fix allocate_net_gen tests

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#1371]
Currently the net generation allocation tests do not get run, because the test module name does not end with `_test`.

When the module is renamed and the tests are run, there are several errors that will require some understanding of what's supposed to happen in the allocation process and maybe the creation of some scenarios that exercise the non-operational status logic, so I'm leaving it alone for now and creating this issue for @cmgosnell. The current error is something to do with `prime_mover_code`

Changes I made:
* I've renamed the module so that `pytest` will find it, and marked the tests with `@pytest.mark.xfail` with a reference to this issue.
* I replaced `None` with `pd.NA` in the input dataframes for non-floating point values.
* I'm running `apply_pudl_dtypes()` on all of the input and output dataframes.
* I added `operational_status` and `retirement_date` columns, indicating that all generators are operating and that they have no specific retirement dates, or that those dates are in the distant future.

**Comment by jdangerx** [comment]
Now that #2297 is merged, the tests are "good enough" to help us keep the code working while we update `allocate_net_gen`. Closing.
