### ISSUE TITLE
Scope how to use Airbyte for our excel extraction

### ISSUE THREAD

**Issue by bendnorman** [catalyst-cooperative/pudl#1404]
Airbyte does provide an excel source that uses [pandas IO to handle](https://docs.airbyte.com/integrations/sources/file#reader-options) headers, footers and sheets. However, you have to create one source for one excel sheet. EIA 923 and 860 offer about 20 years of excel files and each year contains about 10 sheets. This means about 200 sources for one dataset.  Can this be handled gracefully with Airbyte? The schemas for these datasets also change over the years. Where can we handle the column mapping? Same issues with CEMS (50 states * 25 years = 1250 csvs to extract). This issue could be resolved by creating the sources programmatically using the [Airbyte API](https://airbyte.com/embed-airbyte-connectors-with-api) or by adding each partition and table via the UI and doing the column mapping after each partition is loaded into the db.  

Done when these questions are answered:
- Are there similar examples from the Airbyte community?
- What would this look like via the UI? We could try this out for a subset of EIA data.
   - Where does the column mapping happen? 
- Where are the excel reader options and metadata stored? How can we version control them? 
- What would this look like via the API? Can we handle the extraction programmatically?

**Comment by zaneselvans** [comment]
The original EPA CEMS data is actually monthly, so it's 50 states * 25 years * 12 months in raw CSVs, we just bundled the months into years for the archives because Zenodo barfed on a 12,000 file archive.

One advantage of breaking it out into all of these discrete sources -- if we can wield them programmatically -- is that it would be easy to pull in different raw formats and concatenate sources across years.  E.g. the EIA-423 contains the fuel receipts and cost data from before 2008, but that data is in the EIA-923 in subsequent years.

**Comment by bendnorman** [comment]
I was able to programmatically create sources using the [Airbyte API](https://airbyte-public-api-docs.s3.us-east-2.amazonaws.com/rapidoc-api-docs.html#overview). It is pretty straightforward but [still in alpha](https://docs.airbyte.com/api-documentation). 

We could use Airbyte to programmatically load the excel partitions into a database but we'd need to figure out where to unzip the zip files stored on Zenodo. Potential workflow:
1. Download the zipfiles and unzip them. 
2. Programmatically load the raw excel files using Airbyte into a database. This step requires the footer, header, column and file mapping metadata. 
3. Extract the excel files from the db into pandas and combine the partitions. This step requires the column mapping metadata. 
-----------------------------
I think we're going to have to jump through some hoops to use Airbyte. 
1. We need to develop a process for handling zipfiles and Airbyte loading. 
2. We need to create custom Sources for most of our filetypes (XBRL, DBF)

An argument to use Airbyte is that we are going to have to address the above issues in some way so we might as well use Airbyte. However, I'm not sure if it is worth rewriting our existing extract process and adding a big dependency.

**Comment by bendnorman** [comment]
I am closing this issue for now because Airbyte doesn't seems like a great fit for us right now.

**Comment by bendnorman** [comment]
Airbyte has released a CLI that allows users to: _"leverage any scripting or templating tool to generate configurations dynamically for creation of data sources, destinations, and connections"._ In theory this CLI should make it easier to extract our hundreds of excel files without having to add them one by one in the UI. It's still in alpha though. 

- [Blog post](https://airbyte.com/blog/airbyte-cli-now-available-for-testing)
- [Video tutorial](https://www.youtube.com/watch?v=zQh7eRXDJq8)
- [Docs](https://github.com/airbytehq/airbyte/blob/master/octavia-cli/README.md)
