### ISSUE TITLE
Move WORKING_PARTITIONS metadata into pudl.settings module

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#1410]
Currently the `pudl.constants.WORKING_PARTITIONS` dictionary indicates what subset of the raw data provided by the PUDL Datastore is expected to work with the PUDL software.  That information should probably be stored over in the `pudl.settings` module, where the input validation is happening. Does that seem right to you @bendnorman? It's not a kind of information that obviously fits within either the Field/Resource/Package metadata structures or the Datastore.

**Comment by bendnorman** [comment]
Seems like a logical place to move the constants. Each dataset setting class can specify the working partitions: 

```python
class Eia923Settings(GenericDatasetSettings):
      working_partitions: ClassVar[dict] = {"years": [...]}
      ...
```

Where do you think `PUDL_TABLES` should live?

**Comment by zaneselvans** [comment]
Yeah, that sounds like the right place for this information to go.

I've put dealing with `PUDL_TABLES` under its own issue: #1409

**Comment by zaneselvans** [comment]
@bendnorman and I talked about this at our infrastructure check-in, and it seems like the working partitions should live in the data source metadata / Pydantic models that we're compiling, and then the Settings class can refer to that data source class to obtain the partitions, and to the various `Resource` objects in the main `Package` class to get the working tables (with a little massaging of the `Resource` metadata structure).
