### ISSUE TITLE
Archive EIA 176

### ISSUE THREAD

**Issue by bendnorman** [catalyst-cooperative/pudl#1413]
Is [this](https://www.eia.gov/naturalgas/annual/) the actual data?

**Comment by zaneselvans** [comment]
Hahaha, no don't be silly. You get the EIA-176 data by clicking on the little database icon in the lower right hand corner of [the header of this web app](https://www.eia.gov/naturalgas/ngqs/):

![image](https://user-images.githubusercontent.com/596279/151410794-65c3854a-758c-4c77-9dfa-24a85ea8b0b2.png)

It links here: https://www.eia.gov/naturalgas/ngqs/all_ng_data.zip

**Comment by bendnorman** [comment]
~ sigh ~

Glad you told me before I downloaded all of those csvs :)

**Comment by e-belfer** [comment]
This issue was resolved through the merging of [this PR](https://github.com/catalyst-cooperative/pudl-archiver/pull/50) into the `pudl-archiver` repo.
