### ISSUE TITLE
Update PUDL from `datapackage==1.15.2` to `frictionless>=4.40,<5`

### ISSUE THREAD

**Issue by bendnorman** [catalyst-cooperative/pudl#1420]
The pudl-zenodo-storage currently uses datapackage 1.15.2. It seems like frictionless has wrapped their packages up into one main package called [Frictionless Framework](https://framework.frictionlessdata.io/docs/development/migration/#from-datapackage):

From [PyPi](https://pypi.org/project/datapackage/):
_[Important Notice] We have released Frictionless Framework. This framework provides improved datapackage functionality extended to be a complete data solution. The change in not breaking for the existing software so no actions are required. Please read the Migration Guide from datapackage to Frictionless Framework._

Done when datapackges has been updated.

**Comment by jdangerx** [comment]
Changed this to reflect that:

1. We should get `pudl` to use the same library/version as `ferc-xbrl-extractor`
2. The version we use in `ferc-xbrl-extractor` is still out of date, and missing important features (see catalyst-cooperate/ferc-xbrl-extractor#153)

And that this issue should only encompass the first point above.
