### ISSUE TITLE
CCAI: Get setup, gain understanding of Panda for EIA + FERC matching

### ISSUE THREAD

**Issue by katie-lamb** [catalyst-cooperative/pudl#1429]
Not entirely sure what the action items are for this issue until we hear back from Andrew and Xu about how Panda performed with the data we sent. 

Setup: 
- [x] get set up using their AWS server instance to run Panda
- [x] figure out what our set up will be moving forward 
     - should we think about using grant money for our own server platform? 
     - maybe we could get some free credits from Google/Microsoft/Amazon for servers?

**Comment by zaneselvans** [comment]
I think we'll want to try and set up our own system at some point if these tools work well, but probably we should hold off until we're more familiar with it all.
