### ISSUE TITLE
ValueError: Series.replace cannot use dict-like to_replace and non-None value

### ISSUE THREAD

**Issue by charmoniumQ** [catalyst-cooperative/pudl#1442]
### Describe the bug

`pudl_etl` throws a `ValueError`.

```shell
$ pudl_etl settings/etl_fast.yml
See output at <https://dpaste.com/F3MJ6XACC>
```

### Bug Severity
How badly is this bug affecting you?
 - **High:** 

### To Reproduce

- [settings/etl_fast.yml](http://dpaste.com/GVDGW98UK)

### Software Environment?
 - OS: Linux laptop 5.11.0-43-generic #47~20.04.2-Ubuntu SMP Mon Dec 13 11:06:56 UTC 2021 x86_64 GNU/Linux
 - PostgreSQL version (e.g. 9.6)
 - Python version: 3.9.6
 - How did you install PUDL? `pip`

**Comment by zaneselvans** [comment]
I'm pretty sure this is an issue with pandas 1.4.0 which has been fixed in our `dev` and maybe `main` branch, but I don't know if we had a pinned `pandas<1.4` version in the v0.5.0 release of PUDL. Can you try running it with a 1.3.x version of Pandas if you're not already?

**Comment by charmoniumQ** [comment]
`main` seems to work.
