### ISSUE TITLE
Create Dagster and Prefect comparison

### ISSUE THREAD

**Issue by bendnorman** [catalyst-cooperative/pudl#1451]
Our decision between Prefect and Dagster is progressing, see #1437 and #1436.

Dagster provides some helpful data-focused features like dataframe metadata tracking, asset materialization, and data frame validation. It feels like we are leaning towards Dagster for these reasons. That being said we have put a lot of time into our Prefect refactor #901 so we should do a full comparison of the two tools features before we make a decision.

This comparison should include:
- Project stability: github activity, slack activity, funding, number of employees.
- Feature comparisons

This issue is complete when we have created a full comparison of Dagster and Prefect.

**Comment by bendnorman** [comment]
If you are a Catalyst human you can access the full comparison [here](https://docs.google.com/document/d/1tj-aVwGSh2KhExRFV9AtewRAbENtePHp3iTvykXVGUE/edit#heading=h.q0x7t5jixyq6).

**Comment by bendnorman** [comment]
We have decided to move forward with Dagster. See epic #1487 for the full reasoning.

**Comment by saulshanabrook** [comment]
> If you are a Catalyst human you can access the full comparison [here](https://docs.google.com/document/d/1tj-aVwGSh2KhExRFV9AtewRAbENtePHp3iTvykXVGUE/edit#heading=h.q0x7t5jixyq6).

@bendnorman Would it be possible to post a public link to that or copy the discussion here? I have also been confronted with this choice in several projects and would be curious to hear your reasoning.

Of course, if there are private parts to it, I totally understand, it isn't essential!

**Comment by bendnorman** [comment]
Hi @saulshanabrook! Sure! I'll move the notes into a github discussion.

**Comment by saulshanabrook** [comment]
@bendnorman Thank you!
