### ISSUE TITLE
Adjust python dependencies

### ISSUE THREAD

**Issue by karldw** [catalyst-cooperative/pudl#150]
The testing code depends on scipy, but that's not mentioned in Requirements.md or requirements.txt. (The code also depends on matplotlib, which is mentioned in Requirements.md, but not requirements.txt.)

(This won't be an issue for normal people who just use Anaconda instead of miniconda...)

**Comment by karldw** [comment]
It's probably worth pinning packages too: https://conda.io/docs/user-guide/tasks/manage-pkgs.html#preventing-packages-from-updating-pinning
(requirements.txt specifies exact package versions, but `conda update` doesn't respect that.)

**Comment by zaneselvans** [comment]
With having set up Travis CI, we've gone to using the `environment.yml` to specify the packages that are actually required (and if we don't keep it updated, the tests fail) which seems like a much more reliable way to make sure we're tracking dependencies. I also just recently removed the pinned versions from that file. Is this a good idea, or a bad idea?  Some of the pinned versions were getting significantly out of date, and everything seems to work with the newest "default" channel releases of all the packages, and I'd rather hear one at a time, gradually, as packages update and potentially break things.  But at the same time I don't want a potential user to have to deal with that. Is this normally dealt with through releases, which pin required versions, for a given release, while allowing the development to continue happening on the most recent packages?

**Comment by karldw** [comment]
Relying on Travis sounds great! I think the common practice is to just require the dependency, or require some version of the dependency >= something. Here's an example from dask-ml: https://github.com/dask/dask-ml/blob/master/setup.py#L13

I was wrong before, conda does allow updates that still comply with the requirements: `conda env update -f environment.yml`.
