### ISSUE TITLE
clean plants_small_ferc1 plant names... more better

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/pudl#152]
The plant names in the plants_small_ferc1 table are not well standardized -- there is some attempt at cleaning them up so the plant names remain the same from year to year happening in the ferc1 transform step right now, but it's based on some pretty ad-hoc spreadsheet based work, and needs to be vetted much better. For now either the raw name, or a "cleaned" name is being pulled into the PUDL database, but we don't have high confidence in it.

**Comment by cmgosnell** [comment]
I tried to extricate the 'dirty' plant name field from the table by filling in it in with non-cleaned records and then dropping the dirty column, but the small plants table has a foreign key relationship with the plants_ferc1 table which is populated from the plant names used in the id mapping.

If we have an actual ferc plant id, and a plants_ferc1 table that is populated from the raw_dfs this problem will be negated, but for now we're probably going to continue to have a plant_name_clean field and a plant_name field.

**Comment by zaneselvans** [comment]
I think this has been done to the extent we're going to do it, in #1735
