### ISSUE TITLE
Refactor PPL orchestration with Dagster

### ISSUE THREAD

**Issue by katie-lamb** [catalyst-cooperative/pudl#1537]
I'm not entirely sure what to put in this issue yet or what the timeline is. PUDL is switching to using Dagster for task orchestration. The PPL processing needs to be refactored now that it has been merged into PUDL. It might be a good first task for Dagster integration.

**Comment by zaneselvans** [comment]
The PPL is now part of `pudl_out` and will get refactored when we DAGify all that.
