### ISSUE TITLE
CEMS rename emissions/heat input columns as hourly rates

### ISSUE THREAD

**Issue by grgmiller** [catalyst-cooperative/pudl#1581]
## The Issue
The EPA's [Power Sector Emissions Data Guide](https://www.epa.gov/sites/default/files/2020-02/documents/camds_power_sector_emissions_data_user_guide.pdf) states that for the CEMS data:

> Sources must report data for all hours of operation, including start up and shutdown. This
includes partial hours (i.e., an operating time less than the full clock hour). **Because mass
emissions, electricity generation, and heat input are hourly rates (e.g., pounds per hour), the
hourly values should be multiplied by the operating time to calculate the actual emissions,
electricity generation, and heat input.**

This was a surprise to me, because the column names seem to suggest that these data are reported as absolute measurements (tons or mmbtu) rather than rates (tons/hr or mmbtu/hr). However, I reached out to the EPA and they confirmed that these emissions and heat input measurements need to be multiplied by the operating_time_hours column to get the actual value (just like you have to multiply gross_load_mw by operating_time_hours to get gross generation in MWh). However, they said that the need to do this calculation depends on where the data is sourced from: if downloaded from AMPD, this calculation is done for you, but if you download from the FTP or FACT, you need to do this calculation. 

As far as I can tell from the pudl documentation, it seems that pudl pulls the CEMS data from the FTIP site (https://catalystcoop-pudl.readthedocs.io/en/latest/data_sources/epacems.html), so the data reported is actually an hourly rate, instead of a total measurement.

## Suggested correction

Option 1: In `pudl.extract.cems`, for each of the emissions and heat input columns, rename to make it clear that these are rates

For example, instead of renaming `"CO2_MASS": "co2_mass_tons"`, rename it as `"co2_rate_tons_hr"`

Option 2:  Calculate the mass value from the rate and the operating time, as if the data were coming from the AMPD source

**Comment by aesharpe** [comment]
> Option 2: Calculate the mass value from the rate and the operating time, as if the data were coming from the AMPD source

I think I'm preferential to option 2. In the past we've shied away from using rates. What do you think @zaneselvans?

**Comment by aesharpe** [comment]
Ok I did some digging. 

> they said that the need to do this calculation depends on where the data is sourced from: if downloaded from AMPD this calculation is done for you.

Because AMPD is now CAMPD, I figured that their data portal https://campd.epa.gov/data/custom-data-download would show the non-rate version of the data and could serve as a good comparison to PUDL (just to confirm whether we were using the rate version or the non rate version). 

I did a quick comparison of an Idaho plant on 1/14/2019 and it looks like the data from the CAMPD portal and PUDL are exactly the same. 

**CAMPD Data**
<img width="397" alt="Screen Shot 2022-07-21 at 2 35 18 PM" src="https://user-images.githubusercontent.com/49878195/180311548-589a1744-7a41-477a-8940-ba2d0ad9e40c.png">

**PUDL Data**
<img width="765" alt="Screen Shot 2022-07-21 at 2 41 15 PM" src="https://user-images.githubusercontent.com/49878195/180311604-91720754-82cc-4be7-9280-e79ae00203dc.png">

I know we got the PUDL data from FTP, so I'm not convinced that this means we are using the non-rate version.

**Comment by grgmiller** [comment]
Hmm it looks like PUDL might actually be sourcing its data from AMPD:
https://github.com/catalyst-cooperative/pudl/blob/15f20843c132f70dc699c42dce6f017dd190e96c/src/pudl/metadata/sources.py#L184

So maybe the pudl documentation [here ](https://catalystcoop-pudl.readthedocs.io/en/latest/data_sources/epacems.html) is out of date?

Or did the version of the data published on Zenodo get downloaded from the FTP, and PUDL changed its source to AMPD since then?

**Comment by aesharpe** [comment]
> Or did the version of the data published on Zenodo get downloaded from the FTP, and PUDL changed its source to AMPD since then?

I should triple check, but our epacems scraper still seems to use FTP (see updated comment above)

**Comment by grgmiller** [comment]
Where does the FTP scraper live? I can't seem to find it in the pudl codebase anywhere...

**Comment by aesharpe** [comment]
> Where does the FTP scraper live? I can't seem to find it in the pudl codebase anywhere...

It's a different repo. I put a link to it in the comment above

**Comment by aesharpe** [comment]
> Or did the version of the data published on Zenodo get downloaded from the FTP, and PUDL changed its source to AMPD since then?

I think we figured they were the same so we used them interchangeably. Also we wouldn't change the source without also changing Zenodo.

**Comment by aesharpe** [comment]
Ok I just grabbed the data from the FTP: https://gaftp.epa.gov/DMDnLoad/emissions/hourly/monthly/2019/
and it's also the same...

**FTP Data**
<img width="488" alt="Screen Shot 2022-07-21 at 3 07 38 PM" src="https://user-images.githubusercontent.com/49878195/180315497-5d495a50-7e80-4b4c-8408-10e58a642902.png">

**Comment by grgmiller** [comment]
Hmm interesting. Let me reach out to EPA

**Comment by grgmiller** [comment]
The only other thing I can think of is if they didn't perform this calculation when they switched from AMPD to CAMPD. Do you happen to have any of the original AMPD data archived that could be checked?

**Comment by aesharpe** [comment]
Good question. I think we've always pulled from FTP so there wouldn't be any AMPD archived.

**Comment by aesharpe** [comment]
EPA response indicates that this was a miss-understanding and that the columns are ok!

> So I was mistaken when I relayed information to you back in April. My apologies! The op time processing calculation is done for the necessary parameters in AMPD (now CAMPD) and the FTP site. It is only not done in FACT. So the data you pull from the FTP site should match what’s in AMPD/CAMPD. And the FTP headings should make sense that they are in tons (not tons/hr), etc.

**Comment by zaneselvans** [comment]
All the CEMS data we're pulling (and have ever pulled) is from their FTP site. The only reason that that AMPD site is listed as the source URL in those docs is that's the website that you actually go through to get to the FTP site, and if someone wants to go poke around and get more information about the data in general, that's the place to go.

On a side note, it looks like they're now providing access to the same files on the FTP server through HTTPS, which is great, and should be much more reliable and easier to work with in the future. [I created an issue to update the scraper](https://github.com/catalyst-cooperative/pudl-scrapers/issues/26).
