### ISSUE TITLE
Allow averaging over good months for annual MCOE calculations

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#160]
Currently, if a generator has any months of data which are NA, in any of the tables that go into calculating the MCOE, then the entire year's worth of data is effectively lost -- the whole thing becomes NA.  Alternatively, we could aggregate all of the *valid* months and calculate an average annual value based on that partial data. This issue was highlighted with plant_id_eia=56808 (Virgina City Hybrid Energy Center), which should have data for 2012-2016, but which only shows up in 2016... and even then with only a single unit.

**Comment by zaneselvans** [comment]
We can also do the rolling 12 month average to smooth out the noise in the monthly values, which is more appropriate for comparison with the annual FERC Form 1 values.  Set some minimum number of valid values within each 12 month window to assign a value. We have code for this in one of the notebooks.

**Comment by cmgosnell** [comment]
done! there is now a `rolling` arg for pudltabl
