### ISSUE TITLE
Generate documentation for extracted XBRL tables

### ISSUE THREAD

**Issue by zschira** [catalyst-cooperative/pudl#1629]
FERC's XBRL taxonomy contains quite a bit of metadata/descriptions, which can be used to generate a [tabular data resource](https://specs.frictionlessdata.io/tabular-data-resource/) to document tables produced by XBRL extraction.

**Comment by zaneselvans** [comment]
If it's possible to automatically generate rich metadata for the new XBRL format that would be great! It's something we were never really able to do with the only semi-structured FoxPro database. Being able to export that information directly into our documentation would be very helpful. Our Pydantic metadata structures were originally modeled on the tabular data resources / packages. Are you thinking of generating outputs that could be consumed by our existing metadata infrastructure? Or actual `datapackage.json` descriptors?

**Comment by zschira** [comment]
I was planning on using the existing metadata infrastructure as much as possible. So far I've just been working on cleaning up table/column names and organizing metadata from the taxonomy to get prepped for actually generating the structures. Do you have thoughts on using the existing metadata models?

**Comment by zschira** [comment]
Datapackage generation has been implemented in the XBRL repo
