### ISSUE TITLE
Compile Catalyst Email List

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#167]
We've had a lot of conversations with people who are interested in our work. We should put them on an email list so we can update them when interesting things happen! First step is just to make a spreadsheet w/ name, email, phone, notes about who they are and why they're interested.

**Comment by zaneselvans** [comment]
@stevenbwinter @swinter2011 Did we do this? Is this the mailchimp that we've got set up?

**Comment by swinter2011** [comment]
Yes, we did this but another round of it would be useful, focused on adding
people we've been in touch with since the last round of outreach in late
August 2018.
