### ISSUE TITLE
FERC 714

### ISSUE THREAD

**Issue by karldw** [catalyst-cooperative/pudl#169]
I think I'm going to pull [FERC form 714](https://www.ferc.gov/docs-filing/forms/form-714/overview.asp) data for a project I'm working on.  Is this something you'd want to add to PUDL?

Highlights:
- Hourly system lambda by balancing authority
- Hourly demand by planning area
- Organized CSVs since 2006.

**Comment by zaneselvans** [comment]
Early on we did list 714 as one of the forms we wanted to get pulled into PUDL, but as of yet we haven't had a particular use case for it (unlike the EIA 860, 861, 923, and EPA CEMS data) so it hasn't risen to the top of the pile -- but I think eventually it would be a useful thing to have programmatic access to, so if you need to use it and want to work on getting it integrated, I think that would be great.  And maybe it's not a big mess, if they're supplying it as CSV from the beginning.
