### ISSUE TITLE
Notify community-dev when outside users create issues or discussions

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#1698]
To make sure we don't miss interactions with outside users, set up notifications with a GitHub Actions workflow when outside folks create issues or discussions. Some useful actions / docs:

* [Events that trigger workflows](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows)
  * [discussion](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#discussion)
  * [discussion_comment](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#discussion_comment)
  * [issues](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issues)
  * [issue_comment](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment)
* [Is Organization Member](https://github.com/marketplace/actions/is-organization-member)
* [Slack Notify](https://github.com/marketplace/actions/slack-notify)

**Comment by bendnorman** [comment]
Closed by #2211

- [How to format slack markdown messages with the API](https://api.slack.com/reference/surfaces/formatting#linking-urls)
- [How to create a slack bot for github actions](https://github.com/marketplace/actions/slack-send)
- I couldn't find an exhaustive source for the properties of `github.event`. These were some docs I referenced:
   - [Web events and payloads](https://docs.github.com/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#issues)
   - [Events that trigger workflows](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issues)
   - [Github event types](https://docs.github.com/en/developers/webhooks-and-events/events/github-event-types#issuesevent)
   - [How to get an author of a PR/issues](https://github.com/orgs/community/discussions/25502)

**Comment by bendnorman** [comment]
See description and solution of the annoying github condition bug [here](https://github.com/JamesSingleton/is-organization-member/pull/24).
