### ISSUE TITLE
Refactor `plants_steam_ferc1` transform for XBRL + DBF inputs

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/pudl#1707]
Below are my (WIP!) notes about how to rearrange the transform step for the steam table:

## pre-concat but mirrored (as in same steps diff inputs)
- [x] rename cols (draft 1 done!)
   - [x] attempt to integrate the rename dict into our metadata.

## DBF
- [x] `_clean_cols`?: most of this function is pretty dang dbf specific, but we'll need analogous xbrl cleaning as well
   - [x] this works for now but it should probably be cleaned up. Ideally it would be integrated into `assign_record_id_xbrl` -> `assign_record_id`

## XBRL
- [x] merge `_instant` and `_duration` tables
- [x] record_id assignment (DRAFT DONE yeesh) #1706 
- [ ] #1705

## Post concat
- [x] `cleanstrings`
    - [x] we'll probably want to rearrange how these are called to just use the table name (this should mostly be a metadata re-org
- [x] `oob_to_nan`
- [x] convert kW -> MW
- [x] `_plants_steam_assign_plant_ids` (we decided that this needs to be post concat right?

**Comment by cmgosnell** [comment]
Column mapping notes:
- `plant_name` has two options which are almost entirely the same:
```
steam_extracted_xbrl = pudl.helpers.simplify_strings(steam_extracted_xbrl, ["PlantName", "PlantNameAxis"])
steam_extracted_xbrl[steam_extracted_xbrl.PlantName != steam_extracted_xbrl.PlantNameAxis]

>> 

index | entity_id | filing_name | start_date | end_date | PlantNameAxis | OrderNumber | PlantName | PlantKind | PlantConstructionType | YearPlantOriginallyConstructed | YearLastUnitOfPlantInstalled | NetPeakDemandOnPlant | PlantHoursConnectedToLoad | NetContinuousPlantCapability | NetContinuousPlantCapabilityNotLimitedByCondenserWater | NetContinuousPlantCapabilityLimitedByCondenserWater | PlantAverageNumberOfEmployees | NetGenerationExcludingPlantUse | CostPerKilowattOfInstalledCapacity | OperationSupervisionAndEngineeringExpense | FuelSteamPowerGeneration | CoolantsAndWater | SteamExpensesSteamPowerGeneration | SteamFromOtherSources | SteamTransferredCredit | ElectricExpensesSteamPowerGeneration | MiscellaneousSteamPowerExpenses | RentsSteamPowerGeneration | Allowances | MaintenanceSupervisionAndEngineeringSteamPowerGeneration | MaintenanceOfStructuresSteamPowerGeneration | MaintenanceOfBoilerPlantSteamPowerGeneration | MaintenanceOfElectricPlantSteamPowerGeneration | MaintenanceOfMiscellaneousSteamPlant | PowerProductionExpensesSteamPower | ExpensesPerNetKilowattHour
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
12 | C001130 | 533aafa3-c8d2-4c5d-9a31-b3fe1ed29f21 | 2021-01-01 | 2021-12-31 | $— | 8.0 | — | None | None | NaN | NaN | NaN | NaN | NaN | NaN | NaN | NaN | NaN | NaN | NaN | NaN | NaN | NaN | NaN | NaN | NaN | NaN | NaN | NaN | NaN | NaN | NaN | NaN | NaN | NaN | NaN


```
- `next_column`

**Comment by cmgosnell** [comment]
@zaneselvans  do you think it's a good idea to move all of the mapping that is currently being done via `pudl.helpers.cleanstrings` into the metadata encoder?

**Comment by zaneselvans** [comment]
We talked about this on the phone but, I think that given there are literally **thousands** of bad strings which we're cleaning up in (especially) the FERC 1 tables, it's qualitatively a different problem, even if structurally it's similar or the same. Rather than transforming several iterations of historical codes, plus a few weird values, to canonical codes, it's more like a wholesale categorization of something that's not even attempting to be a coded column to begin with.

**Comment by zaneselvans** [comment]
I think given that we've merged in the steam table specific stuff into `xbrl_steam`, and have #1705 as a separate issue for dealing with the utility ID assignments, this can probably be closed now.
