### ISSUE TITLE
Handle GCS Cache flakiness

### ISSUE THREAD

**Issue by bendnorman** [catalyst-cooperative/pudl#1734]
About a quarter of nightly builds fail due to a GCS error that happens at unpredictable points in the ETL:

```bash
Traceback (most recent call last):
  File "/home/catalyst/env/bin/pudl_etl", line 33, in <module>
    sys.exit(load_entry_point('catalystcoop.pudl', 'console_scripts', 'pudl_etl')())
  File "/home/catalyst/src/pudl/cli.py", line 131, in main
    pudl.etl.etl(
  File "/home/catalyst/src/pudl/etl.py", line 463, in etl
    etl_epacems(datasets["epacems"], pudl_settings, ds_kwargs, clobber=clobber)
  File "/home/catalyst/src/pudl/etl.py", line 339, in etl_epacems
    df = pudl.extract.epacems.extract(year=year, state=state, ds=ds)
  File "/home/catalyst/src/pudl/extract/epacems.py", line 152, in extract
    return ds.get_data_frame(partition).assign(year=year)
  File "/home/catalyst/src/pudl/extract/epacems.py", line 107, in get_data_frame
    archive = self.datastore.get_zipfile_resource(
  File "/home/catalyst/src/pudl/workspace/datastore.py", line 371, in get_zipfile_resource
    return zipfile.ZipFile(io.BytesIO(self.get_unique_resource(dataset, **filters)))
  File "/home/catalyst/src/pudl/workspace/datastore.py", line 360, in get_unique_resource
    _, content = next(res)
  File "/home/catalyst/src/pudl/workspace/datastore.py", line 340, in get_resources
    if self._cache.is_optimally_cached(res) and skip_optimally_cached:
  File "/home/catalyst/src/pudl/workspace/resource_cache.py", line 222, in is_optimally_cached
    return cache_layer.contains(resource)
  File "/home/catalyst/src/pudl/workspace/resource_cache.py", line 142, in contains
    return self._blob(resource).exists()
  File "/home/catalyst/env/lib/python3.10/site-packages/google/cloud/storage/blob.py", line 706, in exists
    client._get_resource(
  File "/home/catalyst/env/lib/python3.10/site-packages/google/cloud/storage/client.py", line 366, in _get_resource
    return self._connection.api_request(
  File "/home/catalyst/env/lib/python3.10/site-packages/google/cloud/storage/_http.py", line 73, in api_request
    return call()
  File "/home/catalyst/env/lib/python3.10/site-packages/google/api_core/retry.py", line 283, in retry_wrapped_func
    return retry_target(
  File "/home/catalyst/env/lib/python3.10/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/home/catalyst/env/lib/python3.10/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 GET https://storage.googleapis.com/storage/v1/b/zenodo-cache.catalyst.coop/o/epacems%2F10.5281-zenodo.4660268%2Fepacems-2016-nh.zip?userProject=catalyst-cooperative-pudl&fields=name&prettyPrint=false: User project specified in the request is invalid.
```

It typically happens during the CEMS pipeline but at seemingly random partitions. The error says `catalyst-cooperative-pudl` projoect is invalid which is weird given the ETL successfully completes the request hundreds of times before failing. Maybe adding a retry to the GCS client will do the trick. 

TODOs:
- [x] Upload new CEMS archive to GCS.
- [x] Recreate error
- [x] Add a retry

**Comment by bendnorman** [comment]
The nightly builds for `8e0f1b9ec089b994f855f74849f6026fc991e33c-dev` failed because the `GCSCache` was trying to write a new zenodo archive to the cloud bucket but didn't have permission to write to the bucket. Adding the Bucket Writer role to the VM service account resolved the issue. 

Bad news is the the etl hit a zenoodo time out trying to read to first epacems partition.

**Comment by bendnorman** [comment]
I was able to reproduce the original bad request error after 11 iterations through the entire epacems dataset on the vm.

**Comment by zaneselvans** [comment]
Given the recent (and likely recurring) EIA API failure, maybe a quick temporary fix would be to have the current fuel filling fail gracefully if there's no `API_KEY_EIA` set in the environment, and then remove it from the environment (which is how the tests are set up to work, and how I disabled the EIA API calls in the tests)

**Comment by bendnorman** [comment]
Do the tests already fail gracefully if there's no `API_KEY_EIA`?

**Comment by bendnorman** [comment]
Oh my goodness, I'm still getting the BadRequest error after adding the retry ([the logs](https://console.cloud.google.com/storage/browser/_details/pudl-etl-logs/ddd2583e74bb8b65c7fcc187414bce30bba26002-dev/pudl_out/pudl-etl.log)). 

I doubled check the [requester pays documentation](https://cloud.google.com/storage/docs/requester-pays) to make sure I wasn't missing anything:

> **Once enabled, only the following users can access the bucket or its contents:**
> Requesters who [include a billing project in their request](https://cloud.google.com/storage/docs/using-requester-pays#using). The project used in the request must be in good standing, and the user must [have a role](https://cloud.google.com/storage/docs/access-control/using-iam-permissions#project-add) in the project that contains the serviceusage.services.use permission. The Service Usage Consumer role contains the required permission.

`deploy-pudl-vm-service-account` has the  Service Usage Consumer role and the user project is included in the request. This the example request pays API request:

```
curl -X GET \
  -H "Authorization: Bearer OAUTH2_TOKEN" \
  -o "SAVE_TO_LOCATION" \
  "https://storage.googleapis.com/storage/v1/b/BUCKET_NAME/o/OBJECT_NAME?alt=media&userProject=catalyst-cooperative-pudl"
```
This is the API request throwing the error:
```
https://storage.googleapis.com/download/storage/v1/b/zenodo-cache.catalyst.coop/o/epacems%2F10.5281-zenodo.6910058%2Fepacems-1999-vt.zip?alt=media&userProject=catalyst-cooperative-pudl
```

The user project is clearly included in the API request.

## Possible solutions
- I could play around with some of [these retry parameters](https://googleapis.dev/python/google-api-core/latest/retry.html#google.api_core.retry.Retry). The default parameters retry the call for 120 seconds. [Docs](https://cloud.google.com/storage/docs/retry-strategy#exponential-backoff) on how the retry algorithm works. 
- Mount a volume with a local cache of the zenodo archives. This would probably do the trick but it seems silly we can't reliably access a GCS requester pays bucket from a google VM :(
- Maintain an additional private zenodo-cache bucket that doesn't have requester pays enabled. This does leave the potential for the two buckets to get out of sync. 
- Reach out to folks at pangeo. It looks like some of their users have run into [this issue before](https://discourse.pangeo.io/t/introduction-to-pangeo/659/7).
- Catch the error and let the user know a CEMS partition was skipped. I don't love this idea :/ 

@silky any chance you've run into this type of GCS flakiness before?

**Comment by zaneselvans** [comment]
> Do the tests already fail gracefully if there's no `API_KEY_EIA`?

Yes, if there's no `API_KEY_EIA` it sets the fuel price filling argument in the `pudl_out` objects being used in the tests to `False`

**Comment by zaneselvans** [comment]
Have Pangeo folks had the same problem where they are actually providing the billing project ID and it still doesn't work? That discussion looked like it was about the need to configure things to work with requester pays more generally (which if I understand your description, we are!)  But if this is a more general problem that comes up with requester pays data access I imagine @rabernat et al. would have encountered it!

**Comment by silky** [comment]
> @silky any chance you've run into this type of GCS flakiness before?

Unfortunately not; I think I agree with you that either doing the retry, or just doing your second idea of mounting a local cache seems useful.

**Comment by zaneselvans** [comment]
It's a little unsatisfying, but switching to using the gs://internal-zenodo-cache.catalyst.coop bucket seems to have solved this issue. I'm a little worried about the reliability of providing our data via requester pays buckets now. 🙁 

But maybe we should close the issue since it's not blocking us anymore?
