### ISSUE TITLE
Save zenodo-cache log storage bucket

### ISSUE THREAD

**Issue by bendnorman** [catalyst-cooperative/pudl#1741]
Similar to #1205 but for the zenodo-cache bucket. We expect only Catalyst folks will be using this bucket but you never know! 

Follow [these docs](https://cloud.google.com/storage/docs/access-logs).

**Comment by bendnorman** [comment]
I learned Cloud Audit Logs contain a lot of information about Cloud bucket requests. The most interesting piece of information is the email used to authenticate to the cloud bucket. This information is not captured with Usage logging. However, usage logging contains response size but Audit logs do not. We might be able to merge the two datasets together on the insert_id. 

I set up a log sink that dumps logs from zenodo-cache to the `zenodo_cache_bucket_logs` Bigquery Dataset in the `catalyst-cooperative-pudl` project. This dataset will update in real time. 

I also set up usage logging for zenodo-cache which dumps logs into the `zenodo-cache-bucket-logs` bucket. This info is updated every hour.

**Comment by bendnorman** [comment]
I ran into a weird issue when copying data from zenodo-cache.catalyst.coop using my non catalyst gcp account. I’m able to get items from the intake catalog using my non catalyst gcp account but I get a permission issue when trying to download a file from the zenodo-cache.

**Comment by zaneselvans** [comment]
Did you figure out what was going on with the permissions here? Should I take a look and try to make the zenodo-cache setup the same as intake?

**Comment by bendnorman** [comment]
I have not looked into it. That would be great if you could compare the permissions.

**Comment by zaneselvans** [comment]
Okay, I'll try and fix it now.

**Comment by zaneselvans** [comment]
I switched the permissions for `allUsers` to be `Storage Object Viewer` to match the Intake catalog bucket. Previously the zenodo-cache bucket was using a legacy storage bucket reader permission which I think didn't have object / bucket listing permissions? Do you want to give it another try?

**Comment by bendnorman** [comment]
Amazing that did trick, thanks!

**Comment by zaneselvans** [comment]
@bendnorman should this issue be closed? (I'm chasing down zombie issues that are "in progress" or "in review")

**Comment by bendnorman** [comment]
Oops! Yes this is done. We have a bucket called `zenodo-cache-bucket-logs` that stores all of the logs for the public-facing `zenodo-cache.catalyst.coop` bucket.
