### ISSUE TITLE
Figure out what CEMS `UNIT_ID` and `FAC_ID` are

### ISSUE THREAD

**Issue by aesharpe** [catalyst-cooperative/pudl#1772]
CEMS data have two mystery columns: `UNIT_ID` and `FAC_ID`. There are two unit columns in the data, `UNITID` maps to EPA "smokestacks" or emissions units and is referenced in the epacamd_eia_crosswalk. However, `UNIT_ID` is also there and doesn't seem to fulfill any particular purpose. Same with `PLANT_ID_CAMD` and `FAC_ID`. 

Rather than just delete them, I want to investigate more and see what they are!

Here's a lead from @zaneselvans mentioned in #1692
_A bit of searching suggests that facility_id in the CEMS context refers to the EPA Greenhouse Gas Reporting Program ID. Maybe rename it to something more legible like ghgrp_facility_id_epa._

**Comment by aesharpe** [comment]
Potentially useful links: 

- https://campd.epa.gov/data/custom-data-download
-https://ofmpub.epa.gov/enviro/fii_query_detail.disp_program_facility?pgm_sys_acrnm_in=EIA-860&pgm_sys_id_in=599
- https://enviro.epa.gov/enviro/EF_METADATA_HTML.ef_metadata_page?p_column_name=FACILITY_ID&p_table_name=AA_CEMS_DETAILS&p_topic=

**Comment by zaneselvans** [comment]
I'll try and remember to tweet this out tomorrow AM and see if we can get some leads from Energy Twitter if we don't have it figured out.

**Comment by aesharpe** [comment]
Ok it looks like the `FAC_ID` is some sort of "business database id"
https://ghgdata.epa.gov/ghgp/service/facilityDetail/2020?id=1001124&ds=E&et=&popup=true 

**PUDL Data**
![Screen Shot 2022-07-22 at 2.51.43 PM.png](https://images.zenhubusercontent.com/5e84c333ad36eafe6787e5b9/4bae158f-6d90-422d-b3c8-5cc2ea0f2592)

**EPA Data**
![Screen Shot 2022-07-22 at 2.50.17 PM.png](https://images.zenhubusercontent.com/5e84c333ad36eafe6787e5b9/c4b657af-cc8c-4f2f-8aab-e1f14a975464)

**Comment by aesharpe** [comment]
I asked the EPA what their Business Database was and whether it was important and they got back to me on twitter: 

![Screen Shot 2022-07-26 at 3.35.10 PM.png](https://images.zenhubusercontent.com/5e84c333ad36eafe6787e5b9/a909933b-6614-444a-90fa-bec65bdc0ce8)

**Comment by aesharpe** [comment]
After emailing with Travis from EPA, I'm now aware that the `UNIT_ID` field is a unique identifier used internally at EPA. Without UNIT_ID, the only way to uniquely identify an epa "unit" is by combining the ORISPL_CODE and the UNITID fields.

**Comment by zaneselvans** [comment]
Can you put a table here explaining what all of the original columns mean?
