### ISSUE TITLE
Fix transform for `f1_retained_erng` xbrl + dbf

### ISSUE THREAD

**Issue by aesharpe** [catalyst-cooperative/pudl#1811]
## Updated tasklist
- [ ] Add a method to `process_xbrl_metadata()` that adds a completely new calculation to a field where one is missing
- [ ] Use this method to add calculations for `retained_earnings_ferc1` to the transform

## Table Notes
* The DBF table is almost entirely unstructured, with at least 6 freeform subsections, each of which has a subtotal -- the subtotal rows have well defined meanings, but only the row number and overall category is standardized for the rows making up the sections.
* XBRL has again broken out these unstructured tables into their own unstructured, sequenced tables containing a description + amount, with (presumably) the total from those tables matching the totals reported in the coordinating structured table. But we need to confirm that.
* The main table also has a start + end of year balance in the instant table `retained_earnings_118_instant`.
* There's also an unstructured instant table: `retained_earnings_appropriated_118_instant` with end of last year, end of this year dates.
* Good table for testing whether unstructured tables sum to reported totals, since everybody reports unstructured data.

## Transformation Plan
* Row numbers don't change over the years, but do need to be labeled for DBF + XBRL concatenation.
* Extreme case of unstructured data with only aggregate values showing up in the structured table.

**Comment by zaneselvans** [comment]
Whoops, forgot there are a bunch of unstructured tables yet to go here.

**Comment by e-belfer** [comment]
In issue #2016 and #2581 we ran into some errors with this table. Here are some compiled notes:

- Has `starting_balance` and `ending_balance` and also `amount`. Unclear looking at the form what `amount` corresponds to. Mostly NA start/end balances. Looking at form it seems like it might be unstructured data? Something is wrong here. The primary affected FERC account is getting lost, the freeform `item` description is also being lost. I think we need to revisit this transform.
- In 2020 and earlier data, they seem to have put some ending_balance values in the amount column.

**Comment by e-belfer** [comment]
First-pass assessment of explosion-specific problems with this table:
- Fields sum to one another, but there are no calculations at all defined for this table
- Unclear distinction between starting_balance, ending_balance and amount for some line items
- Item and primary account only found in processed dbf data, not in processed xbrl.
