### ISSUE TITLE
Re-factor datastore management

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#182]
The PUDL datastore management script was originally designed to handle a few data sources all of which had similar structures -- one big ZIP file, released once per year, containing all the data. This is no longer the case, and looking at the other data sources we want to provide access to, and the mess that the datastore management module has become, it's clear we need to do a redesign.

**Some considerations:**
* It should be easy for a new contributor to add the logic required to integrate a new data source into the data store -- the functionality that needs to be implemented should be well defined.
* We need to be able to handle data that is published on different schedules, in different formats, partitioned in a variety of ways. Some examples:
  * EPA CEMS comes out monthly, is partitioned by state, month, and year, and is available on an FTP server as compressed CSVs.
  * FERC Form 1 is published annually as a single giant compressed archive of a bunch of binary data files.
  * The MSHA Mines dataset is updated weekly, and all the data for each table is contained in a single pipe (|) separated value file.
  * The ISO LMP data is available from a variety of different web-based APIs, and may be updated every few minutes.
* Data that has already been released -- even "final" releases -- is sometimes updated or otherwise changed by the reporting agencies. This means some kind of versioning would be useful -- a given ETL run will have taken a particular version of (e.g.) the EI A923 data for 2009-2018 -- just saying "EIA 923 for 2009-2018" doesn't fully specify what data went into it.
* This archive wouldn't be meant to do any data processing -- just to provide the raw inputs in a standardized format. This might mean standardizing directory structures or filenames though. E.g. some of the FERC Form 1 data comes in ZIP archives with parent directories that have different names, even though the bottom directory with all the DBF files in it is always structured the same. Similarly over the years the names of the EIA 923 spreadsheet files that are published have changed -- this raw input archive could standardize the file/directory names and directory structure, without touching the contents of the files, for easier access.
* Most of the Python libraries we're using are perfectly happy to read directly from gzipped files, and the compression ratios on some of the data are 20:1. We might consider making each "unit" of downloaded raw data (like the 3 spreadsheets that make up a year's worth of EIA 923 data) into a single .gzipped archive that remains compressed, to simplify the layout of a local data store, and to avoid taking up huge quantities of local disk space.
* What "current" version of the data should we be checking against when deciding whether we need to update the datastore?  If it's a local copy of the data, then we're committing ourselves to keeping that local copy around for comparison's sake.  If it's an archived version (see below) then the crawler will need to download the most recently archived version, or at least some of its metadata (last date of modification for each file, hash/checksum for each file).
* In an ideal world, we'd be able to check whether a file has been changed and needs to be updated without actually downloading it -- but are the datestamps available via FTP & HTTP reliable?
* In the context of API (rather than file) based data sources (like the ISO/RTO data), how can we know whether the historical data has changed? Maybe that's beyond the scope of this project, and we'll be doing well enough if we can just build up our own historical time series as we go.

**A publicly accessible versioned datastore**
Most of the reporting agencies don't attempt to make the data available in bulk, in a programmatically accessible way, and they certainly don't try and curate the various versions of data they release. We need to do some version of this for ourselves and PUDL, but we could also do it in a way that makes such a resource available to the broader community of folks who are using this data, and have this versioned archive of the raw input data be something that we and others depend on, which is somewhat separated from PUDL as a whole  One way to do this would be to periodically check whether any of the data has changed, and if so, package up a new version and upload it to a versioned archive on https://zenodo.org which would then be durably available, cite-able, and accessible via their RESTful API.

Using Zenodo would mean we don't have to take on the long-term responsibility of maintaining the archive or providing the storage.  We would just need to curate the periodic automatic updates that happen as new data is released, or old versions are changed. This could look something like the way `conda-forge` works -- with one or several Github repositories that get updated over time to deal with changes in download URLs, unzipped directory hierarchies, new data releases etc. and which are used by a periodically scheduled job that runs on GCP to detect changes, create a new archive, and update the appropriate Zenodo resources.

**Data sources to consider**
Whatever structure we choose should be able to accommodate, for example:
* EIA 860
* EIA 861
* EIA 923
* FERC Form 1
* FERC Form 714
* FERC EQR
* EPA CEMS
* ISO/RTO LMP etc.
* PHMSA Pipelines
* MSHA Mines
* USGS Water Census

**Comment by karldw** [comment]
Request: can we totally disable loading some datasets? It would make it way faster to test specific things if we don't have to load 2+ form 1 years every time. I also imagine some people would want to disable CEMS (this could even be the default), since it's so large.

**Comment by zaneselvans** [comment]
Yeah, I wonder if want to set things up to bring in each data source independently, and to then determine which glue is required to connect the pairs of datasets that have come in.

**Comment by zaneselvans** [comment]
See also #314 reported by @gschivley.

**Comment by zaneselvans** [comment]
So, we're (aka @ptvirgo) in the process of re-writing the datastore management code, and splitting off the data acquisition into a different tool that will produce a versioned archive of the original data as it was available from the government sources, which gets updated whenever they change the data (as they seem to on a regular basis) which will facilitate reproducibility without requiring us to archive all the input files individually with any data publication. The plan is to have it run as a daily cron job that notices when files get changed, and automatically generates a new versioned deposit at Zenodo with a DOI etc. that can be cited directly, and accessed via their clean REST API, which will hopefully let more people build stuff that can use programmatic access to the raw data even if they aren't using PUDL.

In addition, the data as it comes from EIA, FERC, etc. often changes file names and directory structures (inside the ZIP files) a bit over the years, and we are wondering (@gschivley @karldw @joshdr83 @briannacote) whether it would be more useful to have the versioned raw data archive at Zenodo consist of *exactly* the same files that have been downloaded from EIA/FERC/etc. including the preservation of their inconsistent filenames and directory structures (ugh), or whether it would be better to standardize those names and directory structures (without touching the contents of the original files themselves) before archiving them.

Building this standardization logic into the tool that downloads and archives new versions of the data would mean that someone could easily make programmatic use of the Zenodo archive without needing to use our tooling, and without needing to re-implement the logic that deals with these inconsistencies.

However, it would also mean that the files aren't utterly pristine.

Which do y'all think would be the better option?

**Comment by karldw** [comment]
@zaneselvans, I don't have a strong opinion here. If you wanted to be sure absolutely no information was lost, you could add a log file that describes how each file was renamed.

**Comment by joshdr83** [comment]
That seems like a good compromise!

Joshua Rhodes
https://sites.google.com/site/joshdr83/
@joshdr83

**Comment by ptvirgo** [comment]
If no one has a strong preference then:

1. Munging it first has a higher overall complexity which means:
2. You get to pay me more money to build something nobody really needs.

Which I'm mostly fine with, as long as everyone is clear that this is 
what you're asking for.
