### ISSUE TITLE
Add a view for the CEMS data

### ISSUE THREAD

**Issue by karldw** [catalyst-cooperative/pudl#184]
I can add this.

Design decisions:
- What variables should be in the view?
  - Date
  - EIA info?
  - UTC time, when that's ready
- Should the view be materialized?
- It seems like SQLAlchemy doesn't natively know about views, but there are packages on pypi that add support. Do you want to add another dependency?  

See: https://github.com/catalyst-cooperative/pudl/issues/171#issuecomment-398653563

**Comment by karldw** [comment]
While we're at it, should we drop all of the *_rate_lbs_mmbtu variables from the table and put them in a view?

**Comment by zaneselvans** [comment]
I think this should be rolled in with #171 and the normalization & naming stuff that @cmgosnell is moving into.
