### ISSUE TITLE
Are some CEMS UTC datetimes off by an hour?

### ISSUE THREAD

**Issue by grgmiller** [catalyst-cooperative/pudl#1864]
In the CEMS transformation step, the reported operating hour is converted from local time to UTC time based on each plant's local timezone reported in `plants_entity_eia`. However, I am wondering if in some cases we are currently changing the data to the wrong UTC time. For the Open Grid Emissions project, we convert `datetime_utc` back to `datetime_local` based on each plant's reported local timezone from `plants_entity_eia` so that we can assign a monthly `report_date` to each column that can be used to match the CEMS data with the monthly totals reported in EIA-923. Because we want a complete timeseries for each unit-month, we drop any observations in unit-months with incomplete hourly data. During this process, I've found that in many cases, incomplete months contain only a single hourly value at the very end of the month. This made me suspicious (why would a plant only report the last hour of a month?), and made me wonder if maybe the datetime is off by an hour.

I would have to look into specific examples to see if this is actually the case, but here is my hypothesis about what might be happening:

Because the raw CEMS data is reported by state-month, I am wondering if the `op_hour` column represents the local time for each plant, or a uniform local time for the entire state. In states that span multiple time zones (AZ, OR, ID, ND, SD, NE, KS, TX, KY, TN, IN, FL), this could make a difference. If the reported operating hour is uniform for the entire state, then the transform step would need to first convert local reported time to local plant time, then to UTC. 

To check into this I need to:
- Examine specific examples of unit-months with only a single hour reported at the end of the month
- Find out where these units are located
- Look at the raw CEMS data to see if these single hours are present there
- Try to look into the CEMS documentation about what the operating hour represents

Other possible explanations:
- Maybe some issue with DST?
- Is the version of `plants_entity_eia` used to convert to UTC different from the one I'm using to convert back?

**Comment by grgmiller** [comment]
See https://github.com/singularity-energy/open-grid-emissions/issues/194

So after looking into this, I discovered that the reason that I was seeing months with single hour datapoints for some units is because the raw CEMS files from the FTP site report all data in local standard time (not local prevailing time). So when these data are converted to local prevailing time, there are cases (generally for plants that only report during the ozone season and have data through Sept 30 at 11pm) when there is a single hour of data for October 1 at Midnight in local prevailing time.

I also did not find any evidence that there were a lot of plants located in the states that have 2 time zones that were off by an hour. However, I still want to double check with EPA the process they use for converting timezone data for each plant.

**Comment by grgmiller** [comment]
I accidentally closed this issue when I just meant to comment so re-opening. 

One thing I'm noticing is that in `pudl.transform.epacems`, it assumes that the reported operating hour is the plant's local standard time (rather than the state's local standard time). This is something I want to confirm with EPA before closing this.

**Comment by zaneselvans** [comment]
Ugh. Timezones. 😵‍💫

**Comment by grgmiller** [comment]
According to email communication with the EPA CAMPD team, "OP_HOUR represents each plant's local standard time. Therefore, the OP_HOUR data, including the FTP datasets, correspond to each facility's local standard time even if the data set is for a state which uses two different time zones."

This confirms that the current transformation steps for the CEMS data are correct.

**Comment by zaneselvans** [comment]
Whew!
