### ISSUE TITLE
Datasette has `plants_entity_eia` file with missing columns

### ISSUE THREAD

**Issue by grgmiller** [catalyst-cooperative/pudl#1867]
It appears that the version of the `plants_entity_eia` table currently hosted on Datasette (https://data.catalyst.coop/pudl/plants_entity_eia) is missing most of the columns it should contain per https://catalystcoop-pudl.readthedocs.io/en/latest/data_dictionaries/pudl_db.html#plants-entity-eia.

**Comment by grgmiller** [comment]
These columns have moved to `plants_eia860` in the dev branch.

**Comment by zaneselvans** [comment]
Ah yeah, sorry the Datasette deployment generally follows `dev` for the time being.

**Comment by zaneselvans** [comment]
I have updated the documentation build to serve up the `dev` branch for the "latest" version on RTD, so this discrepancy shouldn't show up in the future:

https://catalystcoop-pudl.readthedocs.io/en/latest/
