### ISSUE TITLE
Update tests to reflect dagster changes

### ISSUE THREAD

**Issue by bendnorman** [catalyst-cooperative/pudl#1874]
The dagster changes break our existing integration tests and fixtures. Here is an overview of what needs to change:

## Tests `test/integration`
* **`console_scripts_test.py`: Changes to these tests depend on if we want to maintain our existing cli commands. If we do, we can pass the cli args as dagster config and execute ETL jobs using the [dagster python API](https://docs.dagster.io/concepts/ops-jobs-graphs/job-execution#python-apis). An alternative would be to deprecate our CLI commands like `pudl_etl` and just use the [dagster CLI](https://docs.dagster.io/concepts/ops-jobs-graphs/job-execution#dagster-cli). I think I’m in favor of maintaining our existing CLI commands for now and maybe include warning that in the future they will be deprecated in favor of using dragsters UI and CLI commands. However, we’ll have to replace the dataset_settings resource with an `etl_settings` resource. Also the yaml formats for dagster configuration and the `pudl_etl` command are different. We'd have to keep copies of both in `src/pudl/package_data/settings` and we'd have to translate the current settings file structure into the dagster structure at runtime.**
* datasette_metadata_test.py: Nothing here touches dagster stuff
* epacems_test.py: 
	* test_epacems_parallel will break because `pudl.etl.etl_epacems()` is now the `hourly_emissions_epacems` asset. Update this test to create asset context from fixtures and run the `hourly_emissions_epacems` asset. See [Testing software-defined-assets](https://docs.dagster.io/concepts/testing#testing-software-defined-assets) for an example. 
* etl_test.py:
	* Will mostly require updating fixtures
* glue_test.py:
	* Will mostly require updating fixtures
* output_test.py
	* Interacts with the PudlTabl class so nothing really needs to change here
* zenodo_datapackage_test.py
	* Doesn’t touch dagster stuff

## Fixtures
Most of the work for this issue will be updated our pytest fixtures.

* pudl_ds_kwargs and pudl_datastore:
	* These two fixture could be combined. To create the datastore resource, pass the pytest cli args in the `request.config` fixture to `dagster.build_init_resource_config`  function to create the resource context. See [Testing resource initialization](https://docs.dagster.io/concepts/resources#testing-resource-initialization).
* pudl_settings_fixture: simplify or remove to use just the env vars?
* etl_settings
	* This fixture’s design hinges on whether or not we want to keep our existing CLI commands around. 
* pudl_engine: 
	* This fixture runs the fast etl if pytest is told not to use an existing pudl.sqlite database.
	* Should the ETL pull a fresh batch of archived data to a temporary directory or use and existing cache?
	* **How to set PUDL_OUTPUT path to temporary directory without having to change the config for every resource and asset that needs it? Is it possible to set and a temporary env var for pytest? Should we create a single pudl_output resource so it only has to be configured in one place?**
* ferc1_engine_xbrl and ferc1_dbf_sql_engine:
	* These two fixtures will create op context from settings and datastore fixtures and execute their respective ops in the ferc_to_sqlite graph. [See Test ops for an example](https://docs.dagster.io/concepts/testing#testing-ops).
* ferc1_xbrl_taxonomy_metadata: 
	* The pudl.extract.ferc1.extract_xbrl_metadata() function has been replaced by the xbrl_metadata_json asset. 
	* The only input to the xbrl_metadata_json fixture is the PUDL_OUTPUT path. 

## Division of Work
I bolded two design issues that should be addressed prior to converting the tests and fixtures. Would love your input @jdangerx and @zschira. 

I think this issue could be tackled by one person within a sprint. Maybe @jdangerx or @zschira could team up with me to tackle this issue?

Also how should we structure this work on github? Create a PR off of #2104 that contains all integration test updates?

**Comment by zschira** [comment]
> I think I’m in favor of maintaining our existing CLI commands for now and maybe include warning that in the future they will be deprecated in favor of using dragsters UI and CLI commands

I definitely lean this way as well. I think that keeping the interface as unchanged as possible for the initial dagster release seems like the right approach. This will hopefully help smooth out the transition.

> How to set PUDL_OUTPUT path to temporary directory without having to change the config for every resource and asset that needs it? Is it possible to set and a temporary env var for pytest? Should we create a single pudl_output resource so it only has to be configured in one place?

We could potentially have a fixture that overrides your `PUDL_OUTPUT` environment variable, then resets it during cleanup. Maybe not the cleanest approach, but I think it should work.

**Comment by jdangerx** [comment]
> I think I’m in favor of maintaining our existing CLI commands for now and maybe include warning that in the future they will be deprecated in favor of using dragsters UI and CLI commands

I think keeping our existing commands as wrappers around dagster is fine!

> However, we’ll have to replace the dataset_settings resource with an etl_settings resource. Also the yaml formats for dagster configuration and the pudl_etl command are different. We'd have to keep copies of both in src/pudl/package_data/settings and we'd have to translate the current settings file structure into the dagster structure at runtime.

Could we go backwards and `pudl_etl` read dagster-formatted YAML files? Then we can have one set of configs feeding both dagster-CLI and OG-pudl invocations.

Could we also load those YAMLs into the Dagit UI without having to define the configs in `etl/__init__.py`? Seems like we could load the YAML into a dict & call it day, but I haven't tried that. Then we could have the one set of configs feed everything which would be great!

> How to set PUDL_OUTPUT path to temporary directory without having to change the config for every resource and asset that needs it? Is it possible to set and a temporary env var for pytest? Should we create a single pudl_output resource so it only has to be configured in one place?

I think we can just set the env var in `conftest.py` ([stackoverflow agrees](https://stackoverflow.com/questions/69623784/how-to-set-environment-variable-in-pytest)), so long as we're not reading the env var at import-time - setting env vars should only affect the process & any child processes.

**Comment by jdangerx** [comment]
As for breaking up the work - I think we can probably split this into separate PRs (into the feature branch) for each fixture that needs fixing, and we can watch the test error go down towards 0 with each one.

**Comment by jdangerx** [comment]
There might be some dependencies/interactions - maybe we can chart out which ones should be worked on first.

**Comment by zschira** [comment]
I think the only obvious dependency consideration is that we we'll need to create the settings and datastore fixtures first. From a quick glance I don't see any more complicated dependencies than that. I also think I might take a crack at the CLI wrapping before getting into the tests. I'll probably create  separate issue for that.

**Comment by zschira** [comment]
> Could we also load those YAMLs into the Dagit UI without having to define the configs in etl/__init__.py? Seems like we could load the YAML into a dict & call it day, but I haven't tried that. Then we could have the one set of configs feed everything which would be great!

I think this is the approach that I'm going to go with. We can make the settings files look like `DatasetsSettings` object, then convert to a dict and give that to dagster as the config

**Comment by bendnorman** [comment]
> Could we go backwards and pudl_etl read dagster-formatted YAML files? Then we can have one set of configs feeding both dagster-CLI and OG-pudl invocations.

> Could we also load those YAMLs into the Dagit UI without having to define the configs in etl/__init__.py? Seems like we could load the YAML into a dict & call it day, but I haven't tried that. Then we could have the one set of configs feed everything which would be great!

These are both great ideas!

@zschira I think breaking out the CLI changes into a separate issue is a good idea. The current settings files contain configuration for the pudl_etl and ferc_to_sqlite scripts. The dagster branch creates separate resources for the `DatasetSettings` and `FercToSqliteSettings`. Are you thinking about creating a single resource for the `EtlSettings` that is used by the pudl_etl and ferc_to_sqlite `Definitions`?

Maybe the steps here are:
1. Update the existing CLI commands to read in dagster style config files and run dagster jobs.
2. Update the fixtures to use our new dagster resources.
3. Propogate the fixture changes to the integration tests.

**Comment by bendnorman** [comment]
@zschira We need to remember to run the `SQLiteIOManager.check_foreign_keys()` in the `pudl_engine` fixture and remove the temporary `tests/validation/database_test.py` file.

**Comment by bendnorman** [comment]
Closed by #2299
