### ISSUE TITLE
Standardize module divisions within init.py

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#189]
We've re-organized how the ETL process works, but haven't implemented that re-organization in a standard way across all the EIA data. Needs to be made uniform -- division between `init.py` and the `extract` and `transform` modules, so it's easier to read along.

**Comment by cmgosnell** [comment]
I think the issue was actually the ferc ETL process... _ETL_eia has only pudl.(step).eia(datasource).(step) in it. I just cleaned that up and I'm testing it now. When I commit I'll close this issue but let me know if I missed something here.
