### ISSUE TITLE
fill-in `balancing_authority_code_eia` pre-2013

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/pudl#1909]
Since we converted the `balancing_authority_code_eia` to a annually-varying plant attribute as opposed to a static attribute there are no longer any codes before 2013. The goal of this issue is to establish a methodology for filling in those codes and insert it into the output layer.

In my opinion, there are two main avenues for doing this filling in:
* **backfilling** from the 2013 value
* using the most **consistent** reported value

## Running notes/ideas on the differences of these two methodologies
We start with a total of 43% of the records w/o a BA code.
- 74.7% of plant records without BA codes (60692) have the same BA codes from backfilling vs the most consistent static code.
  - [x] **solution:** use either the backfilled or consistent value. easy! -> results in 11.1% null BA codes
- 6.5% of plant records without BA codes (5264) have different BA codes from backfilling vs the most consistent static code.
   - A vast majority of these are plants that seem to have gotten gobbled up by SPP (cough cough i mean SWPP).
     - [x] **solution:** I'm very open to suggestions here but I think it seems pretty fair to use the backfilled value based on an understanding that SPP did indeed accumulate smaller BA's -> results in 10.9% null BA codes
   - There are 602 non-SPP associated records, which is 66 unique plants.
     - 45 of those plants seem to be plants that reported being in PACE (pacificorp east) for 2013 and PACW (pacificorp west) for all the other years AND are obviously located in PACW (bc they are in CA or OR).
       - [x] **solution**: use PACW for plants where the consistent BA code is PACW and the state is CA or OR. -> results in 8.3% of null BA codes
     - Still investigating the remaining  21 plants
- 18.2% of the plant records w/o BA codes (14852) don't have consistent enough BA codes (threshold rn is 70% consistency)
  - of these 1515 unique plants, only 48 of them ever have any BA code.
     - [ ] **solution**: for the i sometimes have codes... idk yet
        - 10 of these plants are now in SWPP so I'd again suggest to use the backfill option.
     - [x] **solution**: for the never have i ever had a ba code plants... they stay null ¯\_(ツ)_/¯. This is 7.8% of total plant records/17% of plant records w/o BA codes

This is in attempts to address a portion of the concerns raised in #1882 by @arengel.

**Comment by zaneselvans** [comment]
If 74.7% of plant records have the same BA codes from these two methods, and 6.5% have different codes, what's going on with the other 20% of plant records?

I agree that backfilling the little BA codes that become part of SWPP is the right thing to do for the output table. If someone wanted to project backward in time and gather up data from all the little BAs that eventually become SWPP, they can still do that based on the more recently associated BA codes.

From the work I did trying to clean up the BA territories, there was definitely some big mess with PACW & PACE, where in a few years the whole combined territory would be associated with a single BA code. I imagine this weirdness is related to whatever was affecting the EIA-861 territory / code reporting too, but it seems to be something systemic that affected a bunch of EIA data, and not just an isolated data entry issue.

**Comment by cmgosnell** [comment]
New comment about the straggler weirdo plants.

# probs backfill (2 or more years of "old" BA code
There are a handful of plants that have a `balancing_authority_code_eia_consistent_rate <= .8`, which is to say that they 
### plant ids:

- 99
- 56505
- 56591
- 56872
- 57404 # but this is a NY plant that reported being in ISNE.. did ISNE ever dip into NY?
- 58466 # but this is an AZ plant in CAISO for 2013-14?
- 58533

# WAUE>NWMT ? WAUE looks like the broader area?
Several plants went from reporting a BA of `WAUE` (`Western Area Power Administration - Upper Great Plains East`) to reporting a BA of `NWMT` (`NorthWestern Energy (NWMT)`)
### plant ids:

- 10138 
- 10784 
- 50931 
- 54006
- 56377 
- 56496 
- 57049
- 57748
- 57914

# ? idk what to do with these plants
### plant ids:

- 2124 # AECI -> SPA
- 56106 # NPPD -> SWPP -> WACM
- 56658 # SPS in 2013 -> ERCO, mistake or real?
- 57983 # SPS in 2013 -> ERCO, mistake or real?

**Comment by cmgosnell** [comment]
It would be simpler (albeit less potentially accurate at times) to clean some of these known weird codes (like the PACW/PACE incorrect codes) and then just use the back-filling across the board. Overall, that seems like it tends to be the right way to go.

**Comment by arengel** [comment]
A few comments on the stragglers, based on some research but mostly suspicions. 
1. In most of these cases, I would assume these are real BA changes. I'm pretty comfortable with v & vi since we would only be filling one year which makes 3 years in the first BA and then a change. ii also seems to make sense given the history. The rest might be best to leave as is without more information.
    1. 99 Tacoma to Puget Sound, could be a real BA transfer, would probably need to do some research to know for sure.
    2. 56505 I'd be more confident this change is real and correct. MISO South is a relatively [new addition](https://www.eia.gov/todayinenergy/detail.php?id=13511) though SPA is not mentioned as joining in the article, but it makes some level of sense that the plant might have become part of MISO anyway since it wasn't owned by SPA.
    3. 56591 & 56872 ...
    4. 57404 Seems unlikely that a 1.6 MW plant in the middle of NY would be part of ISNE but might not be the weirdest thing here.
    5. 58466 I say backfill the one blank year to CISO.
    6. 58533 I say backfill the one blank year to IID.
7. WAUE seems to have been a BA in the upper plains, most of which became part of SWPP somewhere around 2014. It also looks like parts of it were incorporated into NWMT, maybe those parts in the Western Interconnection. You'd think those plants would have been in WAUW to start, or have been added to it but I guess not. I think I'd assume this change is real and the plants should be in WAUE and then NWMT.
8. 56658 & 57983 are pretty weird. Their BA shows as SPS in 2013 but before that the `iso_rto_code` was SPP for a few years. 56658 is in the TX panhandle so the switch isn't so crazy, 57983 isn't so close to SPP so it's a little weirder.  IIRC ERCOT built a lot of transmission around that to integrate wind, perhaps the switch has something to do with that.

**Comment by zaneselvans** [comment]
This is merged and the updated tables are published on Datasette so I'm going to close this. Let us know / feel free to re-open if anything is still wonky @arengel
