### ISSUE TITLE
Save nightly build outputs prior to foreign key indexing

### ISSUE THREAD

**Issue by bendnorman** [catalyst-cooperative/pudl#1959]
While debugging #1954, I realized the database sizes of successful runs were larger than expected. This is because the `/devtools/datasette/publish.sh` script indexes the foreign keys, which increases the size of the dbs. Luckily, this isn't breaking anything, but I think it's best to save the databases as they are output by the ETL. We'll also save a little GCS space.

This can be resolved by copying the ETL outputs immediately after the ETL and tests finish.

**Comment by zaneselvans** [comment]
The FK indexing has been removed from the publish.sh script, so this is no longer relevant.
