### ISSUE TITLE
Create a Parquet IO Manager

### ISSUE THREAD

**Issue by bendnorman** [catalyst-cooperative/pudl#1974]
Create a dagster IO Manager that can read and write parquet files using pandas or dask data frames. Dagster provides a [nice example](https://github.com/dagster-io/dagster/blob/master/examples/project_fully_featured/project_fully_featured/resources/parquet_io_manager.py) for this type of IO Manager. 

This enables us to create assets that depend on CEMS data without needing to handle the IO management.

**Comment by bendnorman** [comment]
I'm still trying to work out the best way to implement this. I have two questions:

1. It might be difficult to take advantage of parallelism with dagster and produce a single epacems parquet file. Could we distribute a directory of parquet files where each file is a partition? It looks like dask supports loading partitioned data from a directory. 

2. Where can I find examples of analyses or output tables that load data from CEMS?

**Comment by zaneselvans** [comment]
You probably already saw it, but the code for producing a bunch of partitioned parquet files in parallel is already in there, it's just not the default output.
