### ISSUE TITLE
Use PUDL metadata sub package for dbf2sqlite function

### ISSUE THREAD

**Issue by bendnorman** [catalyst-cooperative/pudl#1975]
Currently the `dbf2sqlite` function:
1. Drops existing tables from the ferc1.sqlite db using `pudl.helpers.drop_tables()`
2. Gathers ferc1 table names using `pudl.extract.ferc1.get_dbc_map()`
3. `define_sqlite_db()` Creates sqlalchemy models for each table.
4. Extracts the raw data and writes it to the database.
5. Reads the `f1_respondent_id` tables from the db, does some pandas processing to insert missing ids, writes the changes back to the database. 

Is it possible to use PUDL's metadata sub package to handle the schema creation? This would allow us to re use the SQLite IO Manager #1972 we will create for the PUDL ETL, output and analysis table. If this is too big a lift, I think we could just wrap the `dbf2sqlite` function in an op and create an io manager for `_etl_ferc1()` that can read tables from the ferc1.sqlite database.

**Comment by zaneselvans** [comment]
> Is it possible to use PUDL's metadata sub package to handle the schema creation?

This isn't currently possible. The only VisualFoxPro / DBF schema information we have is their actual database files (I think it's mostly stored in the DBC files). There are 116 tables and more than 3000 columns in the original FERC 1 DBF databases, so actually specifying all that structure would be a lot of work, and the database doesn't seem to enforce types or foreign key relationships, and we have no descriptions (other than the `f1_row_lit_tbl` entries) of what the various columns mean.

However, given a programmatically generated SQL Alchemy schema it seems like it should be possible to transform that structural information into other forms. We were going to have to do some kind of generalization / extension of that kind to get the FERC Form 2 (and any other FERC DBF data) loaded into SQLite anyway.  It would be nice to be able to publish schemas (even if they're mostly machine generated) for the FERC SQLite DBs that we create, alongside the ones that are being created for the XBRL data and the PUDL DB.

**Comment by bendnorman** [comment]
Got it. This doesn't seem super feasible or useful right now so I'm going to close this issue.
