### ISSUE TITLE
Create a general row-to-column table transformer

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#2012]
A long time ago in a galaxy far, far away we built some infrastructure for reshaping FERC 1 tables where each row contains a different kind of data, but it wasn't able to deal with the changes in row-number meaning across years. The only table we applied this to was `plant_in_service_ferc1`, but there are many valuable tables with this structure, and we need to be able to extract them easily, and as programmatically as possible. For historical context see e.g. #465, #473, #474, #485.

## Issues to Address
* Account for the fact that the meaning of row numbers changes over years in the DBF data, probably by programmatically renaming things using some normalized version of the row literals found in the original [`f1_row_lit_tbl`](https://data.catalyst.coop/ferc1/f1_row_lit_tbl) table.
* Make it easy to do hierarchical aggregation of the reported accounts by group, sub-group, and FERC account. E.g. "all generation plant"' or "all hydro generation plant" or just "hydro turbines" (which would have an individual account number). See #485
* Identify section header, subtotal, and total rows. Ideally we would store information about which rows are combined to produce the subtotals / totals, and reproduce them proceduraly (e.g. in a database view) rather than storing the derived values. But we could check our calculations against the original values before removing them. There appear to have been a few cases in which respondents used an old version of the form in the year after a change in the meaning of row numbers, which sometimes results in e.g. data appearing in header rows (which should be blank). It may be possible (but not necessarily worthwhile) to identify those filings and programmatically clean them up based on the "correct" form structure.
* In the accounting tables some values are positive, others are negative, and often this is indicated with (accounting notation), which you would only know if you read the label for the row. Somehow this information needs to be retained and associated with the right row/column so we can use it in cleaning up the data (after re-shaping).
* The new FERC 1 XBRL format has more structure and potentially valuable metadata than the old DBF tables. The column names are more descriptive, but don't contain the FERC account numbers. However the taxonomies contain column-level metadata including the associated FERC account number and the name of that FERC account, which we may be able to extract and store in the `datapackage.json` produced alongside the SQLite DB for later programmatic use. Where we would extract and how we would structure this metadata is a question for @zschira.
* What is the "correct" structure for these tables? What kind of naming convention should we use? Is the XBRL table structure & naming appropriate? If possible, it would be good to go with one of the existing structures & sets of names rather than converting everything to a 3rd structure. Or if a 3rd structure is necessary, then at least reconcile the two existing structures first before moving on to further transformations.

## Out of Scope
* The transforms that come out of this process shouldn't change the contents of the data, just its shape & structure. Cleaning the data once it's been re-shaped is a separate problem.

# Issues
There's enough diversity between the various tables that require reshaping that we need to work through several of them before we'll be able to parametrize & generalize the process. We've selected 3-4 high-priority tables with varying structures to do first, and will then attempt to generalize the process given what we've learned. Notes on exploration of these tables are available in the table-specific issues:

* [x] #2021 
* [x] #1807
* [x] #1819
* [x] #1806
* [ ] #1808 
* [x] #2014 
* [ ] #2015
* [ ] #2016

# Design Thoughts
* @cmgosnell and I discussed what we want the ultimate outputs of these transformations to look like, and decided that the wide format we were previously using, and that the XBRL is published in is probably not ideal. The *kind* of value being reported in at least the tables explored above are all generally the same -- e.g. capital contributed to a particular accounting category, quantity of electricity transacted, or O&M expenses. What's different is the categorization and potential grouping of the values, which argues for something like a hierarchical multi-index.
* The categories and groupings aren't bespoke to every table. The FERC Account numbers and their groupings show up repeatedly. Ideally we would store this grouping information in one place and refer to it from elsewhere for aggregation purposes. In the home data table we could store the FERC Account number or a similar ID that identifies the most granular level of reporting, and also have an association table that stores the various kinds of groups that those IDs are associated with separately. Probably each family of nested or otherwise related groupings would have its own association table. The FERC Account ID (or whatever the most granular ID/category was) would probably be the primary key, with each additional column indicating which of several other / higher level categories of records that ID belongs to.
* Even if we don't ultimately want to use the wide XBRL table format, the fact that there's a pretty clean mapping from the DBF to the XBRL structure, and the fact that the XBRL structure provides unique, readable, highly structured column names argues for using that format to get all the data to where it can be concatenated. After that point we can reshape all of the data together.
* Given that the row literals from `f1_row_lit_tbl` aren't unique within a given year and table, we can't depend on them to define the mapping from DBF rows to XBRL columns. What we really need to map is `(sched_table_name, report_year, row_number)` to the unique wide-form XBRL column name. A normalized `row_literal` would be helpful for catching errors / legibility but will often fail programmatically, so we can't rely on that to have a 1 to 1 mapping to the long column names. This is inconvenient since using just the table name, year, and row number... we would have to map every combination manually, and for big tables like `plant_in_service_ferc1` that would mean thousands of rows of semi-manual mapping.
* Really we only need one mapping for each year in which a change has happened, and from that we can reconstruct the corresponding `report_year` based mapping. Unfortunately it turns out that the `row_chg_yr` column only indicates when a particular row literal changed, and doesn't provide any information about when the association between a `row_literal` and a given `row_number` changed (because of rows getting added or deleted before it), so we either need to make some assumptions about which row numbers are affected by changes higher up in the form, or we have to rely on the value of the `row_literal` column to find unique rows to map.
* So I think the manual mapping file we need to construct is actually `(sched_table_name, report_year, row_number, row_literal)` to `(xbrl_table_name, xbrl_column_name)`
* We don't need to store the `xbrl_table_name` if we don't want to because it can be looked up based on the DBF table name. The Plant in Service table has around 100 rows in the DBF data. Probably less than 2x that many if you count all the changes over the years, which seems a little tedious but tractable.
* Another wrinkle here is that one DBF row can map to several XBRL columns, when there are several different values being reported on the basis of that single row. E.g. in the DBF version of the plant in service table there are starting/ending balances, additions, retirements, transfers and adjustments. For a given row, each of those columns maps to a different XBRL column. So we'll either map a combination of DBF row+column to an XBRL column, or need to figure out a programmatic way to specify that multiplicity that can apply to all the mappings for a given table.
* Having worked through the Electric Plant in Service table, it's now clear that reshaping will potentially have to happen in multiple places, so this won't be a single transformer. There's the alignment of DBF + XBRL rows/columns, the stacking of XBRL wide-form data, and potentially separate pre-processing that's required for the XBRL instant and duration tables so that they can be concatenated appropriately.  So probably this Epic will result in 2-4 new reshaping transformers and/or parameterizations.

# Questions for RMI
* How are you using the information in `f1_row_lit_tbl` to align rows/cols across multiple years? Are there any unexpected / strange behaviors that you've found in there that we should know about?
* What kinds of row/column groupings exist besides simple FERC Account numbers? Both alongside the FERC Accounts, and in other kinds of tables. E.g. the cases in which more than one row/column represents the same FERC Account, but one is credits and the other is debits, or non-financial categories like we see in the energy source & disposition table.
* What other kinds of multi-column reporting do we see in the DBF data, and what kind of structures do we need to define to encapsulate it? (analogous to the additions, retirements, transfers, adjustments that we see in the plant in service table)

**Comment by jrea-rmi** [comment]
@zaneselvans I would suggest including one of the tables that need to be melted such as f1_utltyplnt_smmry which has more complicated sub-categories or f1_dacs_epda as a simple case. 

I don't think you need to include f1_elc_op_mnt_expn because it's basically the same as f1_plant_in_srvce.

To further consider which tables to explore, here are the groups of tables with similar transformations that I've made for DBF tables. 

Tables that I think should keep the same value columns, but require better id columns:
- f1_comp_balance_db
- f1_plant_in_srvce
- f1_bal_sheet_cr
- f1_retained_erng
- f1_income_stmnt_2
- f1_elctrc_oper_rev
- f1_elc_op_mnt_expn

Tables that need to be melted (multiple columns become a single id column) before better id columns are added:
- f1_utltyplnt_smmry
- f1_income_stmnt
- f1_dacs_epda

Tables that need to be split into multiple tables, then transformed either of the above ways:
- f1_elctrc_erg_acct
- f1_accumdepr_prvsn

**Comment by jrea-rmi** [comment]
Since f1_plnt_in_srvce is detail of f1_utltyplnt_smmry which is detail of f1_comp_balance_db. To be able to connect them, it's important to make sure that the levels of detail provided for each row of f1_plnt_in_srvce correspond to a level of detail of f1_comp_balance_db.

**Comment by cmgosnell** [comment]
we've been using this for many tables so its done for now!
