### ISSUE TITLE
add newly allocated `fuel_consumed_mmbtu` into `pudl.analysis.mcoe` module

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/pudl#2033]
With @grgmiller 's new addition to the allocation module via #1608  (being merged into dev with some additional validation test checks via #1096 ), we will now have both net generation and fuel allocated at the generator level. The generation is a little more naturally integrated into the `mcoe` outputs because we can easily replace the original 923 table accessed by `pudl_out.gen_eia923()`. There is not 923 table that is fuel at the generator level, so we don't have the same straightforward way to integrate the fuel at the generator-level. But we should find a way to integrate it!

Note: without doing this, the `test_no_null_rows_mcoe` mcoe validation test failed at its previous threshold of 80%. I've set this test to xfail for now. So a part of this issue will need to make this validation test pass.

**Comment by zaneselvans** [comment]
@katie-lamb I think maybe you already addressed this issue some time ago and we can close it and remove the `xfail` that's now generating this message in the data validations?

```
XPASS (The net generation allocation is now integrated into MCOE. The allocated fuel still needs to be integrated - without it we'll have nulls. See #2033)
```

**Comment by katie-lamb** [comment]
@zaneselvans yes I believe so!
