### ISSUE TITLE
update eia860m w/ september 2022

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/pudl#2045]
- [ ] scrap/make new archive
- [ ] update the datastore's DOI 
- [ ] update any metadata needed
- [ ] run transforms (check for anything fishy)
- [ ] map any unmapped plants
- [ ] 

(do this after `xbrl_integration` is merged into `dev`... otherwise we need funky xlsx mapping mege)

**Comment by zschira** [comment]
Hey I just created a new [archive](https://zenodo.org/record/7320218#.Y3KpRZDMJhE)! The DOI is: `10.5281/zenodo.7320218`.

**Comment by zaneselvans** [comment]
@cmgosnell You finished this didn't you?
