### ISSUE TITLE
track down & squash all ferc1 transform warnings

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/pudl#2056]
We've been cruising adding new ferc1 table transformers (old dbf +xbrl) and we've apparently been a liiiittle sloppy about making sure we squash warnings along the way. The scope of this issue is to identify all warnings and squash or silence them (when appropriate).

### Warnings
 - [X] 2022-11-11 12:17:40 [ WARNING] catalystcoop.pudl.metadata.classes:1463 Values in fuel_units column are not included in categorical values in field enum constraint and will be converted to nulls.
 - [X] 2022-11-11 12:17:40 [ WARNING] catalystcoop.pudl.transform.classes:236 Expected column opex_per_kwh not found in dataframe during application of convert_units.
 - [x] 2022-11-11 12:17:44 [ WARNING] catalystcoop.pudl.transform.classes:1120 plants_steam_ferc1: Discrepancy between dataframe columns and rename dictionary keys. Unshared values: {'end_date', 'start_date', 'date'}
 - [x] 2022-11-11 14:07:27 [ WARNING] catalystcoop.pudl.metadata.classes:1465 Values in plant_type column are not included in categorical values in field enum constraint and will be converted to nulls (['']).
 - [x] 2022-11-11 14:07:27 [ WARNING] catalystcoop.pudl.metadata.classes:1465 Values in construction_type column are not included in categorical values in field enum constraint and will be converted to nulls (['']).
- [-] 2022-11-11 14:12:25 [ WARNING] catalystcoop.pudl.transform.ferc1:580 fuel_ferc1: Found 1 duplicate record_ids. ['f1_fuel_2000_12_24_3_1'].

**Comment by cmgosnell** [comment]
The one remaining warning from the fuel table is for a very empty record that gets dropped via `drop_invalid_rows`. going to ignore for now.

![image](https://user-images.githubusercontent.com/25487998/201425147-20c4f0f2-e64c-40c9-8fbf-2f89176cf5c3.png)

**Comment by zaneselvans** [comment]
Done!
