### ISSUE TITLE
Inconsistent outputs from processing of `fuel_ferc1` XBRL data 

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#2090]
Trying to get the nightly builds to pass for #1681 / #2077 I discovered that the `fuel_ferc1` outputs were really different locally vs. in the nightly builds. The expected row count validation is failing, but it's not just that there are missing records, it's that the 2021 `fuel_ferc1` records (coming from the XBRL data) are **wildly different** in my local DB and the one produced by the nightly builds, which is unexpected and concerning.

So, how are they different and why? What could possibly be causing the discrepancy?
* Different ordering of a table / indexing based on whether it's MacOS/M1 vs. Linux/Intel? Affecting the merge of the instant-duration tables?
* Could the `pudl_etl` script being used for the nightly ETL be from a different commit than the code being used for `pytest --live-dbs test/validate`?
* 

### Local DB
* 48280 rows

### Nightly Builds
* 48218 rows

## Debugging Notes:
* Tested running the `fuel_ferc1` and `plants_steam_ferc1` ETL locally.
* Found no difference whether I processed both, or just fuel.
* Found no difference whether I used a copy of the `fuel_ferc1` df as input to steam for plant ID assignment or now (but left it a copy just to be safe!)
* Running ETL for all years results in identical dataframes with just fuel, and fuel + steam.
* Running ETL for just 2021 results in identical dataframes with just fuel, and fuel + steam.
* Verified that each and every year of records read from `fuel_ferc1` is identical between the nightly build output and my local database, with the exception of the 2021 data.
* I've verified that my local extract & transform of just the fuel table results in exactly the same output as pulling from my local DB.
* Now I need to somehow induce the local ETL to give me the same outputs as the nightly build...
* Looking at PSCo data because it's familiar, I am seeing that there's no overlap between the index columns. They appear to be disjoint sets. So e.g. in my local ETL outputs, I get e.g. Craig records for coal and oil, but not for gas. While in the nightly build outputs there's just a gas record.
* Added logging to the `merge_instant_and_duration_tables_xbrl()` method and **THERE IS NO INSTANT TABLE** for `fuel_ferc1` so it can't be the merge. It's just giving us back the instant table as is.

**Comment by bendnorman** [comment]
- The HEAD commit SHA in the docker image is the same as the [most recent commit on dev](https://github.com/catalyst-cooperative/pudl/commit/08d1d89f5d7b66ec55a4e6fc6b63f68ab634c351).
- Is the raw xbrl data different or the cleaned data?

**Comment by zaneselvans** [comment]
@bendnorman I'm using the following to regenerate the fully transformed `fuel_ferc1` table, and grabbing only the 2021 outputs, having verified that all of the other years are exactly identical.

I pulled down the DB generated by the nightly builds, and am selecting only the 2021 records from the fuel table for comparison.

```py
ferc1_settings = Ferc1Settings(
    # Do one year of each, type of data, or all the years:
    years=[2020, 2021],
    #years=Ferc1Settings().years,
    tables=[
        "fuel_ferc1",
        #"plants_steam_ferc1",
        #"plants_hydro_ferc1",
        #"plant_in_service_ferc1",
        #"plants_pumped_storage_ferc1",
        #"purchased_power_ferc1",
        #"plants_small_ferc1",
    ],
)


def test_etl(ferc1_settings):
    pudl_settings = pudl.workspace.setup.get_defaults()
    ferc1_dbf_raw_dfs = pudl.extract.ferc1.extract_dbf(
        ferc1_settings=ferc1_settings, pudl_settings=pudl_settings
    )
    ferc1_xbrl_raw_dfs = pudl.extract.ferc1.extract_xbrl(
        ferc1_settings=ferc1_settings, pudl_settings=pudl_settings
    )
    xbrl_metadata_json = pudl.extract.ferc1.extract_xbrl_metadata(pudl_settings)
    dfs = pudl.transform.ferc1.transform(
        ferc1_dbf_raw_dfs=ferc1_dbf_raw_dfs,
        ferc1_xbrl_raw_dfs=ferc1_xbrl_raw_dfs,
        xbrl_metadata_json=xbrl_metadata_json,
        ferc1_settings=ferc1_settings,
    )
    return dfs

dfs = test_etl(ferc1_settings)
fuel_tfr = dfs["fuel_ferc1"].query("report_year == 2021")
```

**Comment by zaneselvans** [comment]
@zschira I think this may be something we need your help on...

For some reason my local FERC1 XBRL to SQLite conversion is getting one set of fuel table records, while the (same?) conversion running in the nightly builds is getting *an entirely different* set of records. I'm going to re-run the extraction now on my local dev branch and see if the situation persists.

**Comment by bendnorman** [comment]
Is the XBRL to SQLite conversion idempotent, given the RSS feeds are always changing?

**Comment by zaneselvans** [comment]
IIRC, we're always pulling the most recent filing, and only using that one, assuming that it is complete and supercedes prior filings by the same entity in the same time period.

In this case, both the old and new conversions are resulting in records with exactly the same `filing_name` which is a UUID, so I think they're pulling from exactly the same raw data, but getting different outputs for some reason.  And in any case, they're pointing at the same static archive, and the same statically archived Taxonomy.

**Comment by zaneselvans** [comment]
So it seems to me like *neither* my local nor the nightly builds are getting the right outputs.  If the records that are showing up in the two different outputs are all valid, then they should *all* be showing up!

**Comment by zaneselvans** [comment]
This is the query I'm doing from within `sqlite3` to pull PSCo's fuel records:

```sql
SELECT
    entity_id,
    filing_name,
    start_date,
    end_date,
    plant_name_axis,
    fuel_kind_axis
FROM steam_electric_generating_plant_statistics_large_plants_fuel_statistics_402_duration
WHERE entity_id = "C000822";
```

On my freshly converted `ferc1_xbrl.sqlite` DB I get:

```txt
entity_id  filing_name                           start_date  end_date    plant_name_axis  fuel_kind_axis
---------  ------------------------------------  ----------  ----------  ---------------  --------------
C000822    31acf15f-11b1-4534-adb0-abf5a1c754af  2021-01-01  2021-12-31  Cherokee 4       Oil
C000822    31acf15f-11b1-4534-adb0-abf5a1c754af  2021-01-01  2021-12-31  Hayden           Oil
C000822    31acf15f-11b1-4534-adb0-abf5a1c754af  2021-01-01  2021-12-31  Fort Lupton      Oil
C000822    31acf15f-11b1-4534-adb0-abf5a1c754af  2021-01-01  2021-12-31  Craig            Coal
C000822    31acf15f-11b1-4534-adb0-abf5a1c754af  2021-01-01  2021-12-31  Craig            Oil
Run Time: real 0.001 user 0.000218 sys 0.000171
```

On the `ferc1_xbrl.sqlite` that was generated by the nightly builds I get:

```txt
entity_id  filing_name                           start_date  end_date    plant_name_axis     fuel_kind_axis
---------  ------------------------------------  ----------  ----------  ------------------  --------------
C000822    31acf15f-11b1-4534-adb0-abf5a1c754af  2021-01-01  2021-12-31  Cherokee 4          Coal
C000822    31acf15f-11b1-4534-adb0-abf5a1c754af  2021-01-01  2021-12-31  Cherokee 4          Gas
C000822    31acf15f-11b1-4534-adb0-abf5a1c754af  2021-01-01  2021-12-31  Hayden              Coal
C000822    31acf15f-11b1-4534-adb0-abf5a1c754af  2021-01-01  2021-12-31  Hayden              Gas
C000822    31acf15f-11b1-4534-adb0-abf5a1c754af  2021-01-01  2021-12-31  Pawnee              Coal
C000822    31acf15f-11b1-4534-adb0-abf5a1c754af  2021-01-01  2021-12-31  Pawnee              Gas
C000822    31acf15f-11b1-4534-adb0-abf5a1c754af  2021-01-01  2021-12-31  Fort Lupton         Gas
C000822    31acf15f-11b1-4534-adb0-abf5a1c754af  2021-01-01  2021-12-31  Fruita              Gas
C000822    31acf15f-11b1-4534-adb0-abf5a1c754af  2021-01-01  2021-12-31  Fruita              Oil
C000822    31acf15f-11b1-4534-adb0-abf5a1c754af  2021-01-01  2021-12-31  Blue Spruce         Gas
C000822    31acf15f-11b1-4534-adb0-abf5a1c754af  2021-01-01  2021-12-31  Blue Spruce         Oil
C000822    31acf15f-11b1-4534-adb0-abf5a1c754af  2021-01-01  2021-12-31  Rocky Mountain      Gas
C000822    31acf15f-11b1-4534-adb0-abf5a1c754af  2021-01-01  2021-12-31  Cherokee 5, 6, & 7  Gas
C000822    31acf15f-11b1-4534-adb0-abf5a1c754af  2021-01-01  2021-12-31  Cherokee 5, 6, & 7  Oil
C000822    31acf15f-11b1-4534-adb0-abf5a1c754af  2021-01-01  2021-12-31  Comanche            Coal
C000822    31acf15f-11b1-4534-adb0-abf5a1c754af  2021-01-01  2021-12-31  Comanche            Gas
C000822    31acf15f-11b1-4534-adb0-abf5a1c754af  2021-01-01  2021-12-31  Craig               Gas
C000822    31acf15f-11b1-4534-adb0-abf5a1c754af  2021-01-01  2021-12-31  Valmont 5           Coal
C000822    31acf15f-11b1-4534-adb0-abf5a1c754af  2021-01-01  2021-12-31  Valmont 5           Gas
C000822    31acf15f-11b1-4534-adb0-abf5a1c754af  2021-01-01  2021-12-31  Alamosa             Gas
C000822    31acf15f-11b1-4534-adb0-abf5a1c754af  2021-01-01  2021-12-31  Alamosa             Oil
C000822    31acf15f-11b1-4534-adb0-abf5a1c754af  2021-01-01  2021-12-31  Valmont 6, 7, & 8   Gas
C000822    31acf15f-11b1-4534-adb0-abf5a1c754af  2021-01-01  2021-12-31  Fort St. Vrain 1-4  Gas
C000822    31acf15f-11b1-4534-adb0-abf5a1c754af  2021-01-01  2021-12-31  Fort St. Vrain 5-6  Gas
Run Time: real 0.019 user 0.004493 sys 0.003229
```

You should be able to download the nightly-build derived DB using:
```bash
gsutil cp gs://nightly-build-outputs.catalyst.coop/08d1d89f5d7b66ec55a4e6fc6b63f68ab634c351-dev/sqlite/ferc1_xbrl.sqlite ./ferc1_xbrl-nightly.sqlite
```

**Comment by zaneselvans** [comment]
Definitely gotta get that CI running on the [FERC XBRL Extractor repo](https://github.com/catalyst-cooperative/ferc-xbrl-extractor) and make sure it catches whatever madness is causing this discrepancy!

**Comment by zaneselvans** [comment]
Is this Arelle behaving very differently on different platforms?

**Comment by bendnorman** [comment]
The ferc1_xbrl.sqlite db from my local run and the [nightly build run from 11/21/22 (95caaa5d277c1c6d391744582538561481259ea0)](https://console.cloud.google.com/storage/browser/_details/nightly-build-outputs.catalyst.coop/95caaa5d277c1c6d391744582538561481259ea0-dev/pudl_out/sqlite/ferc1_xbrl.sqlite;tab=live_object) have the same output for the above query: 
```
entity_id  filing_name                           start_date  end_date    plant_name_axis  fuel_kind_axis
---------  ------------------------------------  ----------  ----------  ---------------  --------------
C000822    31acf15f-11b1-4534-adb0-abf5a1c754af  2021-01-01  2021-12-31  Cherokee 4       Oil
C000822    31acf15f-11b1-4534-adb0-abf5a1c754af  2021-01-01  2021-12-31  Hayden           Oil
C000822    31acf15f-11b1-4534-adb0-abf5a1c754af  2021-01-01  2021-12-31  Fort Lupton      Oil
C000822    31acf15f-11b1-4534-adb0-abf5a1c754af  2021-01-01  2021-12-31  Craig            Coal
C000822    31acf15f-11b1-4534-adb0-abf5a1c754af  2021-01-01  2021-12-31  Craig            Oil
Run Time: real 0.001 user 0.000218 sys 0.000171
```

I don't think it's a platform issue given the two most recent nightly builds didn't produce the same ferc1_xbrl.sqlite databases.

**Comment by zaneselvans** [comment]
Okay so we have 2 different commits that produced these two different outputs on the same platform (the nightly builds) and they aren't very different from each other so if it's something in our code causing the difference, it seems like it should be pretty easy to ferret out.

But it seems like the code in question is in the `ferc-xbrl-extractor` and I think we were using v0.4.2 in both of these runs, and that's been out since November 8th. And we haven't updated the Zenodo archives for FERC 1 since November 11th.

**Comment by bendnorman** [comment]
Just to make this even more confusing, I recreated the `ferc1_xbrl.sqlite` database in the VM/docker image from 11/22/22's nightly build (08d1d89f5d7b66ec55a4e6fc6b63f68ab634c351) and got the same output as my local run. 

This means something wonky is happening when the whole nightly build is run. Maybe the GCS cache isn't behaving as expected and these runs are working with different archives? We need to see the DEBUG level logs to understand which GCS archives the datastore is using. #2091 will enable debug level logs again.

**Comment by zschira** [comment]
I believe I've figured out the problem. It looks like it was caused by something I did in the XBRL extractor. Basically, it uses a dictionary with a key that is a tuple of strings to look up which facts belong in each table. These tuples weren't sorted though, and I think sometimes `lxml` was returning things in slightly different orders during parsing, which caused the lookup to fail sometimes. After recreating the DB with a fix to sort the tuples, I ran the query from above and I get all of the records from both sets.

**Comment by zaneselvans** [comment]
@zschira I ran a full ETL and data validation using the the `dev` branch of the `ferc-xbrl-extractor` repo with your fixes and incredibly the only thing that was visibly affected was the row counts in the `fuel_ferc1` and `fbp_ferc1`. There are about 2x as many records from 2021 / the XBRL now as there were before (which is only about a 1.2% increase in the overall number of records).  At least structurally it doesn't seem to have affected any of the other tables that we're transforming.  Really curious why it stood out on the fuel table.

**Comment by zaneselvans** [comment]
This has been fixed via:
* https://github.com/catalyst-cooperative/ferc-xbrl-extractor/pull/35
* https://github.com/catalyst-cooperative/pudl/pull/2092
