### ISSUE TITLE
Migrate settings from constants.py to settings.py

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#210]
There's a small subset of the items defined in `constants.py` that are more like settings, which affect the overall operation of the PUDL package, and which are a bit buried now. Need to identify them and move them over to `settings.py` along with other such system-wide variables.

**Comment by cmgosnell** [comment]
Are there any additional items from constants that we should move into settings or is this finished?

**Comment by cmgosnell** [comment]
Closing bc, obsolete and duplicative with #52.
