### ISSUE TITLE
data.catalyst.coop SSL certificate is expired / site is down?

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#2116]
As of this morning I'm getting a connection error when attempting to access [our Datasette deployment](https://data.catalyst.coop):

![image](https://user-images.githubusercontent.com/596279/206478111-f9850dd9-28a0-4287-b898-9c087eaa9544.png)

The web server itself seems to be up. Pinging it works fine:

```console
$ ping data.catalyst.coop
PING ghs.googlehosted.com (172.217.3.147): 56 data bytes
64 bytes from 172.217.3.147: icmp_seq=0 ttl=58 time=56.360 ms
64 bytes from 172.217.3.147: icmp_seq=1 ttl=58 time=60.982 ms
64 bytes from 172.217.3.147: icmp_seq=2 ttl=58 time=59.218 ms
64 bytes from 172.217.3.147: icmp_seq=3 ttl=58 time=61.228 ms
```

I'm pretty sure that we used the built in GCP certificate system, but trying to list certificates now shows nothing:

```console
$ gcloud compute ssl-certificates list
Listed 0 items.
```

What the heck is going on here?  @bendnorman does this make any sense to you?

**Comment by bendnorman** [comment]
I’ve gotten EOF errors when downloading files before when I’m on my VPN. It sounds like this issue was resolved when you disabled your VPN?

**Comment by zaneselvans** [comment]
Thank goodness it turned out that this was just my local VPN issue.
