### ISSUE TITLE
Calculate MCOE with EIA923 fuel costs and FERC non-fuel costs

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#213]
Once FERC Form 1 and EIA 923 are connected (#212), we can take the generation unit level marginal cost of fuel based on EIA data, and the non-fuel costs from FERC, and use them to estimate total MCOE at the generation unit level.

Combined with the regression analysis identifying the fixed, capacity, and net generation based portions of power plant operating costs as reported to FERC (#204), we can then also estimate future power plant operating costs, as a function of fuel price and projected capacity factor.

**Comment by gschivley** [comment]
I noticed that the `pudl.analysis.mcoe` method doesn't currently include a MCOE column. Is this an oversight or something that will come with the resolution of this issue?

**Comment by zaneselvans** [comment]
It's because we still do not really have MCOE -- we just have the fuel portion from EIA, and MCOE is more than that, and until we get some reasonable number pulled over from FERC (or elsewhere) for the non-fuel marginal costs, it's... a work in progress.

**Comment by gschivley** [comment]
Ok, I suspected as much.

**Comment by zaneselvans** [comment]
A lot of this work is taking place in the RMI / FERC context at this point.
