### ISSUE TITLE
Flag invalid params in `params.py`

### ISSUE THREAD

**Issue by aesharpe** [catalyst-cooperative/pudl#2160]
For XBRL stuff, I'm wondering if there is a way to throw an error if there is an invalid parameter in the params `TRANSFORM_PARAMS` dict and you try and transform that table.

I just merged my branches with dev and saw that the `align_row_numbers_dbf` transform function changed its params from `dbf_table_name`  to `dbf_table_names`, and the function was quietly not running after merging with dev. (I mean, not quietly because it was breaking elsewhere and the logs weren't showing up, but it would be way easier if it failed because of this param discrepancy and not because of something else that I had to then backtrack from).

I figured I could do a comparison of the **allowed params** (defined in the parameter classes) and the **provided params** (written in `params.py`) somewhere, but the provided params get ditched if they aren't in the allowed params.

**EX:** I had `dbf_table_name` defined instead of `dbf_table_names` in `params.py`, and when I asked the `align_row_numbers_dbf` function to print out the params it showed:
`dbf_table_names=None`

I wanted some way to access the provided parameters, to compare them to the allowed parameters, but I couldn't figure out how. I feel like the right place to do this is in AbstractTableTransformer class. Anyone have ideas here? I think it's an important flag to include, and I'm really curious how we might do this.

It's also important to get the table names right, not just the params!

**Comment by zaneselvans** [comment]
I suspect that we can get Pydantic to do the work of identifying unexpected parameters and giving us errors, using [Model Config options](https://docs.pydantic.dev/usage/model_config) as we have in the `TableTransformParams` classes already:

```py
class Config:
    extra = "forbid"
```

**Comment by aesharpe** [comment]
Found a small inconsistency already -- should we use `xbrl_duration` or `duration_xbrl` when referring to these different sub-xbrl tables?

**Comment by zaneselvans** [comment]
We have a convention that in the `Ferc1TableTransformer` context any method that ends with `_xbrl` only applies to XBRL data, and similarly anything that ends with `_dbf` applies only to DBF data, and to preserve that pattern we went with `_instant_xbrl` and `_duration_xbrl` as suffixes for the methods that are specific to the instant/duration data.  The functions and methods and parameters should all be named the same way, so I think that convention should be applied to all of them.

**Comment by aesharpe** [comment]
Ok great, that's what I thought. There are a bunch of cases where we define `raw_xbrl_duration` etc. that I'll switch over.

**Comment by zaneselvans** [comment]
I think you may run into other naming conventions in other systems if you chase that consistency too far, you might want to see where it leads before trying to change everything to match.

**Comment by aesharpe** [comment]
Seems like it only comes up in the `ferc1` transform module and the `ferc1_eia` glue module. Can't find anything that looks too disastrous.

**Comment by zaneselvans** [comment]
This is done I think, with #2177
