### ISSUE TITLE
Can't request review from @inframundo team

### ISSUE THREAD

**Issue by jdangerx** [catalyst-cooperative/pudl#2189]
@zaneselvans thanks for adding an @inframundo team in the github org! I can’t assign review to it, which is surprising, because I can do that with other teams on GH. The [docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) say
> Organization members with write access can also assign a pull request review to any person or team with read access to a repository.

Is it possible that @inframundo doesn’t have read access to `pudl`? The way I’ve seen the GH structure in the past has been: 
```
root org 
     |---> “engineering” (which has access to core repos)
             |---> sub-team 1 (which has access to team-specific repos)
             |---> sub-team 2 (...)
```

**Comment by zaneselvans** [comment]
Yeah I thought this was strange too. I couldn't request a PR from the group either. I didn't realize there were group permissions though, and didn't assign anything to the team so that's probably it.

**Comment by zaneselvans** [comment]
I've added several repos to the @catalyst-cooperative/inframundo team, and given it write-access to them. Does the PR request work now?

**Comment by jdangerx** [comment]
Sure does, mystery solved 🕵️
