### ISSUE TITLE
Decide how to handle dagster logging

### ISSUE THREAD

**Issue by bendnorman** [catalyst-cooperative/pudl#2223]
By default, dagster released logs appear in the UI and the digit process in the CLI but python logs only appear in the CLI. [Dagster allows you to capture python logs](https://docs.dagster.io/concepts/logging/python-logging). There are a couple of downsides to this option. 1) It's an experimental feature and 2) they [warn against retaining too many logs](https://docs.dagster.io/concepts/logging/python-logging):

> Please note that you should generally be fairly selective about which logs you wish to capture, especially in a production context. It is possible to overload the event log storage with these events, which may cause certain pages in Dagit to take a long time to load. Consider only capturing the most critical logs, and avoid including debug information if you expect to maintain a large amount of run history.

I haven't tested out the performance of the UI when retaining all of our existing python logs.

Another option is to use [dagster loggers](https://docs.dagster.io/concepts/logging/loggers). I haven't researched these enough to understand the benefits.

**Comment by jdangerx** [comment]
I think we had decided that we will not worry about this:
* the nightly build will run in console and thus all logs will be visible
* in development, logs will be visible in the console as well
* if we were to run a persistent Dagit UI, we would want to pull in the logs somewhere, but that seems like a bridge to cross once we get to it.
@bendnorman @zschira if you agree, we can just close this issue.

**Comment by bendnorman** [comment]
I think the current log handling is fine as is. We can reopen this issue if we want to change the logging behavior.
