### ISSUE TITLE
`allocate_net_gen` dropping data when energy source codes don't match between `gens` and `gf`

### ISSUE THREAD

**Issue by grgmiller** [catalyst-cooperative/pudl#2226]
As noted in https://github.com/singularity-energy/open-grid-emissions/issues/271, it looks like the `pudl.analysis.allocate_net_gen` module is dropping data in certain cases when an energy source code reported for a plant in the EIA-923 `gf` table does not appear in the EIA-860 `gens` table.

One specific example is `plant_id_eia` 8023 in the year 2019. In EIA-923, most of the generation and fuel consumption for this plant is reported associated with the `RC` energy source code. However, in the EIA-860 generator table, `RC` is not listed as any of the numbered energy source codes or startup fuel codes associated with this plant. Thus, all of the data for RC fuel consumption is getting dropped, leaving only data for DFO fuel consumption, which is a startup fuel for this plant.

I have not yet traced exactly which step the RC data is getting dropped, but it seems like we may want to adjust the code to be more resilient to this type of issue. It seems like one relatively simple fix could be to check that all energy source codes reported in the gf table for each plant-pm appear in the gens table. However, we may want to check how widespread this issue may be - it may be more appropriate to make a manual fix to the input EIA-860 data for a single plant than to try and write a general rule for fixing an issue that only applies to a single plant.

**Comment by cmgosnell** [comment]
Hey @grgmiller ! thanks for bringing this up! I **thought** that `_allocate_unassociated_records` dealt with this. But as you are very intimately aware, this process is layered and we could certainly be getting something wrong. We could use this plant as an example to pull it through the process to check what is happening to it. Or/and we could make it a test case!

**Comment by grgmiller** [comment]
So after tracing this though the `allocate_net_gen` code, it looks like this data is getting dropped in the `associate_generator_tables` function, when we use `_allocate_unassociated_records` to allocate unassociated `prime_mover_code` when creating the `gen_assoc` df. Prior to pipeing `_allocate_unassociated_records`, the `RC` data still exists. 

I wanted to see how widespread this issue is, and in 2019, I found that there are 49 individual plants where non-zero fuel consumption data in the gf table is associated with an energy source code that does not exist for that plant in the gens table. This is resulting in up to ~52,000,000 MWh and 528,000,000 mmbtu of fuel (primary coal and petroleum) being dropped from the pipeline in 2019.

I need to think about how best to fix this - we may be able to modify `_allocate_unassociated_records` but it may also be necessary to update the energy source codes in `gens` somewhere further up the pipeline. 

At the very least, I think we could implement a simple validation test to make sure that this does not happen again. In theory, since we are treating the `gf` data as the ground truth, the total generation and total fuel consumption for all plants that is outputted by `allocate_gen_fuel_by_generator_energy_source` should match the total generation and total fuel consumption for all plants in the raw `gf` table. If it doesn't, we know that data is getting dropped somewhere.

**Comment by jdangerx** [comment]
For internal planning:

Scope:
* [ ] we have passing tests for the cases where (energy source code|prime mover code) are missing from `gens` but present in `gf`, where the missing codes are added to `gens` and the corresponding generation/fuel usage is spread evenly across appropriate

Next steps:
* [ ] add variations of the existing "all generation/consumption is accounted for" tests which use data that is missing energy source / prime mover. There are some examples in `allocate_net_gen_test.py` that are commented out right now.
* [ ] write tests to make sure the allocation is correct vs. just the sums.
