### ISSUE TITLE
Replace credentials_json with WIF

### ISSUE THREAD

**Issue by jdangerx** [catalyst-cooperative/pudl#2271]
There are the following service account secrets that we need to change:

* `pudl-usage-metrics.GCP_SA_KEY` (`tox-pytest.yml`, `load-metrics.yml`) (tox-pytest-github-action@catalyst-cooperative-pudl.iam.gserviceaccount.com?)
* `pudl.DEPLOY_PUDL_SA_KEY` (`build-deploy-pudl.yml`) (deploy-pudl-github-action@catalyst-cooperative-pudl.iam.gserviceaccount.com)
* `pudl.ZENODO_CACHE_MANAGER_SA_KEY` (`zenodo-cache-sync.yml`) (zenodo-cache-manager@catalyst-cooperative-pudl.iam.gserviceaccount.com ? )
* `pudl-catalog.GOOGLE_CREDENTIALS` (`tox-pytest.yml`) (tox-pytest-github-action@catalyst-cooperative-pudl.iam.gserviceaccount.com?)
* `gce-build-test.GCE_SA_KEY` (`gce.yml`) (gce-github-action-test@catalyst-cooperative-pudl.iam.gserviceaccount.com?)

For each of these, we need to:
* figure out which service account they actually apply to
* add the service account mapping to the "gh-oidc" module

I think we can just throw all the mappings into one module, and add some repository-level attribute restrictions - the [docs](https://github.com/terraform-google-modules/terraform-google-github-actions-runners/tree/master/modules/gh-oidc) have this example code:

```terraform
module "gh_oidc" {
  source      = "terraform-google-modules/github-actions-runners/google//modules/gh-oidc"
  project_id  = var.project_id
  pool_id     = "example-pool"
  provider_id = "example-gh-provider"
  sa_mapping = {
    "foo-service-account" = {
      sa_name   = "projects/my-project/serviceAccounts/foo-service-account@my-project.iam.gserviceaccount.com"
      attribute = "attribute.repository/${USER/ORG}/<repo>"
    }
  }
}
```
And I think we can just add more things to `sa_mapping`.

**Comment by jdangerx** [comment]
@zaneselvans @bendnorman @zschira can one of you confirm that the above service account mappings are correct?

**Comment by bendnorman** [comment]
These mappings look correct to me!

**Comment by jdangerx** [comment]
Closing this issue since I'd rather track all this work in pudl-usage-metrics#90.
