### ISSUE TITLE
Convert FERC1 -> EIA 860/923 glue table test to Dagster

### ISSUE THREAD

**Issue by zschira** [catalyst-cooperative/pudl#2303]
### Background

The [annual plant and utility id mapping process](https://catalystcoop-pudl.readthedocs.io/en/latest/dev/pudl_id_mapping.html#checking-for-unmapped-records) uses a mini-ETL run from `test/integration/glue_test.py` as described in #2293. It seems this requires a PUDL engine, and raw FERC XBRL/DBF engines, which can all be produced via dagster. Currently, however, it is still using the old XBRL/DBF extract functions, and should likely be using dagster assets.

### Approach

- [ ] Convert `src/pudl/glue/ferc1_eia.py` to use dagster assets where applicable
- [ ] Create job for the `get_missing_ids` pipeline
- [ ] Verify that tests are passing on new configuration
- [ ] Verify that `tox -e get_unmapped_ids` works

**Comment by jdangerx** [comment]
This approach sounds good to me , @zschira do you think this can be worked on independently of the other integration test work you're doing?

**Comment by jdangerx** [comment]
(And should we change this issue to "Convert FERC1 -> EIA 860/923 glue tables to Dagster"?)

**Comment by zschira** [comment]
> do you think this can be worked on independently of the other integration test work you're doing?

I think so. `glue_test.py` is using some fixtures that I've updated, but I think you could start converting `src/pudl/glue/ferc1_eia.py` to use assets and create a job. Then, hopefully my work will be in the `dagster-asset-etl` branch by the time you need those fixtures, so you'd be able to merge and get the tests working.

**Comment by bendnorman** [comment]
## Some ideas
* `get_util_ids_ferc1_raw_xbrl`
	* pulls in `identification_001_duration` table and does some pandas manipulation.
	* We could convert this to an asset that pulls in the id table using the FercXBRLSQLiteIOManager. However, the FercXBRLSQLiteIOManager currently merges the requested table with the id table. We’d have to add some bespoke logic for loading just the id table.
	* Could also keep the code as is and feed it the `ferc1_engine_xbrl` fixture.
* `get_util_ids_ferc1_raw_dbf`
	* Create a source asset for `f1_respondent_id` then create an asset that depends on `f1_respondent_id` to do some pandas manipulation.
	* 	Could also keep the code as is and feed it the `ferc1_engine_xbrl` fixture.
* `get_plants_ferc1_raw`
	* Convert to a collection of assets?
	* Where would these glue assets live? In a separate definition or in pudl.etl definitions? We don’t want to run this during the regular ETL though so I think we should create a separate definition. 
	* We could also do a semi janky solution of creating an extract function that materializes the raw the source assets and returns a dictionary of data frames. We have to pass the dataset_settings config.

**Comment by bendnorman** [comment]
I think the best option is to just convert the `get_plants_ferc1_raw` function to a collection of assets. Each table in the `plant_tables` list will have a transform asset that reads in the raw tables from the `SourceAsset`s created by `pudl.extract.ferc1.create_raw_ferc1_assets()`. We'll then need another asset that concats all of the transformed tables together and does the last bit of pandas operations. The `glue_test_dfs` will have to construct and execute a `get_plants_ferc1_raw` job using the assets and required resources.

The easiest option is to just keep the `extract_dbf` and `extract_xbrl` around and handle this in a future PR.

**Comment by jdangerx** [comment]
> The easiest option is to just keep the extract_dbf and extract_xbrl around and handle this in a future PR.

I agree that we should keep our eyes on the prize of "integration tests pass and we can start trying to merge `dev` into `dagster-asset-etl`

> I think the best option is to just convert the get_plants_ferc1_raw function to a collection of assets.

Agreed - tt'd be nice to convert all this "output glue mismatches" code into dagster one day, but that day doesn't have to be today.
