### ISSUE TITLE
`tox-pytest` workflow generates a mostly empty cache

### ISSUE THREAD

**Issue by jdangerx** [catalyst-cooperative/pudl#2315]
Brought up in [this comment](https://github.com/catalyst-cooperative/pudl/pull/2311#issuecomment-1432221015).

This is not high priority until we start tackling our test times.

Scope:
* [x] the Zenodo cache generated by a tox-pytest run contains the actual data instead of just the `datapackage.json`s

Next steps:
* [x] Find a short subset of tests to run that downloads actual data to the local cache, without `--gcs-cache` set
* [x] Verify that setting `--gcs-cache` will not download actual data and just download the `datapackage.json`

**Comment by zaneselvans** [comment]
The long CI times are definitely annoying, but I think we might be more concerned with the resulting data egress fees -- if GitHub is downloading ~1GB of data from GCS every time we run CI how much does that cost? I guess 1GB is only about $0.12, but we do run CI dozens of times a day sometimes.

**Comment by jdangerx** [comment]
Now that #2329 is merged we see a real cache in `main` and also it gets used in other branches!

<img width="1087" alt="image" src="https://user-images.githubusercontent.com/2495794/221038475-c2b77959-8720-4df9-adf3-09ca450f5093.png">

**Comment by jdangerx** [comment]
If we keep merging `dev` into main more frequently, the `main` cache should stay fresh too.
