### ISSUE TITLE
Scope FERC Forms 2 and 6 DBF extraction

### ISSUE THREAD

**Issue by zschira** [catalyst-cooperative/pudl#2335]
### Background

Currently all FERC XBRL based data is being extracted and raw DB's are published via datasette. Recently, we've received multiple requests to provide earlier years of data for froms 2 and 6, which are contained in DBF data. We have a DBF extractor, but it is specific to form 1.

### Scope

Estimate work required to start extracting earlier years of data.

- [ ] What will it entail to generalize DBF extractor
- [ ] Are there schema changes over the years that will cause incompatibilities -
    - [ ] Form 2
    - [ ] Form 6

**Comment by zaneselvans** [comment]
@rousik has essentially done this in the course of #1984 and is continuing on down the path of extracting FERC 2 and 6.
