### ISSUE TITLE
Outputs failing w/o FERC bc of datetime issues

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/pudl#236]
Not exactly sure what is happening here, but when you have a db initialized with only EIA, the outputs for EIA break. I was attempting to look at the MCOE output using the PudlTabl object, but the same issue was cropping up when using most of the PudlTabl functions.

Each PudlTabl function that involves EIA only tables but requires either the puld.helpers.merge_on_date_year() or any other report_date merge was giving me errors like `AssertionError: Zero dates found!` or `ValueError: You are trying to merge on datetime64[ns] and float64 columns. If you wish to proceed you should use pd.concat`.

All of this stopped when I re-initalized including even just one FERC year, although I'm not sure why,

**Comment by zaneselvans** [comment]
With all the changes we've made to how datetime aggregation/merges happen in the PUDL outputs, I think this is no longer an issue.
