### ISSUE TITLE
Dagster nightly build output paths differ from those in `dev`

### ISSUE THREAD

**Issue by jdangerx** [catalyst-cooperative/pudl#2368]
The dagster nightly builds are outputting to a slightly different path in the bucket than the dev nightly builds are. @zaneselvans  you mentioned that we link to these paths somewhere, where is that? It’s easy enough to change the paths, I just need to know the spec.

We have `/pudl_out/sqlite/*.sqlite`, `/pudl_out/parquet/**.parquet`, `/parquet/**.parquet`, `/sqlite/*.sqlite` in the [dev nightly build output](https://console.cloud.google.com/storage/browser/nightly-build-outputs.catalyst.coop/149860f987ec5015759d8231e9434e0a5a704ad9-dev?project=catalyst-cooperative-pudl&pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false). Is that expected / do we need to have this data duplicated?

In the [dagster output](https://console.cloud.google.com/storage/browser/nightly-build-outputs.catalyst.coop/b1e2d9de61fc4972c86759c35f10da68ec049052-dagster-nightly-builds;tab=objects?project=catalyst-cooperative-pudl&prefix=&forceOnObjectsSortingFiltering=false) we just have `/*.sqlite`, `/*.parquet`/.

This probably blocks the `dagster` -> `dev` merge, so marking this as `high` priority.

```[tasklist]
### Scope
- [ ] output directory structure matches spec
- [ ] decide if duplicate data is necessary
```
```[tasklist]
### Next steps
- [ ] spin up docker environment, but pull the contents of the dagster-nightly-builds to `PUDL_OUT` to skip all the long ETL stuff
- [ ] get the GCP commands right
```

**Comment by zaneselvans** [comment]
On `dev` the nightly builds output the old directory structure, with files organized into `sqlite`, `parquet` etc. When those outputs are copied to GCS and AWS, the directory structure is flattened, and everything goes into one directory (except for the partitioned CEMS parquet files, which get their own directory).

Going forward with Dagster and the environment variables that specify where inputs come from and outputs go to, I think we want to use the flat output structure which is currently what we have in on GCS / AWS and what I understood to be how Dagster was set up to do the outputs.

I think @zschira updated the test fixtures to output things in the right places in the tests.

The old output paths are constructed in `pudl.workspace.setup.derive_paths()` I think.

**Comment by zaneselvans** [comment]
Maybe the difference here is that before we would output everything to local disk (using the old filetype based directory structure) and then only after the entire ETL had completed, move them to the public buckets, where they have a flat directory structure?

Or are you talking about the private (and sometimes broken) nightly build outputs that end up in a bucket before getting copied over to the public buckets?

**Comment by jdangerx** [comment]
Ahh you got it. The difference is in the `nightly-build-output.catalyst.coop` GCS bucket - the `intake.catalyst.coop` on GCS and S3 all have the right formats. Makes sense, closing!
