### ISSUE TITLE
Rename electric_opex_ferc1 to electric_operating_expenses_ferc1

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#2370]
In the PUDL DB two of the new tables we've integrated from FERC 1 are currently named:
* `electric_operating_revenues_ferc1` and
* `electric_opex_ferc1`

These tables are analogous to each other (one just records revenues and the other expenses, within the same financial category) and should be named using a similar pattern, so I suggest we change `electric_opex_ferc1` to `electric_operating_expenses_ferc1` as there's no well-known shorthand for "operating revenues" like there is for expenses.

**Comment by aesharpe** [comment]
That makes sense to me. I wonder if there are any other cases where we might want to enumerate opex into operating expenses. 

For now, I think this makes sense as an isolated update.
