### ISSUE TITLE
Update PUDL to new major versions of key dependencies

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#2384]
Several of our key dependencies have released or are about to release major versions that probably include breaking changes. The dust probably won't settle between them until 2023Q2, so we can wait until then to update PUDL.

```[tasklist]
- [ ] #2383
- [ ] #2394
- [ ] #2395
- [ ] https://github.com/catalyst-cooperative/pudl/issues/2842
- [ ] #2854
```

**Comment by bendnorman** [comment]
Can we close this issue?

**Comment by zaneselvans** [comment]
Yes, we're on to other dependencies now :)
