### ISSUE TITLE
pudl.output.eia860.generators_eia860() fails

### ISSUE THREAD

**Issue by karldw** [catalyst-cooperative/pudl#243]
**Describe the bug**

The `generators_eia860` output function fails [here](https://github.com/catalyst-cooperative/pudl/blob/c4a3a1df04a43a9c784ede17fa11d7c44c417dca/pudl/output/eia860.py#L258) because of the column data types.

**To Reproduce**

My settings.yml loaded in the EIA 860 and 923 data for all available tables and years. 

```python
from pudl.output import eia860
eia860.generators_eia860()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pudl/pudl/output/eia860.py", line 259, in generators_eia860
    on=['plant_id_eia', 'report_date'])
  File ".../python3.7/site-packages/pandas/core/reshape/merge.py", line 61, in merge
    validate=validate)
  File ".../pandas/core/reshape/merge.py", line 555, in __init__
    self._maybe_coerce_merge_keys()
  File ".../pandas/core/reshape/merge.py", line 986, in _maybe_coerce_merge_keys
    raise ValueError(msg)
ValueError: You are trying to merge on datetime64[ns] and float64 columns. 
If you wish to proceed you should use pd.concat
```

**Expected behavior**
I expected the generators table.

**Desktop:**
 - OS: Ubuntu 18.10
 - postgresql version: 10.6
 - Python version: 3.7

**Comment by zaneselvans** [comment]
Hey Karl, I suspect this is the same issue as #236 -- for some reason that we haven't chased down yet the output functions all seem to fail unless there's at least one year of FERC data in the DB.

**Comment by karldw** [comment]
Ah, got it. Thanks!

**Comment by zaneselvans** [comment]
You might also try doing the same output but using a PudlTabl output object to do it.
