### ISSUE TITLE
Convert FERC1-EIA record linkage outputs to Dagster assets

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#2439]
```[tasklist]
- [x] `gens_mega_eia`
- [x] `plant_parts_eia`
- [x] `ferc1_to_eia`
```

**Comment by bendnorman** [comment]
What is the status of converting the `ferc1_to_eia` portion to dagster assets @katie-lamb? Is this blocking merging in the rename PR and doing a data release or can we convert it after the fact?

**Comment by zaneselvans** [comment]
WOO we're done with getting all of our assets into Dagster!!!
