### ISSUE TITLE
Use Pandas nullable Integer, Boolean, and String datatypes

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#252]
As of [Pandas 1.0.0](https://pandas.pydata.org/pandas-docs/stable/whatsnew/v1.0.0.html), there are several Pandas specific nullable data types that will remove a bunch of headaches we've been working around, these include:
* [Nullable integers](https://pandas.pydata.org/pandas-docs/stable/user_guide/integer_na.html)
* [Nullable Booleans](https://pandas.pydata.org/pandas-docs/stable/user_guide/boolean.html)
* A dedicated (and nullable) [StringArray](https://pandas.pydata.org/pandas-docs/stable/whatsnew/v1.0.0.html#dedicated-string-data-type) datatype.

Using these data types should simplify a bunch of things in the ETL, and allow us to ditch `fix_int_na()` and the workarounds for mixed string columns that look numeric in some years of data, and the cases where we have missing Boolean values.

Probably needs to happen in conjunction with exhaustive typing of the database columns when they are extracted and maybe when they are being used in the `PudlTabl` output objects too.

This issue should really be broken down into several different ones with more detail... this is a placeholder for now.

**Comment by cmgosnell** [comment]
I've made some progress on this with Issue #403.
