### ISSUE TITLE
Boiler manufacturer name and code are null

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#2522]
### Describe the bug
In the `boilers_entity_eia` table, there are only null values for the `boiler_manufactuer` and `boiler_manufacturer_code` columns.

This is true in the outputs, and also after the `clean_boilers_eia860()` has been run, where this is done:

```python
    # Add boiler manufacturer name to column
    b_df["boiler_manufacturer"] = b_df.boiler_manufacturer_code.map(
        pudl.helpers.label_map(
            CODE_METADATA["environmental_equipment_manufacturers_eia"]["df"],
            from_col="code",
            to_col="description",
            null_value=pd.NA,
        )
    )
```

Not sure why this isn't being caught by our "no null columns" data validations.

**Comment by e-belfer** [comment]
Is this only happening in the fast ETL, or in the full as well? This is a column that only exists in 2009 & 2010 I believe.

**Comment by zaneselvans** [comment]
Ahhh, interesting. Not sure if I checked both.

**Comment by e-belfer** [comment]
I just reran this, and running the full ETL we do see columns with data here (2,712 rows). As expected, there's no data here at all for the fast ETL as these columns don't exist. Closing this issue.
```
from dagster import AssetKey

from pudl.etl import defs

asset_key = "core_eia__entity_boilers"
df = defs.load_asset_value(AssetKey(asset_key))
has_manufacturers = df[df.boiler_manufacturer.notnull()]
has_manufacturers
```

Produces a table that looks like (first few rows for sample):

|     | plant_id_eia | boiler_id |                               boiler_manufacturer | boiler_manufacturer_code |
|----:|-------------:|----------:|--------------------------------------------------:|-------------------------:|
| 164 |        58215 |       ST1 | Other (specify in a Footnote on SCHEDULE 7, CO... |                       OT |
| 190 |        58079 |    HRSG-2 |                   Vogt Machine Company/Vogt Power |                       VO |
| 191 |        58079 |    HRSG-1 |                   Vogt Machine Company/Vogt Power |                       VO |
| 206 |        58005 |     HRSG2 |                                               NEM |                       NM |
| 207 |        58005 |     HRSG1 |                                               NEM |                       NM |
