### ISSUE TITLE
Generator level compilation without fuel costs

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#253]
The current MCOE output function brings together a ton of useful information at the generator level, however, it requires fuel costs to be present in order to generate an output record. This is kind of appropriate when the fuel costs are the quantity of interest, but in other cases (e.g. carbon emissions intensity) it also wipes out other useful data.

Instead, we should either preserve the other data in rows that have NA values for costs, or we should create a separate output function that does not attempt to integrate the costs (which are the source of the overwhelming majority of the NA values)

**Comment by cmgosnell** [comment]
I think I just fixed this with my last [commit](https://github.com/catalyst-cooperative/pudl/commit/a5d1cf98f0ec5c72fb48336cafaf31bf11e6128e).
