### ISSUE TITLE
Output complete EIA time series

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#254]
**Is your feature request related to a problem? Please describe.**
Time series analysis often requires that **all** of the timesteps be present in the series, even if they do not contain valid data, for windowing, averaging, etc. However, the MCOE outputs drop records which have NA values for costs entirely, rather than preserving them and delivering complete time series.

**Describe the solution you'd like**
Rather than completely dropping records that have one invalid value, we should retain the whole record, so whatever useful data is there is available. In cases where no data is available, empty dummy rows with entity information but no "data" fields should be added to complete the time series.

**Comment by zaneselvans** [comment]
The recent re-vamp of the MCOE process should at least partially address this issue? If you run `pudl_out.mcoe(all_gens=False)` you'll get any generator-years / generator-months that have data in either the `fuel_cost()` or `capacity_factor()` outputs (as opposed to `all_gens=True` which also includes all of the generators). If there are generator-year/months that have no MCOE outputs, they'll still be missing from the MCOE outputs but there will be many fewer slots to fill-in to get complete timeseries.

**Comment by cmgosnell** [comment]
closing bc this is too vague.
