### ISSUE TITLE
spot check xbrl metadata calculations within `electric_operating_revenues_ferc1`: usable or not?

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/pudl#2579]

**Comment by e-belfer** [comment]
See #2016 for full notes. This table is missing two sub-components which originate from the rate schedule table and will need to be incorporated as a cross-table calculation. Otherwise, all calculations appear as expected.

**Comment by e-belfer** [comment]
Reopening now that this sub-component issue has been fixed in #2599 as there are still missing data issues.

**Comment by e-belfer** [comment]
Missing data issues seem to have been resolved in the reorganization of the transformer in #2618
