### ISSUE TITLE
Inject DBF-only factoids into calculation metadata

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#2700]
In developing the XBRL calculation trees, we discovered that a number of facts we had assigned to values reported only in the older DBF data had not been incorporated into the calculations or metadata. Many of these facts are involved in the balance sheet and income statement table explosions, and should be included in order to get the most  ideally they would be included in order to ensure the accuracy of calculations in older years.

Right now, discrepancies from this omission are probably being masked by the calculation reconciliation process where we add `_correction` records, which means they're probably relatively small (since we have tolerances on what amount of "correction" is allowed).

Only in the case of `special_funds_all` which comes from `f1_comp_balance_db` (aka `balance_sheet_assets_ferc1`) has the value been integrated into the calculations (but it wasn't also added into the metadata directly, which is causing a separate issue).

To see the list of all of these DBF only factoids, open up [src/pudl/package_data/ferc1/dbf_to_xbrl.csv](https://github.com/catalyst-cooperative/pudl/blob/main/src/pudl/package_data/ferc1/dbf_to_xbrl.csv) and filter for records where `dbfonly` is True.

The fact that these factoids show up in this file means they will appear in the multi-year data already. They'll also need to be added into the appropraite calculations, and into the metadata itself during `process_xbrl_metadata()` for the relevant tables.

```[tasklist]
- [x] ("balance_sheet_assets_ferc1", "special_funds_all"),
- [x] ("balance_sheet_assets_ferc1", "nuclear_fuel"),
- [x] ("balance_sheet_liabilities_ferc1", "accumulated_deferred_income_taxes"),
- [x] ("electric_operating_expenses_ferc1", "load_dispatching_transmission_expense"),
- [x] ("income_statement_ferc1", "miscellaneous_deductions"),
- [x] ("balance_sheet_assets_ferc1", "preliminary_natural_gas_survey_and_investigation_charges"),
- [x] ("electric_energy_sources_ferc1", "megawatt_hours_purchased"),
```

### Process:
- What table is it in?
- What calculation(s) *should* it be part of (where are its later-day siblings?)
- Is part of a calculation fix already? If not, add it.
- Do a couple of manual additions to metadata, and then figure out how to parameterize the addition.

**Comment by e-belfer** [comment]
Closed in #2747
