### ISSUE TITLE
Integrate EIA 923 2022 early release data

### ISSUE THREAD

**Issue by aesharpe** [catalyst-cooperative/pudl#2732]
- [x] Add the new Zenodo archive DOI values to `pudl/workspace/datastore.py`.
- [x] Run the datastore script to download the new year of data.
- [x] Add the new year to the years in `etl_full.yml` and `etl_fast.yml`.
- [x] Add the new year to the `working_partitions` in `pudl/metadata/sources.py`
- [x] Update the information in `pudl/package_data`:
     - [x] file maps (add _Early_Release suffix!)
     - [x] column maps (probably the same)
     - [x] page maps (probably the same)
     - [x] skip footer (probably the same)
     - [x] skip rows (+1 for early release data)
- [x] Launch dagit and refresh the code location.
- [x] Materialize the `raw_eia923` asset group. Look out for warnings in the logs about missing or extra columns. If they appear, check and update the `package_data` accordingly.
- [x] Materialize the `clean_eia923` asset group. You'll probably see some errors related to encoding. Take a look at which column it's talking about and look at `metadata/resources/eia.py` to see which encoder in `CODE_METADATA` to tweak.
- [x] Update the validation test `test_minmax_rows` in `test/validate/eia_test.py`.
- [x] Run `tox` and troubleshoot what else might be broken! Might include things like:
     - Foreign key errors
     - The need to map new plants or utilities (https://catalystcoop-pudl.readthedocs.io/en/dev/dev/annual_updates.html#connect-datasets)
     - All sorts of other whacky stuf.

**Comment by ggurjar333** [comment]
Can I TAKE this?

**Comment by aesharpe** [comment]
Hey @ggurjar333 I think @e-belfer is gonna take this one! But if you want to chip in maybe take a look at this issue in our archiver repo? This would really help us usher in the new data sooner. https://github.com/catalyst-cooperative/pudl-archiver/issues/68

**Comment by e-belfer** [comment]
Closed in #2741
