### ISSUE TITLE
Add dimensions and tabular calculations to XBRL Calculation Forests

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#2736]
With #2721 merged, the additional dimensions `utility_type`, `plant_status`, and `plant_function` are available in the newly compiled tabular calculation components table and in the exploded dataframes.

In order to validate and debug the calculations that involve these dimensions, and use them in analysis of the exploded data, they need to be integrated into the calculation forests, and the leaf-based filtering of the exploded data.

Rather than identifying a calculation component by (`table_name`, `xbrl_factoid`) we'll now need to use a tuple that also includes all of the other dimension columns. In many cases these will include null values, since not all dimensions are involved in all calculations.  This larger tuple will also be used to filter the final exploded data table.

```[tasklist]
- [x] Use calc components table to construct calculation tree.
- [x] Use additional dimensions to filter the exploded dataframe.
```

**Comment by zaneselvans** [comment]
# Questions
- There's only one set of columns for `utility_type`, `plant_status` and `plant_function`. Do those values always apply to both the calculation component and the higher level fact that they're being aggregated into? That seems like it can't be true, since sometimes we'll have a calculated value that potentially sums up different kinds of values from different dimensions in different tables depending on e.g. `utility_type`.
- Does the `balance` column still have meaning with all of the mucking around we've done in the calculations?
- What does the `subdimension` column mean? What values are allowed in it?
- There are a handful of `electric` values found in the `plant_function` column, but I don't think that's a valid value, based on the enumerated values in `pudl.transform.ferc1.params.PLANT_FUNCTION_CATEGORIES`
- What became of the `source_tables` lists?
- At first glance it seems like the exploded metadata has been supplanted by the calculation components table. How are they different? The exploded metadata contains all the directly reported (uncalculated) values, but the calculation components only contain calculated values.
- `utility_function` does not appear in the exploded data table for `balance_sheet_assets_ferc1`

**Comment by cmgosnell** [comment]
- In the exploded calculations there's only one set of columns for the additional dimensions. Do those values always apply to both the calculation component and the higher level fact that they're being aggregated into? That seems like it can't be true, since sometimes we'll have a calculated value that potentially sums up different kinds of values from different dimensions in different tables depending on e.g. utility_type.
   - the dimensions apply to the calculation components not the higher level fact.

**Comment by zaneselvans** [comment]
I'm struggling with the new `calculation_components_xbrl_ferc1` association table. The `MetadataExploder.calculations()` method needed to be updated to appropriately manage calculations that refer to components from outside of the explosion (turning them into parent-only calculation components) but either the inputs don't look like I think they do, or I'm doing something wrong in the new method, or my expectations about what should be true about the dataframe that's coming out of the method are wrong. See #2763
