### ISSUE TITLE
Apply start and end dates to ferc1 data in PudlTabl objects

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#274]
The PudlTabl tabular data output class takes a `start_date` and an `end_date` at initialization, and uses they to restrict the date range of the EIA data accessed and output. However, it applies no restrictions to the FERC data it outputs. This is incorrect.

May also want to consider allowing different EIA and FERC start/end dates, given how different the scope of available data is (which will become a bigger issue with EPA CEMS data.)

**Comment by jdangerx** [comment]
@cmgosnell this is done, right? it's marked as blocked on "convert report_year in ferc to report_date" but we just wrote custom code to handle report_year instead.
