### ISSUE TITLE
Functionalize data sanity checks

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#279]
Many of the data sanity checks that we are doing on our tabular outputs are similar to each other, and those tests can be functionalized for re-use. A new module `pudl.validate` containing these functions should be created and existing sanity checks should be converted to use the generalized forms. See #275, #276, #277, & #278 for examples of where these tests will get used.

This will help us ensure that the data validation notebooks and visualizations, which parallel the `test/validation` tests, are doing exactly the same operations as the tests that are running (and passing or failing) in the pytest modules.

## Types of validation tests
What are the different kinds of data validation that we're going to need to do repeatedly?

### Absolute / intrinsic values See #388 
In some cases, we know that a column should contain values that lie within a particular range. E.g. we know the heat content of each fuel type in terms of mmBTU/unit, and we should be able to check whether values are consistent with those expectations. These tests don't need to ensure that *every* value is reasonable, but should tell us whether the whole dataset is okay or if something has gone horribly wrong. It could also be good if these test can be used to generate masks that exclude "unreasonable" values.
* Median value of a column within a given range (takes a min and a max acceptable value)
* Upper end of a column's values is less than a given value (takes a percentile and a value)
* Lower end of a column's values is greater than a given value (takes a percentile and a value)

How do we figure out what the right values are to test against here? We could eyeball it... or we could take some representative subsamples of the whole dataset to see how variable the distribution is.  One way to subsample would be by year. This would also mean that we could choose boundaries that won't flag anything as broken even if a particular year is loaded by itself, and it has some systematic difference from the dataset as a whole (e.g. fuel prices were high that year).

### Masking / sub-selecting
For many of the tests that expect values to fall in a certain valid range, we will have different valid ranges depending on some other field in a table (e.g. fuel type) so we need to be able to select the appropriate rows before checking whether the values are valid.
* Should this masking / selection be part of the validation function? Or should it be done before the dataframe is passed in to the validation function?
* The more functionalized it is, the easier it will be to ensure that the same validation is being run in the tests and in the notebooks, but the harder it will be to keep the functions generic and usable in a bunch of different contexts.

**Comment by zaneselvans** [comment]
I feel like it might make sense to create a `pudl.validate` module or subpackage to house functions that check if the data is in good shape.

**Comment by cmgosnell** [comment]
that makes a lot of sense to me. having all of the data validation only in the tests seems like it would be a waste. I'm sure we'll want to use the validation functions in other contexts.
