### ISSUE TITLE
Integrate FERC Form 1 2022 data

### ISSUE THREAD

**Issue by aesharpe** [catalyst-cooperative/pudl#2813]
We recently discovered that FERC was missing some data (it wasn't getting pulled by the extractor), so we're working on re-jiggering the extractor to fix this: https://github.com/catalyst-cooperative/ferc-xbrl-extractor/issues/105 and #2810 

Once that's done, we'll be ready to integrate the FERC 2022 data

- [ ] Add the new Zenodo archive DOI values to pudl/workspace/datastore.py.
- [ ] Run the datastore script to download the new year of data.
- [ ] Add the new year to the years in etl_full.yml and etl_fast.yml.
- [ ] Add the new year to the working_partitions in pudl/metadata/sources.py
- [ ] Clone the FERC1 data into SQL
- [ ] Launch dagit and refresh code location
- [ ] (update alembic?)
- [ ] Materialize the raw asset group and debug.
- [ ] Materialize the clean asset group and debug.
- [ ] Run the fast ETL and debug.
- [ ] 
- [ ] Update the validation test min/max rows

**Comment by e-belfer** [comment]
Closed because this issue has been taken up in #2811.
