### ISSUE TITLE
Migrate FERC DB cloning to SQLite

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#283]
Even after we move to a datapackage based endpoint for the ETL process, we will still need to spin up some kind of DB to clone the FERC database out of its FoxPro jail. In order to keep the overall setup and dependencies of PUDL as simple as possible, it seems like switching to using SQLite instead of Postgresql would probably be a good idea.

Should we keep using SQLAlchemy for this? It seems like there's probably a lighter-weight way to go about it.

**Comment by swinter2011** [comment]
test comment sync 4
