### ISSUE TITLE
Create shared diagnostic tooling for XBRL calc mismatches

### ISSUE THREAD

**Issue by jdangerx** [catalyst-cooperative/pudl#2870]
We compare the calculated & reported values in our XBRL data in a few different places.

It would be nice if these comparisons could share code, though if the diagnostics differ wildly that may not be practical.

```[tasklist]
## Scope
- [x] there is one piece of shared code that we can add new diagnostics to
```

**Comment by jdangerx** [comment]
@zaneselvans or @cmgosnell you all have a branch for this, right? Where is it at?

**Comment by zaneselvans** [comment]
The first part of this was under #2880 -- just getting all of the calc checks to use the same function. @cmgosnell also has #2886 but it sounds like we might be moving in another direction with getting those calculations untangled.

I'll create a new branch / PR that's linked to #2872 that tries to get new metrics in there and maybe separate the steps of the performing the calculations, checking how accurate they are, and generating the corrections.

**Comment by jdangerx** [comment]
I think since #2880 is merged, and the rest of the "metrics stuff" lives in #2872 we can close this issue.
