### ISSUE TITLE
Define XBRL explosion success metrics and measure them

### ISSUE THREAD

**Issue by jdangerx** [catalyst-cooperative/pudl#2872]
## When & Where to Check?
There are at least 3 places where we check for discrepancies between reported values and the calculations that are supposed to reproduce them. 
* In the FERC 1 table transformers, we check all **intra-table** calculations and each table has it's own expected rate of errors.
* Early in the FERC 1 table explosions, which combine several tables, we check all **inter-table** calculations, and each explosion has it's own expected rate of errors.
* At the end of the explosion, after we've collapsed all the calculations into a single formula that connects the root to the leaves which contribute to it.

All of these contexts will use the same function and be able to calculate the same kind of error metrics. The output that we start with is a table organized by calculation node ID: (`table_name`, `xbrl_factoid`, `utility_type`, `plant_status`, `plant_function`).  For each of these records, we get a reported value and a calculated value, from which we can calculate a relative (fractional) and an absolute error.

## Existing Metrics
* What fraction of **all** records have reported & calculated values that are not identical within some tolerance (fed into `np.isclose()`)

## Potential new metrics:
* **Aggregate absolute error (USD):** sum up all of the absolute errors within a group of records.
* **Aggregate relative error:** Divide the aggregate absolute error by the total value reported in the same group.
* **Percent duplicated:** sum up all of the absolute errors where the relative difference is exactly equal to one within a group of records, and divide by the total number of calculations with errors. Quick metric to flag problems in the calculation component aggregations.

## Plotting, Slicing & Dicing
In addition to calculating the above suggested metrics on the entire dataset, we can break down the outputs along several additional dimensions to narrow down the potential source of issues with some judicious use of `groupby()`. The columns we `groupby()` can come either from the data side (the individual filings) or the metadata side (which defined the calculations. The most obvious columns to use are:

* `report year` (data)
* `utility_id_ferc1` (data)
* `table_name` (metadata)
* `xbrl_factoid` (metadata)

We can also plot the **distribution** of error values within a group, rather than just looking at a single fraction or aggregated value.  In the case of `report_year` we can also look at how an error metric has evolved over time for the dataset as a whole, or within individual groups along other non-temporal dimensions.

We can prioritize which subset of the overall dataset to focus on based on the above metrics, for example:
* Identify calculations to debug based on which `xbrl_factoid` values have the highest error fraction.
* Identify utilities who frequently introduce errors with large dollar value errors and see if there's a systematic fix, or if we should flag them as unreliable.
* Identify individual years of data that have particularly bad errors to focus on even if the overall level of error is otherwise acceptable.

### Original Source Data / Metadata
* Data entry errors introduced by FERC respondents (wrong units, using the wrong version of the form, sign errors, revising numbers in one part of the form that do not get updated elsewhere resulting in internal inconsistencies)
* Errors in the intra-table calculation definitions supplied by the FERC XBRL metadata (misspellings of fact names, omission or incorrect inclusion of facts in a calculation)

### Manually Compiled Calculations
* (intra-table) Errors in our hand-compiled fixes to the FERC supplied calculation definitions.
* (intra-table) Errors introduced through our renaming of facts to fix internal inconsistencies / spelling errors.
* (intra-table) Errors in the algorithm we use to infer intra-fact calculations that sum across dimensions like `utility_type` (Q: do we actually do this in the table transforms right now? If not why not?)
* (inter-table) Errors in the calculations that we have compiled / inferred which link different tables.

### Graph Transformation
* Errors in the process of transforming the calculation components into a graph.
* Errors in the process we use to prune the graph, removing unnecessary components.
* Errors in the process we use to convert the many individual sub-totals into a single large calculation

## Examples
* If the calculations look good overall but are off across the board for a particular individual fact, we would want to check whether there's an obvious error in the calculation as defined by FERC, or if it's a calculation that we previously altered, in a way that is no longer applicable.
* We see that the rate of errors within a particular table are small from 1994-2020, and then it jumps in 2021 across all utilities. This would suggest that the errors are specific to the XBRL and related to that table. We should probably go look at our XBRL transform function for that table.
* We see that a small subset of utilities have very high error rates in the same tables in the same years, but generally good data in other years and other tables. If we see that the years and tables in which the error rates are high correspond to years in which those tables were updated and the row numbers changed their meaning, this would suggest that the errors are due to the utilities using outdated versions of the Form 1. We can either flag those combinations of utility-year-table as bad and set them to NA, or attempt to parse that data using a row map from the year of the form they appear to have used.
* If we see a set of facts for which the relative error is exactly 1.0, that would suggest that the same values are being counted twice, probably due to a bug in the way the calculations are being constructed for those facts, and we should look at how we're treating those facts in the calculation component compilation process, in our manually fixed calculations, or 
* If the proportion of records whose calculated & reported values don't match is small, but the absolute dollar value of the mismatch is large, we can look at just those facts with a relative error of 10x or more. If all of the extreme outliers are off by a factor of exactly 1000x, it might be that the utility accidentally used kW instead of MW, or thousands of dollars rather than dollars, etc. and that error could be corrected upstream. If the relative error is much more random and pervasive across an entire utility-year-table, it might be another indication of the utility using an outdated form.
* With 30 years of data, we could have almost perfect data in 29 years, and completely bad data in 1 year and the aggregate error rate would only be 3% which might look acceptable overall, but would actually mean the data in that one year is unusable.

## Current Error Levels
Note that at the end of each of these reconciliation processes we add "correction" records that force the totals to match perfectly when they are included. This prevents errors in earlier stages from compounding and allow us to isolate new errors within a particular portion of the process. These corrections can also be used alongside the values they are correcting to get a sense of how reliable the original value is. Most corrections should be 0.

### Intra-Table Error Fractions
* default: **0.05**
* `plant_in_service_ferc1`: **0.08**
* `retained_earnings_ferc1`: **0.08**
* `electric_plant_depreciation_changes_ferc1`: **0.40** (not part of explosions, not yet debugged)

### Inter-table Error Fractions
* `income_statement_ferc1`: **0.20**
* `balance_sheet_assets_ferc1`: **0.85** ❌ something is obviously very wrong here
* `balance_sheet_liabilities_ferc1`: **0.07**

### Root-to-Leaf Error Fractions
Really there should be no errors here -- all we're doing is transforming the underlying intra- and inter-table calculations, and selecting a subset of them for inclusion in the final output. Any error here can only be due to programmatic error on our part, which we should fix.

### Establishing a Baseline
We should be able to calculate:
* Fraction of records with errors
* Absolute dollar value of errors
* Relative magnitude of errors

For each:
* table transform, looking only at intra-table calculations.
* set of exploded tables, looking at only inter-table calculations.
* set of exploded tables, incorporating both intra- and inter-table calculations?
* set of exploded tables, looking just at the root-to-leaf calculation

For each combination of:
* Year
* Utility ID
* Table
* Fact

and hopefully by looking at some histograms, and the list of worst offenders in each category, get a sense of where the problems are and how bad they are, and make a prioritized list of them to chase down.

## Error Targets
* We want a small number of overall records whose calculated and reported values do not match.
* To the extent that there **are** errors, we want to be sure that they're in the underlying data, and not due to our code.
* Repairing errors in the underlying data & metadata can be labor intensive and we should go after easy programmatic fixes that apply to lots of records first, and be aware of when we get to the point of diminishing returns.
* There are far more intra-table calculations (which originate from FERC) than inter-table calculations (which we have compiled).
* Within what aggregations does it matter if there are very large dollar value errors? If users want to talk about aggregate results across all utilities, a single utility that has reported a number in the wrong field could drastically skew the entire result, and would need to be identified as an outlier and removed for the aggregate value to be valid.
* What's the relationship between tolerable calculation errors levels for the dataset as a whole, vs. for a particular year, or a particular utility? Do we want to cap the error frequency, aggregate absolute, or aggregate relative errors in any individual year? Or any other groups?

```[tasklist]
- [ ] Split calculation reconciliation into 3 steps: Calculating Values, Calculating & Checking Errors, Adding Corrections.
- [ ] Define API for these three steps
- [ ] write code to measure explosion accuracy
- [ ] decide on success criteria for explosion accuracy - this might be a total % combined with some sort of minimum % per year
```

**Comment by jdangerx** [comment]
We could define explosion accuracy as:

For every calculated value for a root calc in the exploded table:

```
(1 - abs(weighted sum of leaf values - reported value))
```

For each exploded table, we want:
* average across all utilities X report years > 95%
* every (utility, report year) > 90%

**Comment by jdangerx** [comment]
I'm just making up thresholds from thin air right now - it might make sense to start measuring these and see where they go after we start fixing things.

I think there are two perspectives we can take for setting thresholds:
* how close is "close enough" for our users' use cases? We could ask e.g. some of the folks at RMI what they need.
* how close is "as accurate as possible, given the input data we have?" We'd have to somehow know how many errors are in the input data, which seems much harder. 

Seems like the first bullet should be our approach

**Comment by cmgosnell** [comment]
## Some Preliminary Results
<img width="1229" alt="image" src="https://github.com/catalyst-cooperative/pudl/assets/25487998/ce64cdeb-3129-46d7-afd4-27948a8daccc">

<img width="1236" alt="image" src="https://github.com/catalyst-cooperative/pudl/assets/25487998/f668e225-d136-4c9d-9703-3561e502fa5e">

<img width="1232" alt="image" src="https://github.com/catalyst-cooperative/pudl/assets/25487998/a7f89ff8-2a0e-4ed5-8f35-8b89047fc61e">

hahah this one looks real goth/completely illegible but you can see that there are only a handful of facts that are worth investigating
<img width="923" alt="image" src="https://github.com/catalyst-cooperative/pudl/assets/25487998/79a6b40a-7259-4455-9704-da5279e03ce3">

With this file [calculation_metric_checks.csv](https://github.com/catalyst-cooperative/pudl/files/13048412/calculation_metric_checks.csv) and the code snippet below you can explore the worst of the metrics across all of the tables:

```
calculation_metric_checks = calculation_metric_checks.set_index(["group", "table_name", "group_value"])
metrics_to_check = ["error_frequency", "relative_error_magnitude", "null_calculation_frequency"]
groups_to_check= ['table_name', 'xbrl_factoid', 'utility_id_ferc1', "report_year"]

metric = metrics_to_check[1]
group_name = groups_to_check[0]


print(group_name)
(
    calculation_metric_checks.groupby(level=["group", "table_name"]).max()
    .filter(like=metric)
    .loc[group_name]
    .sort_values(metric, ascending=False)
    .round(5)
)
```

**Comment by zaneselvans** [comment]
This is amazing @cmgosnell! I think there's something funny with the x-axis in the by-year plots, but this is so much more readily interpretable.

**Comment by zaneselvans** [comment]
What does it mean that a handful of calculated facts can be 100% null, and that can somehow result in half of all calculations being null when grouped by year or utility? Is that just the nulls propagating somehow within those broader groups, while they're very narrowly confined when grouped by fact?

**Comment by cmgosnell** [comment]
I think this was fully done with #2915
