### ISSUE TITLE
Clean up exploded assets and rate base tags

### ISSUE THREAD

**Issue by e-belfer** [catalyst-cooperative/pudl#2892]
Based on a first round of feedback, let's address some outstanding issues with the exploded assets and rate tags.

#2894:
- [x] Remove rate base tag from `allowances` factoid in `income_statement_ferc1`
- [x] And add it to `allowance_inventory_and_withheld` ?
- [x] Add dbf2020 information to depreciation_amortization_summary_ferc1
- [x] `less_derivative_instrument_assets_hedges_long_term` should be connected to row 66
- [x] `less_derivative_instrument_assets_long_term` should be connected to row 64
- [x] `less_noncurrent_portion_of_allowances` should be connected to row 53
- [x] `less_long_term_portion_of_derivative_instrument_liabilities` should be connected to row 51
- [x] `less_long_term_portion_of_derivative_instrument_liabilities_hedges` should be connected to row 53
- [x] `other_miscellaneous_operating_revenues` needs a DBF 2020 row (25?)
- [x] check that `special_funds_all = special_funds + other_special_funds` calc in `balance_sheet_assets_ferc1` is not dropped, or add if missing
- [x] check that `preliminary_natural_gas_and_other_survey_and_investigation_charges = preliminary_natural_gas_survey_and_investigation_charges + other_preliminary_survey_and_investigation_charges (+ maybe preliminary_survey_and_investigation_charges)` calc in `balance_sheet_assets_ferc1` is not dropped, or add if missing
- [x] check that `nuclear_fuel` calc (see rows 7-13) in `balance_sheet_assets_ferc1` is not dropped, or add if missing
- [x] check that `accumulated_deferred_income_taxes = accumulated_deferred_income_taxes_accelerated_amortization_property + accumulated_deferred_income_taxes_other_property + accumulated_deferred_income_taxes_other` calc in `balance_sheet_liabilities_ferc1` is not dropped, or add if missing
- [x] `plant_in_service_ferc1` should generally be `plant_status = in_service`, except for electric_plant_purchased and electric_plant_sold
- [x] `balance_sheet_assets_ferc1` table doesn’t have utility_type labeled
- [x] Fix `plant_function` in `out_ferc1__explosion_tags`
- [x] Add `utility_type` to balance sheet liabilities and retained earnings tables
- [x] Fix tags to remove `partial` conflicting tags and tag at the `plant_status` level for `accumulated_depreciation` and `accumulated_provision_for_depreciation_amortization_and_depletion_of_plant_utility` children
- [x] Add `plant_status` tags to all tables missing (`utility_plant_summary_ferc1`) and set up tagging infrastructure to handle >1 csv

#2916 
- [x] label `plant_in_service_ferc1` `plant_function`
- [x] label `electric_operating_expenses_ferc1` `plant_function`

#2918 
- [x] Add dbf2020 information to electric_plant_depreciation_functional_ferc1

Still to do:
- `electric_plant_sold` and `electric_plant_purchased` are getting marked with `utility_type` `in_service`
- Plant function tags not propagating as expected in forest as table

Out of scope
- Clean up the new cruft from #2810

**Comment by e-belfer** [comment]
The four missing calcs can be explained by DBF-only factoids used up through 2003, which were later replaced by multiple more detailed factoids. See #2700 for more detail.

**Comment by cmgosnell** [comment]
hey @jrea-rmi ! one hopefully simple question... for the `utility_plant_summary_ferc1` labeling of the `plant_status`-es, they should be labeled within the headers that are in the taxonomy/form itself? As in the field labeled "Leased to Others" in the "In Service" section should be labeled `in_service` not `leased`, right?

**Comment by cmgosnell** [comment]
also i was a little too hopelessly optimistic yesterday about adding the `plant_status's into the core db tables! The sticking point here is that when we check the calculations, we use the dimension columns as merge keys, which effectively means dimensions on the parent and child side of a calculation need to be either *the same value* or be null. (i believe!)

which means we add em as tags!

**Comment by jrea-rmi** [comment]
phew, I was confused by "Leased to Others" within "In Service." Generally, the plant_status coming from this table has been maybe the most confusing thing to me in all of FERC data.

I think `utility_plant_net = utility_plant_and_construction_work_in_progress - accumulated_provision_for_depreciation_amortization_and_depletion_of_plant_utility `. And that it'd make sense for all of those to be labeled as `"plant_status"=="total"`. 

I think `construction_work_in_progress` should get the same `plant_status` label of `construction_work_in_progress`. Do you have any alternative ideas?

**Comment by e-belfer** [comment]
> I think construction_work_in_progress should get the same plant_status label of construction_work_in_progress. Do you have any alternative ideas?

Assuming you mean `utility_plant_construction_work_in_progress` and `construction_work_in_progress` should both get the same label? In which case, they're both currently NA's but perhaps total makes most sense here. The other total labellings suggested all make sense to me @jrea-rmi and I can update them.

**Comment by jrea-rmi** [comment]
> > I think construction_work_in_progress should get the same plant_status label of construction_work_in_progress. Do you have any alternative ideas?
> 
> Assuming you mean `utility_plant_and_construction_work_in_progress` and `construction_work_in_progress` should both get the same label? I agree. The other total labellings suggested all make sense to me @jrea-rmi and I can update them.

I'm thinking `utility_plant_and_construction_work_in_progress` with `plant_status=="total"` and `construction_work_in_progress` with `plant_status=="construction_work_in_progress"`

**Comment by cmgosnell** [comment]
I think this one is fully closable but @e-belfer if you have an objections to that plz just reopen
