### ISSUE TITLE
generate schema for datapackaging

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/pudl#292]
In our migration to datapackages (and away from the pqsl database), we need to basically translate the existing sqlalchemy schema into table schemas that conform to the [frictionless data spec](http://frictionlessdata.io/specs/table-schema/).

**Comment by cmgosnell** [comment]
Right now you can generate a functional set of metadata based on the existing psql database by running this [notebook](https://github.com/catalyst-cooperative/pudl/blob/master/results/notebooks/data_packaging_prep.ipynb). Especially for the resource and table schema specs, I'm imagining the full metadata will be stored in one place and we'll use it/modify it to generate whatever version specific metadata we need. As I was discussing in Issue #319, we're probably going to want the ability to pull a subset of the data sets into a package, which means we'll want to pull a subset of table schema's from the main metadata. Are there any good existing packaging feature that would aid in this process @lwinfree @roll?

To note: once we have a good working packaging process set up, the plan is to remove the existing psql database so we won't be able to regenerate the metadata. I assume we'll have to update it in a piecemeal fashion as the table specs change.

**Comment by roll** [comment]
@cmgosnell 
Just as a note (if I got it right you don't need it already) that for initial SQL export you can use `datapacakge-py`:

```
# pip install tableschema-sql
from sqlalchemy import create_engine
from datapackage import Package, Resource

DATABASE_URL = 'postgresql://roll:roll@localhost:5432/movies'

descriptor = {'resources': [{'path': 'countries'}, {'path': 'locations'}]}
package = Package(descriptor, storage='sql', engine=create_engine(DATABASE_URL))
package.infer()
package.save('descriptor.json')
```

**Comment by zaneselvans** [comment]
@roll is this a way to go from having a datapackage descriptor to having an empty SQL database based on the included TableSchemas and their interrelationships?

Is there a similarly concise way to generate a tabular datapackage descriptor (or at least a list of tabular data resource descriptors) given an SQLAlchemy engine?

**Comment by cmgosnell** [comment]
Thanks @roll! this would have saved us lots of time! Do you have any tools for easily manipulating or accessing slices of the metadata once it's created? I won't be too hard to just manipulate the json file if there aren't existing tools, but it'd probably be good to use them if they exist.

**Comment by roll** [comment]
@zaneselvans 
It creates a datapackage (pull) from an existent SQL database (allowing to use a subset of tables where a `table` goes to be converted to a `resource`). The `infer` step means that we also ask to use metadata reflection. The codebase is relatively simple and comes at `tableschema-sql-py` driver -  https://github.com/frictionlessdata/tableschema-sql-py/tree/master/tableschema_sql

On the other hand, we can do the other direction (push) something like this:
```
# pip install tableschema-sql
from sqlalchemy import create_engine
from datapackage import Package, Resource

DATABASE_URL = 'postgresql://roll:roll@localhost:5432/movies'

package = Package('path/to/datapackage')
package.save(storage='sql', engine=create_engine(DATABASE_URL))
```

And it's not only for SQL we also have drivers for Pandas, BigQquerly, Elasticsearch etc. Other question that some of them require some improvements.

Here architecture overview:
> https://github.com/frictionlessdata/implementations#frictionless-data-implementations

**Comment by roll** [comment]
@cmgosnell 

> Do you have any tools for easily manipulating or accessing slices of the metadata once it's created?

Sure, that's the main `datapackage-py` responsibility - https://github.com/frictionlessdata/datapackage-py#datapackage-py

For example, using the library you can re-arrange your `all-in-one` internal data package into smaller published data packages.
