### ISSUE TITLE
Integrate PHMSA Pipeline Data

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#295]
The US DOT's Pipeline and Hazardous Materials Safety Administration collects a bunch of information about natural gas pipelines. It includes the age, length, state, material, diameter, and owner of natural gas gathering, transmission, and distribution pipelines nationwide.

[See here for more information on the dataset](https://cms.phmsa.dot.gov/data-and-statistics/pipeline/gas-distribution-gas-gathering-gas-transmission-hazardous-liquids)

**Comment by swinter2011** [comment]
test comment

**Comment by zaneselvans** [comment]
We're not using Epics for these kind of perpetual threads any more.
