### ISSUE TITLE
Figure out how to resolve merge conflicts in lock files

### ISSUE THREAD

**Issue by bendnorman** [catalyst-cooperative/pudl#3055]
Now that we are using lock files, we'll get merge conflicts in `pyproject.toml` which are manageable and conflicts in `our *lock.yml` files which are not manageable. We don't want to be resolving dozens of direct and indirect dependency merge conflicts.

[This article suggests](https://dev.to/francecil/lockfile-merge-conflicts-how-to-handle-it-correctly-588b) creating a merge strategy for the lock files.  For example, direct dependency A gets upgraded on `dev` from 0.1 to 0.3 and is upgraded to from 0.1 to 0.2  on a feature branch called `feature`. Merge `dev` into `feature,` and there is a merge conflict in `pyproject.toml` and a handful of conflicts in conda-lock.yml because the indirect dependencies of dependency A changed. We could set a merge strategy for lock files to always use the lock files from the current branch. The merge conflict in `pyproject.toml` will be resolved and the lock files may be temporarily out of sync with `pyproject.toml`. I think this should be ok because when the new resolved `pyproject.toml` file is pushed to GitHub, the `update-conda-lock` action will use the new `pyproject.toml` and clobber the incorrect lock files.

**Comment by zaneselvans** [comment]
Ahhh, so you can specify a particular merge strategy on a per-file basis.

**Comment by jdangerx** [comment]
Yeah, this seems like a good way forward!
