### ISSUE TITLE
Bad lat/lon values for plant_id_eia 60237

### ISSUE THREAD

**Issue by joshdr83** [catalyst-cooperative/pudl#311]
**Describe the bug**
The latitude & longitude values in the plants_entity_eia table are incorrect for plant_id_eia values 60237, as reported by Josh Rhodes.

**Comment by gschivley** [comment]
I assume this is related to #309? Might want to consolidate as a single issue that some plant values have the wrong lat/lon.

Great to see you on here @joshdr83!

**Comment by joshdr83** [comment]
Gotcha — I wasn’t sure that I could do that…

I’ll give it a try.

Thanks!
Josh

**Comment by gschivley** [comment]
@zaneselvans can edit the issue name and we can keep a running list of plants with bad lat/lon in one place rather than opening new issues.

**Comment by joshdr83** [comment]
Sounds good! Thanks - Josh

**Comment by cmgosnell** [comment]
this is a duplicate issue from #309 so I'm closing it.
