### ISSUE TITLE
Allow for sources without years

### ISSUE THREAD

**Issue by gschivley** [catalyst-cooperative/pudl#314]
I'm just about finished with adding a couple IPM tables to PUDL but it's hard to work them into `update_datastore.py`. I had to add a list of `None` to the variable `pc.data_years` to finally make it work. As discussed, the system needs to be overhauled somewhat and made a bit more flexible for adding new sources that aren't available as annual files.

**Comment by zaneselvans** [comment]
Will integrate this into an object-oriented rewrite of the `datastore` subpackage in #182.

**Comment by zaneselvans** [comment]
Closing this and rolling it into the general re-write of  #182.
