### ISSUE TITLE
Port nightly build process to Google Batch

### ISSUE THREAD

**Issue by jdangerx** [catalyst-cooperative/pudl#3208]
This lets us run multiple tag builds at once, and provides an environment where the dang logs show up on time.

Let's try to leave the rest of the system as untouched as possible.

```[tasklist]
## Success criteria
- [ ] ETL runs on Google Batch
- [ ] Slack notifications on success/failure include links to Batch job
```

**Comment by jdangerx** [comment]
As of now, the batch job seems to run the ETL successfully, but doesn't cleanly exit & terminate the batch job when the ETL fails - need to investigate that more.

**Comment by bendnorman** [comment]
It seems like the VM should terminate when the container exits :/ You could use our workaround from our existing set up where we make an API call from within the VM to shut down itself down. Pretty janky but an option!
