### ISSUE TITLE
Nightly build failure 2023-01-10

### ISSUE THREAD

**Issue by jdangerx** [catalyst-cooperative/pudl#3229]
## Outputs link

https://console.cloud.google.com/storage/browser/builds.catalyst.coop/2024-01-10-0603-d62dd5c42-main

## Relevant logs

```
==> Building image with Docker
--> docker host: 20.10.12 linux x86_64
#1 [internal] load .dockerignore
#1 transferring context: 2B 0.0s done
#1 DONE 0.0s

#2 [internal] load build definition from Dockerfile
#2 transferring dockerfile: 336B 0.0s done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/library/python:3.11.0-slim-bullseye
#3 DONE 0.7s

#4 [1/6] FROM docker.io/library/python:3.11.0-slim-bullseye@sha256:b5ee5360b357dcd0ab2e1cc5e22fa589b6734bbd55776df6b1700994febf1527
#4 DONE 0.0s

#5 [internal] load build context
#5 transferring context: 39.35MB 4.3s
#5 transferring context: 90.71MB 9.5s
#5 transferring context: 144.76MB 14.6s
#5 transferring context: 194.28MB 19.7s
#5 transferring context: 243.45MB 24.7s
#5 transferring context: 296.08MB 29.8s
#5 transferring context: 345.25MB 34.9s
#5 transferring context: 394.97MB 39.9s
#5 transferring context: 444.76MB 44.9s
#5 transferring context: 499.75MB 50.1s
#5 transferring context: 550.65MB 55.1s
#5 transferring context: 604.93MB 60.2s
#5 transferring context: 650.33MB 65.2s
#5 transferring context: 696.48MB 70.5s
#5 transferring context: 734.33MB 75.5s
#5 transferring context: 764.45MB 80.7s
#5 transferring context: 796.51MB 85.8s
#5 transferring context: 826.43MB 90.8s
#5 transferring context: 854.75MB 95.9s
#5 transferring context: 884.87MB 101.0s
#5 transferring context: 913.06MB 106.0s
#5 transferring context: 941.97MB 111.1s
#5 transferring context: 969.63MB 116.1s
#5 transferring context: 1.00GB 121.1s
#5 transferring context: 1.03GB 126.3s
#5 transferring context: 1.05GB 131.5s
#5 transferring context: 1.07GB 136.6s
#5 transferring context: 1.10GB 141.8s
#5 transferring context: 1.13GB 146.8s
#5 transferring context: 1.16GB 151.9s
#5 transferring context: 1.19GB 157.1s
#5 transferring context: 1.22GB 162.2s
#5 transferring context: 1.24GB 167.2s
#5 transferring context: 1.27GB 172.3s
#5 transferring context: 1.30GB 177.3s
#5 transferring context: 1.33GB 182.5s
#5 transferring context: 1.35GB 187.6s
#5 transferring context: 1.38GB 192.6s
#5 transferring context: 1.41GB 197.7s
#5 transferring context: 1.44GB 202.8s
#5 transferring context: 1.46GB 207.9s
#5 transferring context: 1.49GB 212.9s
#5 transferring context: 1.52GB 218.0s
#5 transferring context: 1.55GB 223.1s
#5 transferring context: 1.58GB 228.1s
#5 transferring context: 1.60GB 233.3s
#5 transferring context: 1.63GB 238.3s
#5 transferring context: 1.66GB 243.4s
#5 transferring context: 1.69GB 248.4s
#5 transferring context: 1.71GB 253.4s
#5 transferring context: 1.74GB 258.6s
#5 transferring context: 1.77GB 263.7s
#5 transferring context: 1.80GB 268.8s
Error: failed to fetch an image or build from source: error building: failed to receive status: rpc error: code = Unavailable desc = error reading from server: EOF
Traceback (most recent call last):
  File "/home/mambauser/pudl/devtools/datasette/publish.py", line 180, in <module>
    sys.exit(deploy_datasette())
             ^^^^^^^^^^^^^^^^^^
  File "/home/mambauser/env/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mambauser/env/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/mambauser/env/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mambauser/env/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mambauser/pudl/devtools/datasette/publish.py", line 151, in deploy_datasette
    check_call(["/usr/bin/env", "flyctl", "deploy"], cwd=fly_dir)  # noqa: S603
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mambauser/env/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/env', 'flyctl', 'deploy']' returned non-zero exit status 1.
```

## Next steps

Seems like there was some issue deploying to fly.io, maybe a network blip? We can try to download job outputs and deploy manually.

**Comment by jdangerx** [comment]
I downloaded last night's outputs

```
> gsutil -m cp -r "gs://builds.catalyst.coop/2024-01-10-0603-d62dd5c42-main" .
```

Then I added a `--build-only` flag to mirror the `flyctl deploy --build-only` flag, to see if the build works.
Then I ran
```
> PUDL_OUTPUT=~/scratch/2023-01-10/2024-01-10-0603-d62dd5c42-main/ python publish.py --build-only
...
```
which succeeded. Ignore the fact that I got the year wrong in the containing directory 🤦 

So I'll re-run it without the build-only flag, and also make a PR for said build-only flag.

**Comment by jdangerx** [comment]
Re-ran the full deploy and it all worked! If we keep running into this we should consider how to retry automatically or perhaps bake less data into the docker image.

**Comment by jdangerx** [comment]
I'll keep this open until the QOL fix related to this issue gets merged in.

**Comment by zaneselvans** [comment]
In general when we get a failure like this do we actually want to do the redeploy? How do we ensure that the data that's showing up in Datasette corresponds to the data that shows up under the `/nightly` prefix in the distribution buckets and was it generated with the code that's on the `nightly` branch? If something post-etl and testing goes awry, do we just investigate and make it internally consistent by hand?

**Comment by jdangerx** [comment]
Your worry is that whatever outputs are in `builds.catalyst.coop` for this specific build ID doesn't correspond to the outputs that were verified?

I think if you look in the logs, and:

* nothing seems to have gone wrong in the upload to `builds.catalyst` or `pudl.catalyst`
* `nightly` points at the correct nightly build tag

Then it's safe to redeploy - of course, assuming nothing goes wrong in the re-download from GCS / the upload to fly.io.

**Comment by jdangerx** [comment]
Oh, or are you asking about whether we should automatically try to re-deploy? I think if the error occurs in `flyctl deploy` it's worth trying again - everything has passed validation up until that point, you know?

**Comment by zaneselvans** [comment]
I'm trying to think about how our published outputs / repository could end up being inconsistent with each other, depending on which of the individual sub-tasks has failed, and how we impose consistency after the failure has happened

In this case, the only thing that failed was the Fly.io deployment, and nothing depends on it, so re-deploying Fly.io gets everything back in sync.

But if say, copying from builds.catalyst.coop to pudl.catalyst.coop fails, then the s3 outputs would also be out of sync with what got uploaded to Fly.

**Comment by jdangerx** [comment]
Hmm, the fly.io deployment process is from the pre-compressed-outputs days. We could actually have it download the compressed outputs from pudl.catalyst.coop instead of uploading directly from PUDL_OUTPUT - maybe that's more robust?
