### ISSUE TITLE
Re-running PUDL initialization w/ default settings deletes DB

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#323]
**Describe the bug**
If one already has a database initialized, and then runs
```sh
init_pudl.py settings_init_pudl_default.yml
```
The pre-existing database is deleted and replaced with nothing... which is *probably* not what the user wants.

**Expected behavior**
If the user has a database already, and tries to initialize with nothing, probably we should not touch the existing database, and output a big obvious message.

**Comment by cmgosnell** [comment]
how do you think this should translate to the new packaging arrangement?

**Comment by zaneselvans** [comment]
Given that we're going to dump the DB here shortly, probably it doesn't translate directly, but I wanted to remain aware of it.  And maybe more generally, we should try and avoid having anything that people are likely to do without thinking too hard be something that can wipe out all of their data.

**Comment by zaneselvans** [comment]
No longer directly relevant.  Implementing clobber check for FERC 1 SQLite DB in #408 and have a clobber check for the data packages.  Should also have a clobber check for the `datapkg_to_sqlite1` script though...
