### ISSUE TITLE
Clean up and standardize column names

### ISSUE THREAD

**Issue by e-belfer** [catalyst-cooperative/pudl#3277]
We highly distributed the mapping of PHMSA raw data. This means we probably have some inconsistencies across our column naming conventions we should fix. These include:

- [x] Fix ordering of onshore/offshore and transmission/gathering
- [x] Check that categorizations are consistent across tables
- [x] Check missing and extra column errors for all tables to make sure we haven't mismapped anything
- [x] Standardize file names - `transmission_gathering`, `miles`
- [x] Standardize placement of `pipe`
- [x] standardize treatment of time between transmission and distribution data

**Comment by cmgosnell** [comment]
## all the date fields

2022 pdf:
> DATAFILE_AS_OF | Data as of date
> FILING_DATE | System created value: Date when a record was filed with PHMSA DOT
> FILING_DATE (duplicated) | Date Submitted
> REPORT_DATE | System created value: Date when an Initial record was filed with PHMSA DOT
> REPORT_DATE (duplicated) | Initial Date Submitted

pre 2000:
> DOE	|	DATE	|	 	Date record was entered into the database. (YYYYMMDD)
> DOC	|	DATE	|	 	Date record was changed in the database. (YYYYMMDD)

**Comment by e-belfer** [comment]
> ## all the date fields
> 
> 2022 pdf:
> 
> > DATAFILE_AS_OF | Data as of date
> > FILING_DATE | System created value: Date when a record was filed with PHMSA DOT
> > FILING_DATE (duplicated) | Date Submitted
> > REPORT_DATE | System created value: Date when an Initial record was filed with PHMSA DOT
> > REPORT_DATE (duplicated) | Initial Date Submitted
> 
> pre 2000:
> 
> > DOE	|	DATE	|	 	Date record was entered into the database. (YYYYMMDD)
> > DOC	|	DATE	|	 	Date record was changed in the database. (YYYYMMDD)

@cmgosnell Do you read this as DOE = REPORT_DATE? Sounds like DOC would be equivalent to the FILING_DATE only when the filing was a supplemental filing, so not a 1:1. Or should we treat them as 4 slightly different columns?
