### ISSUE TITLE
Nightly build failure 2024-01-24

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#3284]
# Data validation failure
The utility and balancing authority service territories derived from EIA-861 have significantly more records than expected.

* All of the real code changes between `nightly-2024-01-21` and `nightly-2024-01-24` seem to be related to the PHMSA extraction.
* However, the `conda` environment was also re-locked on Monday. Maybe something there changed the behavior of the service territory assets?

```
test/validate/service_territory_test.py::test_minmax_rows[compiled_geometry_balancing_authority_eia861-108436] 
-------------------------------- live log call ---------------------------------
2023-08-15 14:53:49 [    INFO] catalystcoop.pudl.validate:194 compiled_geometry_balancing_authority_eia861: found 112507 rows, expected 108436. Off by 3.754%, allowed margin of 0.000%
FAILED                                                                   [ 99%]
test/validate/service_territory_test.py::test_minmax_rows[compiled_geometry_utility_eia861-237872] 
-------------------------------- live log call ---------------------------------
2023-08-15 14:53:52 [    INFO] catalystcoop.pudl.validate:194 compiled_geometry_utility_eia861: found 247705 rows, expected 237872. Off by 4.134%, allowed margin of 0.000%
```

# Build script success criteria:

* In addition to the above issue, despite the fact that the **build failed** the script seems to think it succeeded in some ways.
* The `nightly` branch was updated.
* The `success` file was created in the output bucket
* The `/nightly` outputs were updated with last night's outputs.
* It seems like we aren't correctly capturing the exit status of the chain of commands in the `run_pudl_etl()` funciton. Maybe we should break them up into individual commands each with their own success variable, and have the function return the AND of all of them?

# Datasette doesn't match?

Curious whether the datasette deployment had taken place given the above combination of failure and perceived success, I counted the rows in the two affected tables, and to my surprise, it matched **neither** the expected or observed row counts above:

```sql
SELECT COUNT(*) FROM out_eia861__compiled_geometry_utilities;
-- 248987
```

```sql
SELECT COUNT(*) FROM out_eia861__compiled_geometry_balancing_authorities;
-- 112853
```

# ETL Logs:
[pudl-etl.log](https://github.com/catalyst-cooperative/pudl/files/14039695/pudl-etl.log)

**Comment by jdangerx** [comment]
I'll note here that the [`pudl_codes_datasources` table](https://data.catalyst.coop/pudl/core_pudl__codes_datasources) does include a `pudl_version` column which appears to point at the right git hash: 
<img width="287" alt="image" src="https://github.com/catalyst-cooperative/pudl/assets/2495794/45460ec0-258f-434f-aa1f-7d02e78fd470">

**Comment by jdangerx** [comment]
I'm surprised that the `pytest ... && touch $PUDL_OUTPUT/success` led to `touch`ing if `pytest` failed...

**Comment by jdangerx** [comment]
I think the logs you're looking at are for the wrong day, actually! 😌  See the timestamp:
```
2023-08-15 14:53:52 [    INFO] catalystcoop.pudl.validate:194 compiled_geometry_utility_eia861: found 247705 rows, expected 237872. Off by 4.134%, allowed margin of 0.000%
```
I can't find any test failures in the `2024-01-24` logs.

**Comment by zaneselvans** [comment]
Okay, so this was just a network hiccup in attempting to publish the data release to the Zenodo Sandbox, and actually everything is materially fine.
