### ISSUE TITLE
Publish rate base table in DB

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/pudl#3310]
## why?
bc we have these cool tables that have now been vetted (via #3534) and they should be accessible in the db

## success?
- rate base table is being published and distributed.
- this table has sufficient but not overwhelming documentation to explain their weirdness. Focus on how a user would use these tables not on how they were built.
- Potential rabbit hole avoid-er: Don't publish the `out_ferc1__detailed_*` tables. Only publish `out_ferc1__yearly_rate_base` 🟢 -> I spun off the detailed table into #3642

## how?

```[tasklist]
### out\_ferc1\_\_yearly\_rate\_base
- [x] make draft schema
- [x] check pks (as asset_checks when needed bc nulls)
- [x] document table
- [x] document new columns
- [x] convert draft schema into real schema
- [x] convert `asset` to sql asset
- [x] migrate full db schema
- [x] add release notes!
```

```[tasklist]
## found oddities
- [x] the column `tags_in_rate_base` shouldn't end up in the rate base table bc == "yes". but we just converted two tags prop checks into asset checks that rely on that column. Need to slurp these checks back into the asset function.
- [x] the pk of the table (which is full of nulls so it can't be a real pk) -> made asset_check instead
```

```[tasklist]
## possible tweaks to make this easier to document
- [x] remove `tags_` prefix? - Idk i think this is fine. its helpful to be able to say "all of these are tags" so i think its okay as is even though its long
- [x] replace the augemented `aggregatable_{dimension_column}` columns with their og counterpart and document in the table description
```

**Comment by aesharpe** [comment]
> remove tags_ prefix? - Idk i think this is fine. its helpful to be able to say "all of these are tags" so i think its okay as is even though its long

I was also sort of thinking this...but it's not a high priority. I think it would help if I understood the difference between these tags and the `xbrl_factoid`s better.
