### ISSUE TITLE
Enable Pandera dtype and validation checks

### ISSUE THREAD

**Issue by jdangerx** [catalyst-cooperative/pudl#3318]
We have all the tools available to us to:

* define dtypes for assets
* define column-based and DF-based validation checks for assets
* run dtype checks & validation checks in Dagster

Let's start using those tools to get better guarantees about our data!

```[tasklist]
## Scope
- [ ] you can define data validation checks in `RESOURCE_METADATA` for persisted assets
- [ ] you can define data validation checks + dtypes as a Pandera schema for un-persisted assets
- [ ] validation checks + dtype checks are run in Dagster for both persisted & un-persisted assets
- [ ] examples of the above are presented to the team!
```

**Comment by bendnorman** [comment]
Can we close this now that https://github.com/catalyst-cooperative/pudl/pull/3282 is merged?

**Comment by jdangerx** [comment]
Yes! We can track the follow-up work in #3412 .
