### ISSUE TITLE
Capture and check test coverage in the merge queue

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#3337]
Now that we are using the merge queue in this repo #3317 it seems like we are no longer getting any feedback about our test coverage, since that can only be generated when the integration tests run, and the test coverage is not currently a required check.

```[tasklist]
- [x] Add `ci-coverage` to required checks to ensure we continue generating test coverage and uploading it to CodeCov.
- [x] Ensure that test coverage associated with `main` is updated. [Seems to be working](https://app.codecov.io/gh/catalyst-cooperative/pudl)
- [x] Add a simple fixed threshold for use in checking whether test coverage is good enough
- [x] Update docs & PR template to direct folks to run `make pytest-coverage` locally before submitting to the merge queue
```

**Comment by jdangerx** [comment]
https://github.com/matplotlib/napari-matplotlib/issues/155 looks like our friend @dstansby ran into something similar before and tried not uploading the coverage from the merge queue branch? Wonder if that worked.

**Comment by zaneselvans** [comment]
Another option would be to use a very simple python test coverage evaluation action to determine whether a PR passes or fails the check, and just use CodeCov as a UI for exploring what's covered and what's not.  For example: [orgoro/coverage](https://github.com/orgoro/coverage)
