### ISSUE TITLE
Simplify the many types of id's

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/pudl#337]
A lot of problems came up for data packaging due to the indexes and auto-incremental ids. We have four types of tables in regards to indexes/id's:
- Tables using SQLAlchemey's auto-id's as primary keys with column name `id` (tons of tables)
- Tables using SQLAlchemey's auto-id's as primary keys with column name `fuel_receipt_id` (1 table)
- Tables w/out an `id` column that don't use the df's index or an auto-incremental id (tons)
- Tables w/ an `id` column that is actually data (5)

I'm thinking of simplifying the tables so there are only two types of tables:
- tables with auto-incremental ids as primary keys
- tables with no auto-incremental ids

This means I need to standardize the name for the auto-incremental id. I'm thinking about just going with `id` for simplicity... but it could be `auto_id` or something more descriptive. If I leave the auto id's as `id`, I'll need to change the 5 tables that use `id` data field to more descriptive names.

**Comment by cmgosnell** [comment]
Does anyone remember why we used `id` (in `plants` tbl) and `plant_id` (in `utility_plant_assn` tbl) and `plant_pudl_id` everywhere else? @swinter2011 @zaneselvans ... I have an urge to change them all to `plant_id_pudl`.

**Comment by zaneselvans** [comment]
The idea was that in a primary key's home table, it would just be called `id`, indicating that it was the primary key for that table, while when it was referenced from another table, it would be given a name that also indicated what table it was coming from. I've seen this pattern in a lot of database-like setups, but I don't think we stuck to it very well, and having the same column be called the same thing everywhere also seems like it would be pretty clear.
