### ISSUE TITLE
Missing county names in plants_entity_eia table

### ISSUE THREAD

**Issue by joshdr83** [catalyst-cooperative/pudl#339]
**Describe the bug**
There appear to be missing county names in the `plants_entity_eia` table that are present in the raw 860 data, sheet: 2___Plant_Y2017.xlsx 

**To Reproduce**
`Select * from plants_entity_eia where plant_id_eia in (6791, 57222, 56522)` (+ about 500 more plants) and the county name come up as `null`, but the counties can be located in the 2___Plant_Y2017.xlsx  workbook.

**Comment by cmgosnell** [comment]
Hey @joshdr83! Can you check out my [response](https://github.com/catalyst-cooperative/pudl/issues/325#issuecomment-508144304) to Brianna in issue #325. This is generally an expected outcome right now. I've been debating whether or not to change our harvesting process to reduce the null fields, but there doesn't seem to be a perfect option to do so.

**Comment by cmgosnell** [comment]
subsumed within Issue #446
