### ISSUE TITLE
Automatically make versioned distribution files read only

### ISSUE THREAD

**Issue by bendnorman** [catalyst-cooperative/pudl#3400]
We should make our versioned distributions (`v2024.02.05`, `v2024.XX.XX`...) read-only so we don't accidentally overwrite or delete them. `stable` and `nightly` don't need to be read-only because they are expected to change on successfully releases and nightly builds.

```[tasklist]
- [x] Modify build script to place a temporary hold on versioned data releases in GCS.
- [ ] Figure out how to place an object lock on the released data in S3.
```

**Comment by zaneselvans** [comment]
Hmm, it looks like [object level retention policies](https://cloud.google.com/storage/docs/using-object-lock#enable-retentions) have to be enabled at the time of bucket creation, and that's not the default.
