### ISSUE TITLE
Make SEC 10K metadata into a structured database

### ISSUE THREAD

**Issue by katie-lamb** [catalyst-cooperative/pudl#3431]
One of the lessons from previous unstructured data extraction projects is the necessity to collect as much metadata as possible, and be able to go from a structured database of metadata to a specific document. Also, we should be able to add our own columns onto the metadata during the extraction process.

We have filer’s name and CIK (unique ID that SEC uses) and all the metadata is currently being saved in the archives as a CSV.

- [x] Create a central database and dump the 10Ks into a cloud bucket
- [x] The metadata seems consistent between all documents, so create a structured table of metadata that we can add columns are
- [x] Set up a way to associate a parent company with its filing and peruse random files to figure out what’s going on

**Comment by katie-lamb** [comment]
Terraform setup in [this PR](https://github.com/catalyst-cooperative/mozilla-sec-eia/pull/2)

**Comment by zschira** [comment]
We now have all of the filings on GCS with a metadata DB, so I'm going to go ahead and close this.
