### ISSUE TITLE
Integrate 2018 FERC Form 1 data

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#344]
The FERC Form 1 data for 2018 has been posted to [their archaic FTP site](ftp://eforms1.ferc.gov/f1allyears/f1_2018.zip), and awaits our tender digital caress with baited breath.

**Comment by swinter2011** [comment]
test comment

**Comment by zaneselvans** [comment]
The new plant and utility IDs for FERC Form 1 are now being generated (by a notebook in devtools), and all the new required string cleaning maps should be available. However, FERC 1 can't be pulled into PUDL without the ID mapping having taken place, so #428 to happen before this can be closed.

**Comment by zaneselvans** [comment]
I went ahead and categorized all of the unrecognized freeform strings in the string cleaning dictionaries within `constants.py` so I *think* the only thing that has to happen for this to be closed is the ID mapping in #428, though perhaps we'll discover some new FERC 1 nonsense once the data is actually pulled into PUDL.
