### ISSUE TITLE
compression of data package resources causing validation errors

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/pudl#352]
Hey @roll! We were thinking about compressing one of our resources and I got it all working except when running `goodtables.validate` I'm getting one error. We used the I tried removing the compression and 

We used the [patterns for compression](http://frictionlessdata.io/specs/patterns/) - the path in the metadata looks like this:
`"path": [ "data/hourly_emissions_epacems_2016.csv.gz",
               "data/hourly_emissions_epacems_2017.csv.gz" ], `

Here is the error I'm getting.. Is this an expected behavior? Or are compressed files supposed to be "valid" resources and I'm just doing something wrong. Let me know!
```{'datapackage': '/Users/christinagosnell/code/pudl/results/datapackage/epacems_eia860/datapackage.json',
   'time': 0.15,
   'valid': False,
   'error-count': 1,
   'row-count': 0,
   'source': ['/Users/christinagosnell/code/pudl/results/datapackage/epacems_eia860/data/hourly_emissions_epacems_2016.csv.gz',  '/Users/christinagosnell/code/pudl/results/datapackage/epacems_eia860/data/hourly_emissions_epacems_2017.csv.gz'],
   'schema': 'table-schema',
   'errors': [{'code': 'source-error',
     'message': "'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte",
     'message-data': {}}]}],

**Comment by roll** [comment]
Hi @cmgosnell,

I've reviewed the whole stack and figured out that support for multi-parting and compression for the same resource is blocked by https://github.com/frictionlessdata/tabulator-py/issues/267, for now.

We can consider implementing it later but as, for now, our primary plan is to use a resource per partition I think this issue can be closed.

**Comment by cmgosnell** [comment]
everything is working for this yay
