### ISSUE TITLE
Flipped starting/ending balance in out_ferc1_yearly_other_regulatory_liabilities_sched278

### ISSUE THREAD

**Issue by jrea-rmi** [catalyst-cooperative/pudl#3592]
### Describe the bug
out_ferc1_yearly_other_regulatory_liabilities_sched278 seems to have values in the opposite columns of what they should be in years 2020 and earlier. I expect the ending_balance from one year to be the same as the starting_balance in the next year. But I see the opposite columns match.

### Bug Severity
How badly is this bug affecting you?
 - **Medium:** With some effort, I can work around the bug.

### To Reproduce
The specific cases I looked at were:
Pacific gas & electric (utility_id_ferc1 183), description = TOTAL
Pacific gas & electric (utility_id_ferc1 183), description = REGULATORY LIABILITY RETIREM
Alabama Power Co (utility_id_ferc1 294), description = ASC 410-20 (ARO) or ASC  410-20 (ARO)

### Expected behavior
values in ending_balance should be in the starting_balance column, and vice versa, for years 2020 and earlier.

### Software Environment?
.csv downloaded from datasette today.

### Additional context
N/A

**Comment by yolandazzz13** [comment]
Hi, I'm a student at University of Michigan who's currently working on a final project in a software engineering course that expect us to make contributions to open source github projects. I wonder if you can assign me to this issue? @catalyst-cooperative/com-dev Also , I was able to locate the source file it would be awesome if I can be told how the source code generate the datasets. Thank you in advance!

**Comment by yolandazzz13** [comment]
Ok I think I've got this issue resolved. I'm going to submit a PR. Is there anyone that can assign this issue to me? Please feel free to contact me or reply if anyone on the developing team wants to review my solution. @catalyst-cooperative/com-dev @jrea-rmi
