### ISSUE TITLE
Request: change EPA CEMS variable descriptions

### ISSUE THREAD

**Issue by karldw** [catalyst-cooperative/pudl#360]
Below I've listed the current variable descriptions for each of the EPA CEMS variables, as well as my proposed change. I think these changes are helpful because they're sometimes more correct (e.g. `plant_id_eia` vs `facility_id`) or are more precise about units.

For some variables, particularly `steam_load_1000_lbs`, `facility_id`, and `unit_id_epa`, I'm a little unsure what to write.

CC: @cmgosnell and @gschivley 

- `id`
    - Current: PUDL-issued surrogate key.
    - Proposed: Unique PUDL-issued plant-unit-hour key (may change between PUDL versions).
- `state`
    - Current: State the plant is located in.
    - Proposed: _no change_
- `plant_id_eia`
    - Current: EIA Plant Identification number. One to five digit numeric.
    - Proposed: The unique six-digit facility identification number, also called an ORISPL, assigned by the Energy Information Administration.
- `unitid`
    - Current: Facility-specific unit id (e.g. Unit 4)
    - Proposed: _no change_
- `operating_datetime_utc`
    - Current: Date and time measurement began.
    - Proposed: Date and time measurement began (UTC).
- `operating_time_hours`
    - Current: Length of time interval measured.
    - Proposed: _no change_
- `gross_load_mw`
    - Current: Power delivered during time interval measured.
    - Proposed: Average power in megawatts delivered during time interval measured.
- `steam_load_1000_lbs`
    - Current: Total steam pressure produced by a unit or source in any calendar year (or other specified time period) produced by combusting a given heat input of fuel.
    - Proposed: Not sure, but should be specific to the hour, not the year
- `so2_mass_lbs`
    - Current: Sulfur dioxide emissions in pounds.
    - Proposed: _no change_
- `so2_mass_measurement_code`
    - Current: Identifies whether the reported value of emissions was measured, calculated, or measured and substitute.
    - Proposed: _no change_
- `nox_rate_lbs_mmbtu`
    - Current: The rate at which NOx in was emitted in pounds per million BTU.
    - Proposed: _no change_
- `nox_rate_measurement_code`
    - Current: Identifies whether the reported value of emissions was measured, calculated, or measured and substitute.
    - Proposed: _no change_
- `nox_mass_lbs`
    - Current: Nitrogen oxide emissions in pounds.
    - Proposed: NOx emissions in pounds.
- `nox_mass_measurement_code`
    - Current: Identifies whether the reported value of emissions was measured, calculated, or measured and substitute.
    - Proposed: _no change_
- `co2_mass_tons`
    - Current: Carbon dioxide emissions in short tons.
    - Proposed: _no change_
- `co2_mass_measurement_code`
    - Current: Identifies whether the reported value of emissions was measured, calculated, or measured and substitute.
    - Proposed: _no change_
- `heat_content_mmbtu`
    - Current: The measure of utilization that is calculated by multiplying the quantity of fuel by the fuel's heat content.
    - Proposed: The energy contained in fuel burned, measured in million BTU.
- `facility_id`
    - Current: The unique six-digit facility identification number, also called an ORISPL, assigned by the Energy Information Administration.
    - Proposed: New EPA plant ID. 
- `unit_id_epa`
    - Current: Unique EPA identifier for each unit at a facility.
    - Proposed: New EPA unit ID.

**Comment by cmgosnell** [comment]
hey @karldw ! Lots of these changes look great to me. I'm also unsure about those three fields, but for implementation you can to add these directly into the models for now on the master branch. I'm able to regenerate the metadata for the data packaging based on the current state of the database and I'll probably keep that functionality until the actual switch over date... which is probably still two weeks out. Until then, you can change the comments in models and after that you'll be able to modify the metadata in `pudl/src/pudl/package_data/meta/data_package/datapackge.json`.

**Comment by gschivley** [comment]
> gross_load_mw
Current: Power delivered during time interval measured.
Proposed: Average power in megawatts delivered during time interval measured.

*delivered* might imply to the grid or a final consumer. Maybe *Average gross power in megawatts produced during the time interval measured*?


>heat_content_mmbtu
Current: The measure of utilization that is calculated by multiplying the quantity of fuel by the fuel's heat content.
Proposed: The energy contained in fuel burned, measured in million BTU.

Worth noting that it is calculated using CO2 measurements rather than measuring fuel inputs?


>facility_id
Current: The unique six-digit facility identification number, also called an ORISPL, assigned by the Energy Information Administration.
Proposed: New EPA plant ID.
unit_id_epa
Current: Unique EPA identifier for each unit at a facility.
Proposed: New EPA unit ID.

Does new mean that they were created in PUDL?


> plant_id_eia
Current: EIA Plant Identification number. One to five digit numeric.
Proposed: The unique six-digit facility identification number, also called an ORISPL, assigned by the Energy Information Administration.

Worth noting that in rare cases the plant id is different in EIA data?

**Comment by karldw** [comment]
I didn't know heat content was calculated from CO2. That's interesting.


---------

> > facility_id
> > Proposed: New EPA unit ID.

> Does new mean that they were created in PUDL?

No, they're from EPA, not generated by PUDL. The "new" part of that was only because they don't go all the way back to the oldest CEMS data. How about "EPA plant ID" and "EPA unit ID"?

**Comment by gschivley** [comment]
![image](https://user-images.githubusercontent.com/10373332/62464486-bef24980-b75a-11e9-9104-2e560a7d0d33.png)

From the [plain english guide to Part 75.](https://www.epa.gov/sites/production/files/2015-05/documents/plain_english_guide_to_the_part_75_rule.pdf). F-factors are provided in Appendix F of Part 75.

**Comment by cmgosnell** [comment]
Hey @karldw! I started pulling these in changes into the [metadata](https://github.com/catalyst-cooperative/pudl/commit/741d98d719885ee17a4a5694223865e517bbe772). I embellished a bit on the `facility_id` and the `unit_id_epa` to make them more descriptive, but you know these fields better than I do so feel free to change them.

**Comment by karldw** [comment]
Hey @cmgosnell, I didn't write a PR! I think the `facility_id` and `unit_id_epa` (called `FAC_ID` and `UNIT_ID` in the original EPA CSV) are not assigned by EIA. I assume they're assigned by EPA, though I'm not sure what system they refer to. Would it be helpful if I made a PR with this change?

**Comment by karldw** [comment]
Maybe worth noting: there are a lot of different plant ID systems. For example, here's a listing for the Rathdrum plant in Idaho: https://ofmpub.epa.gov/enviro/fii_query_detail.disp_program_facility?pgm_sys_acrnm_in=EIA-860&pgm_sys_id_in=7456
The corresponding `facility_id` is 966 with unit IDs 3118 and 3119.

**Comment by zaneselvans** [comment]
Hey some of these changes seem to have not come through for some reason so I'm going to re-open this just to keep track of the need to update them....
