### ISSUE TITLE
Remove pudl postgres database!!

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/pudl#363]
Once we are at the point of converting over fully to data packages, there will be lots of things we need to get rid of which reference the database that will no longer be relevant...

- [x] models! all of them...
- [x] all the functions tagged with `Remove upon removal of pudl_db` todo's
- [x] postgres dependencies
- [x] `init.py`
  - [x] the db connections
  - [x] everything else!
- [x] a bunch of tests.
- [x] any `keep_csv` reference

I'm sure there is more...

**Comment by cmgosnell** [comment]
Hey @karldw! are you using the views for CEMS? It looks like they can be easily converted away from using the models' metadata definition but I figured I should check in with you about it before spending the time converting them.

**Comment by karldw** [comment]
I'm not! I've moved to an all-parquet workflow. Thanks for checking!
(I agree that it wouldn't be too hard to convert, but there's no need.)
