### ISSUE TITLE
Don't deploy outputs when using `workflow_dispatch` trigger on `main`

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#3643]
# Overview

Due to some faulty logic in our altogether too complex conditionals for deciding when/where to deploy build outputs, running a `workflow_dispatch` deployment on `main` results in the outputs being deployed to the following paths:

```
s3://pudl.catalyst.coop/main/
gs://pudl.catalyst.coop/main/
```

```[tasklist]
- [x] Simplify the nightly/stable/workflow_dispatch logic as outlined below
- [x] Attempt to create a Zenodo sandbox data release for workflow_dispatch builds
- [x] Stop deploying to parquet.catalyst.coop since we publish all parquet files now
- [x] Use gcloud instead of AWS CLI since it can manage S3 now
```

**Comment by jdangerx** [comment]
Punting this until next sprint since we're not focusing on the build script refactor/quality for this sprint.

**Comment by e-belfer** [comment]
Putting this into next sprint, since we'll be doing yet another release in November and this seems to be a problem again.
