### ISSUE TITLE
Update XBRL extraction to handle multiple taxonomies per year

### ISSUE THREAD

**Issue by jdangerx** [catalyst-cooperative/pudl#3650]
### Overview

Once catalyst-cooperative/pudl-archiver#349 is done, we have to actually use all that fancy metadata to extract the filings correctly!

### Success criteria
* [ ] filings extracted using the correct taxonomies
* [ ] all FERC 1 transforms execute without errors, though they probably don't pass validation checks.

```[tasklist]
### Next steps
* [ ] read taxonomy and filename from the metadata
* [ ] chunk extraction based on which taxonomy is being used
```

**Comment by zaneselvans** [comment]
I think this should probably get bumped to High or Urgent priority so that we can unblock work on the new year of FERC Form 1 data.

**Comment by cmgosnell** [comment]
hey @jdangerx and/or @zschira ! is this issue about the getting the xbrl data into a sqlite db side of extraction? or is it the post-sqlite db side of extraction (which iirc is basically just a read_sql step).

**Comment by jdangerx** [comment]
This is about the XBRL -> SQLite side - basically "use the correct taxonomy to turn this specific filing into tabular data."
