### ISSUE TITLE
Copy CSVs from tables that show up in multiple data packages (but same dp bundle)

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/pudl#366]
In one bundle of data packages, you can add one data set to multiple data packages. What if we enabled the copying of the CSVs output from one data package into another data package w/o having to re-run the ETL process?

The best candidate for this would be EIA 860. 860 can be in a data package with just EIA 860 and 923 and also needs to be in the data package with EPA CEMS. If we enabled the use of the output CSVs, we wouldn't have to generate 860 and 923 twice.

I'm still unsure if there are unintended consequences of doing this... or more generally whether or not this is a good idea. If we do implement this, it would probably be good to ensure that the input parameters like tables and years are exactly the same before copying.

**Comment by zaneselvans** [comment]
No longer relevant with direct SQLite outputs.
