### ISSUE TITLE
Fix remaining flake8 linter errors and enable in tox

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#372]
There are still ~100 linter errors coming from `flake8` when it's run on the entire repository, so it would cause the builds to fail if it were turned on in Travis. We need to chase them down and either fix them or exempt them with # noqa pragmas, and enable the flake8 linter in the Travis builds so syntax and style issues can be caught even if someone submits code that hasn't been de-linted.

**Comment by gschivley** [comment]
Just run Black on everything ;)

**Comment by zaneselvans** [comment]
You know, I *wanted* to like black, and maybe if we'd been using it from the beginning it would have been fine, but we've been "beautifying" in Atom with `autopep8` and black changed *a lot* of stuff, and not in ways I was really thrilled with.

**Comment by gschivley** [comment]
I never used autopep8 and started using a few of black's rules on my own. Double quotes are the biggest switch for me.

I do agree that changing over in an existing project is tough though. Lots of commits everywhere just for a formatting change.
