### ISSUE TITLE
Include `generator_operating_date` in the `core_eia860m__changelog_generators` table

### ISSUE THREAD

**Issue by arengel** [catalyst-cooperative/pudl#3722]
**Is your feature request related to a problem? Please describe.**
In some of our models we use monthly 860 data to define the set of generators since it has all the columns we need and reflects the best available data on planned retirements and additions. We'd like to be able to use `core_eia860m__changelog_generators`  for this purpose but it is missing the `generator_operating_date` which makes this inconvenient.

**Describe the solution you'd like**
I'd like to have the `generator_operating_date` as reported in 860m included in the `core_eia860m__changelog_generators` table.

**Describe alternatives you've considered**
We could merge on that single column from `_out_eia__yearly_generators` but that's less convenient and it's not clear if those dates are actually the ones, or the same as the ones reported in 860m.

**Comment by e-belfer** [comment]
@arengel This should now be fixed in the nightly builds.
