### ISSUE TITLE
Write up documentation on how to use superset

### ISSUE THREAD

**Issue by bendnorman** [catalyst-cooperative/pudl#3749]
Create a superset dashboard that is mostly a markdown file that describes how to use PUDL superset. It should explain how to use SQL Lab, link to our data dictionary and which superset features we're not supporting right now (creating personal dashboards and charts).

- [x] Explain the 100k row limit and point to other data access modes
- [x] Link to data dictionary
- [x] Provide a sample SQL query
- [x] Point to any relevant superset tutorial docs

**Comment by bendnorman** [comment]
@e-belfer do you think we should include how to create charts in our landing dashboard for now?

**Comment by e-belfer** [comment]
@bendnorman Do you have any tutorial documents you like? The ones I've seen are mostly focused on deployment, not usage

**Comment by bendnorman** [comment]
I added a couple of preset chart tutorials to the dashboard.

**Comment by bendnorman** [comment]
The [initial iteration](https://pudl-superset-xl7xwcpe2a-uc.a.run.app/superset/dashboard/superset-intro/?native_filters_key=ZxmvhehzIkaDMVWwX3CZ_BRpuNz7t0lsgLgtkWJcRkm6IDbUNvJ2QzYuGFQozj-l) of this is complete!
