### ISSUE TITLE
Make Excel & CSV column mapping warnings into errors

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#3757]
Occasionally spreadsheet headers change in the EIA inputs, and currently this generates a warning, but not an error... but it really needs to be an error, because if we don't address it, we end up dropping a bunch of data that actually exists.  Sometimes we catch these issues when updating the data, but sometimes we do not!

See the [`xlsx-column-errors`](https://github.com/catalyst-cooperative/pudl/tree/xlsx-column-errors) branch where these errors are highlighted.

* The change from logging a warning to raising an error can be made in the base Extractor class that we use for all of our spreadsheet based data sources.
* There will need to be some (per data source?) special cases to ignore -- e.g. in the EIA-923 there's an "Early Release" warning that shows up as a column header, but is really just meant to flag that the whole spreadsheet is Early Release data.
* Will potentially affect EIA 176, 860, 860M, 861, and 923, as well as PHSMA data.

# Identified Errors

## EIA-176/191/757a
* All good!

## EIA-860/860M
* All good!

## EIA-861
* All good!

## EIA-923
* byproduct_expenses_and_revenues/2009:
  *  Extra columns: `unnamed_30`
* boiler_fuel/2023
  * Extra columns: `early_release_data_july_2024_not_fully_edited_use_with_caution_do_not_aggregate_to_state_regional_or_national_totals`

## PHMSA Natural Gas
* yearly_transmission_gathering_preparer_certification/2000: Expected columns not found in extracted table:
  * `preparer_telephone`
  * `preparer_name`
* yearly_distribution/(2004-2007): Extra columns found in extracted table:
  * `unnamed_227`
* yearly_distribution/2009: Extra columns found in extracted table:
  * {'unnamed_233', 'unnamed_261', 'unnamed_243', 'unnamed_240', 'unnamed_255', 'unnamed_260', 'unnamed_242', 'unnamed_249', 'unnamed_247', 'unnamed_252', 'unnamed_250', 'unnamed_259', 'unnamed_235', 'unnamed_241', 'unnamed_254', 'unnamed_253', 'unnamed_239', 'unnamed_257', 'unnamed_248', 'unnamed_244', 'unnamed_227', 'unnamed_256', 'unnamed_232', 'unnamed_236', 'unnamed_263', 'unnamed_237', 'unnamed_229', 'unnamed_238', 'unnamed_262', 'unnamed_228', 'unnamed_245', 'unnamed_251', 'unnamed_231', 'unnamed_246', 'unnamed_230', 'unnamed_258', 'unnamed_234'}
* yearly_gathering_pipe_miles_by_nps/(2010-2022): Expected columns not found in extracted table: 
  * `onshore_type_a_gathering_pipe_other_size_miles`
  * `onshore_type_b_gathering_pipe_other_size_miles`
  * `offshore_gathering_pipe_other_size_miles`

```[tasklist]
### Tasks
- [x] fix eia923
- [ ] fix phmsa
```

**Comment by e-belfer** [comment]
To my memory (but worth confirming):
- the "other_size_miles" are columns that are in the form, but not in the actual data. We kept them in case they were ever reported. - the "unnamed" columns are instances where unstructured data spills over from its column into adjacent columns (usually a handful of rows per dataset).
