### ISSUE TITLE
Solicit feedback about Superset from Catalyst Cats

### ISSUE THREAD

**Issue by bendnorman** [catalyst-cooperative/pudl#3775]
We want to solicit feedback from catalyst cats on the UX before we release this to the public. We should create a list of tasks and UX questions for Catalyst Cats to complete.  The goal here is to collect points of friction in the setup and use.

I started to draft the questions [here](https://docs.google.com/document/d/1tj-aVwGSh2KhExRFV9AtewRAbENtePHp3iTvykXVGUE/edit#heading=h.pi4t8bsltuxi).

**Comment by bendnorman** [comment]
I created a [Google Form to collect responses](https://docs.google.com/forms/d/1B9b7BiabtwmI8DjEpHwuTcGPo58u1JOXJeqX26GS3kk/edit).

**Comment by jdangerx** [comment]
@bendnorman do you think this is done? Or should we make a list of the main themes of the feedback / make a bunch of issues about it before we close this issue?

**Comment by bendnorman** [comment]
I'm almost done with [a summary](https://docs.google.com/document/d/1jHD5Vff-0dKx94tkddRziznaTv6YlCu1-JAedHTp__s/edit#heading=h.rkcp1k3va1ls) of the feedback. I think we can close it once we prioritize the issues that came up in the feedback. It'd be helpful to talk through the feedback with one or two inframundo folks to figure out next steps.

**Comment by bendnorman** [comment]
The summary is complete and we've done some follow up in #3832 so I'm going to close this.
