### ISSUE TITLE
add the dataset table into the datapackage generation

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/pudl#379]
generate it for each dp.. and somehow merge the table when flattening dp's..

**Comment by cmgosnell** [comment]
we've decided to get rid of the `datasets` table. All it included was a True/False for each of the data sets, which indicated whether or not the data set was in the PUDL database.

We decided this for two main reasons:
- this info is readily available in the datapackages (in which csv's exist and in the metadata)
- the new PUDL sqlite db will not have empty tables like the postgres db did. If a data set wasn't included in the datapackage that is being converted to sqlite, that data set's tables just won't exist. Because of this, checking if a table exists at all will be sufficient to tell whether or not there should be data in it.

I'm not sure if anyone was actually using this table (@karldw @gschivley ??) so please respond if this will be a big pain for you.

**Comment by karldw** [comment]
I wasn't using it!

**Comment by gschivley** [comment]
Not using it either.

**Comment by cmgosnell** [comment]
wahoo! goodbye tiny table.
