### ISSUE TITLE
Ensure epacems_to_parquet clobbers files appropriately

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#384]
The `epacems_to_parquet` script currently uses a hard-coded path for its output.  If you run the script more than once you get duplicate output parquet files -- which are named with unique hashes. This means you'll end up getting duplicated data in the parquet dataset. Instead, the lowest level directory of the dataset partitioning should be getting clobbered whenever the script is re-run.

**Comment by zaneselvans** [comment]
By "lowest level" here I mean, the deepest directory in the parquet file partitioning hierarchy. Parquet datasets (which are collections of parquet files) use the directory names to partition so at the top level you might have directories named `year=2015` and `year=2016` And inside each of those directories you'd have more named like `state=CA` and `state=CO` etc.  And only inside those "lowest level" (state) directories, do you find the actual files, which contain the data pertaining to that year and state.

**Comment by karldw** [comment]
Tangentially related to the issue above, and #385, what kind of partition flexibility do you want for the CEMS data? 

1. If partitions are changeable by the user, shouldn't the `epacems_to_parquet` script delete everything under `parquet/epacems/`? Currently the `epacems_to_parquet` function takes a `partition_cols` argument, but it can't be set on the command line.
2. All of the existing partitioning has been by year and state. If `partition_cols` is set to something else, say `nox_mass_measurement_code`, the parquet files will end up with partitions of  `nox_mass_measurement_code` _for every year and state._ (Each file is assigned a random name, so at least they won't overwrite one another.)

I think the solution here is probably to say "we hard-code that the partitions are by year and state, but you can call dask's [`reset_index`](https://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.DataFrame.reset_index) if you want something else for your data analysis".

**Comment by zaneselvans** [comment]
Hmm, yeah those other partitions don't really make sense. I was imagining that it would be good to allow partitioning by either state or year or both, because I don't really know what file size is best for the parallel reads to speed things up, and for the data to easily fit in memory depending on the machine, and having it splittable in those two ways gives 3 options. And it seems like people often only care about using a subset of the data in time or space.

**Comment by cmgosnell** [comment]
I'm leaning towards wanting to only partition by state and year. It seems like these are the options that will work the best and as Karl said, users can re-partition things as they see fit.

I also think wiping the higher level `parquet/epacems` directory is the way to go. That way there is no possibility for having leftover files. In the lower-level directory option, if you were only trying to get 2017 for a few states, would there be leftover 2016 subdirectories? That seems messy and it sounds like a bad idea to have some parquet files hanging around from one run and some from another. With the new process of this function pulling directly from already made data packages, it doesn't take too long so wiping the whole thing with a `clobber` option seems like a good option.
