### ISSUE TITLE
Make superset dashboard improvements for user testing

### ISSUE THREAD

**Issue by bendnorman** [catalyst-cooperative/pudl#3867]
Before we do user testing we need to make a few improvements. We'll check in on this work after 5 hours.

```[tasklist]
### High Priority
- [x] Rework welcome dashboard (see comment below)
- [x] PIck 5 tables to create Table Dashboards for. Make sure PK and filter columns are on the far left side of the table. Pick a variety of table shapes and sources.
- [x] Add a description of the table and and explantion of how to download the data as a csv
- [x] Allocate minimum amount of Cloud Run resource to improve performance. What's our benchmark? What are we willing to pay?
- [x] Clean up permission to make sure new users dont see all our superset junk
- [x] Test permissions once we've made all these improvements
- [x] Restore PUDL logo to top-left
```

```[tasklist]
### Bonus
- [x] Is it possible to have a site tour pop up on superset? - Possibly by embedding it into a react app, but I don't think this is going to be trivial unless I'm missing something.
- [x] Can we save SQL Queries - Yes! Can we make them visible by default to new users? - Not obvious.
- [ ] Get rid of the bar for numeric fields in table charts
- [ ] Figure out how redirect or emphasize the welcome dashboard
- [ ] Figure out if we can spruce up the auth0 text
- [ ] Customize the home page - e.g., https://medium.com/towards-data-engineering/customize-apache-superset-home-page-to-fit-any-html-block-85f8d4b58419
```

**Comment by bendnorman** [comment]
For the welcome dashboard, we want to:
- generally have less text
- Have people look at data and interact with the data ASAP. Something like a quickstart guide
- Explain the three different methods for interaction with the data on superset: table dashboard, creating charts and SQL lab

The flow for welcome dashboard improvements:
- Have a couple of sentences about what PUDL and Superset are
- Link to one of the Table Dashboards. This dashboard will explain how to filter and download data
- Maybe a section that goes into more detail about the table dashboards
- Section about how to find the data you need in the data dictionary
- Section on how to create charts
- Section on how to use SQL Lab
- FAQ

We can divide these sections up by using tabs.

**Comment by bendnorman** [comment]
Ugh, some very frustrating findings while trying to iron out the permissions for user test. When you give a user permission to a datasource, it gives them read access to all the datasets, charts and dashboards that are derived from the datasource including ones made by other users :/ This poses some UX and privacy concerns for us.

**UX:** If users can see everything built off PUDL it will get difficult to navigate the UI. You can filter dashboards and charts by owner. We could tell users to filter for charts owned by themselves and an admin account that is responsible for creating all the default PUDL charts and dashboards. Superset does [expose](https://github.com/apache/superset/blob/0fdcd8b27e6d6ba70f8f38b4a033c61555af92bd/superset/config.py#L1830-L1849) a way to restrict the owners that appear in the filter dropdowns however I don't think it actually restricts the dashboards and charts you see when the lists are unfiltered.

**Privacy:** all users' first and last names will be available to anyone who registers.

## Solutions?
- Just live with it? We could encourage people to filter for dashboards created by us and themselves but this isn't ideal from a UX perspective. Maybe people would be comfortable with their name being out there? Maybe having charts and dashboards public amongst registered users could actually serve as helpful examples and knowledge sharing? Also, the views that list dashboards, charts and datasets might not be the most intuitive method for navigating PUDL data. I think treating the [PUDL Tables tab](https://superset.catalyst.coop/superset/dashboard/p/R4P912NKv1G/) of the welcome dashboard feels more intuitive anyway.
- Dig into the superset code and figure out how to hide other dashboards, charts and datasets via the UI or in the actual permissions system.
- It looks like superset is considering [redesigning its permissions system](https://github.com/apache/superset/issues/28377) to allow for more granular control but there isn't much movement on it.

**Comment by zaneselvans** [comment]
Hmm, this is unfortunate. How do larger organizations deal with this? Letting everybody see everything all the time seems like chaos?

Only providing access to dashboards seems like we'd be hiding a lot of functionality -- not the functionality we want the CSV folks to see maybe, but still a lot of power and flexibility I think we'd been hoping to expose for folks that want it. It would also mean that we'd only be able to roll out access piecemeal, as we build out appropriate dashboards that eventually come to cover all of PUDL.

My intuition is that it's probably best to make it clear that this is all publicly visible, and do our best to use the UI, tagging, or whatever other organizational tools are available to us to provide direction to the best resources.

Separately, I've wondered whether we might be able to offer public access -- with everything you create being visible to everyone else -- as the free option, and then offer the ability to create private dashboards, saved queries, maybe access to other non-PUDL data? etc. as a paid option.

**Comment by zaneselvans** [comment]
Even more separately, I've also been wondering whether there's an *extremely* simple way that we could provide an in-browser interface that can be pointed at the URL of a Parquet file in S3, display its metadata, and provide a barebones GUI in the vein of Datasette for folks to build a `SELECT stuff FROM url WHERE whatever` and click a "Download CSV" button -- but have the work of translating the stream of Arrow data from the S3 Parquet file into that CSV be done on the client side, in the browser, so we don't actually have to run any service and can just use the free S3 bucket data.

As an added benefit... this would make every publicly visible Parquet file on the internet accessible to CSV users... which would also include all the datasets at Hugging Face, and a bunch of other stuff in the AWS Open Data Registry.

Some suggestions from the Hive Mind included:

* https://reflex.dev/docs/getting-started/introduction/
* https://perspective.finos.org/
* https://www.npmjs.com/package/@duckdb/duckdb-wasm

**Comment by jdangerx** [comment]
I think "just live with it" is probably OK... we can tell people not to publish things unless they want to have them be public.

> Even more separately, I've also been wondering whether there's an extremely simple way that we could provide an in-browser interface that can be pointed at the URL of a Parquet file in S3, display its metadata, and provide a barebones GUI in the vein of Datasette for folks to build a SELECT stuff FROM url WHERE whatever and click a "Download CSV" button -- but have the work of translating the stream of Arrow data from the S3 Parquet file into that CSV be done on the client side, in the browser, so we don't actually have to run any service and can just use the free S3 bucket data.

This really captures the imagination! It gives us the option for a nice non-SQL way to filter & download data, and have a (searchable) data dictionary built into the tool, and maybe people can still run SQL queries if they want.

But, if we want user authentication and metrics, we'd need to write our own (fairly straightforward) web server. Which we'd then have to maintain as well as operate.

Though if we are OK with just getting metrics off of S3 downloads and forgo user email tracking, we could just point a frontend-only app at S3 and call it a day. Get rid of our operational burden.

I'm still open to the idea of building our own tool, but I'm wary of spending our time spinning our wheels on this decision.

I think our choices are:

* stick with stock Superset
  * Pros: this could be the easiest way to getting our data in users' hands.
  * Cons: if we have to build up a web of hacks to get the functionality users need on top of stock superset, that could be a lot of work: interacting with Superset's API, forcing people into "dashboards", etc.
* maintain a fork of Superset
  * pros: this is an easy way to transition from stock Superset to something where we can hack some bigger changes in: data dictionary, CSV downloads, etc.
  * cons: have to keep following upstream, superset is a big app that's kind of hard to learn to change; maybe some of our needs don't fit with Superset's core design. 
* write our own app
  * pros: it seems like we could more easily focus on the "I need something to shove into Excel" use case; app could be simpler than Superset
  * cons: now we have to maintain an app as well as operate it; hard to migrate from Superset if users have built lots of data visualizations there already.

Given the amount of roadblocks / compromises with Superset so far, it might be worth spending some time prototyping a non-Superset tool separately... which I guess was the original POSE plan anyways.

**Comment by e-belfer** [comment]
Given that we're on the cusp of actually testing out this tool, I'd like to just ask our users how they feel about this and whether it's a dealbreaker for them when we do the tests, rather than assuming it will be. I don't think mocking up another option is a bad idea at all, but I would like to wait until we see how people respond to our current set-up.

**Comment by jdangerx** [comment]
Yeah, agree that we should do any additional frontend stuff *after* the first user calls!

**Comment by e-belfer** [comment]
I'm moving the remaining bonus items to #3908 and closing this. Everything absolutely crucial to address prior to user testing has been addressed.
