### ISSUE TITLE
Investigate less zealous removal of NA values during f1_fuel import

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#39]
After the fuel and fuel_unit strings are cleaned up in the f1_fuel import, any record which contains any NA values is dropped, before the DataFrame is pulled into the PUDL DB. In some cases, this means we lose some data. E.g. some utilities only report their mmbtu/kWh numbers on a separate "Total" line. We should check and see whether there's a less destructive way we can deal with these leftover records.

**Comment by swinter2011** [comment]
test comment sync 3

**Comment by zaneselvans** [comment]
@katie-lamb Ah, we've had this issue for a whiiiiiiile.

**Comment by zaneselvans** [comment]
I think this was finally addressed in the XBRL / FERC 1 refactor. #1574
