### ISSUE TITLE
Make asset checks run during integration tests

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#3928]
## Overview

Asset check failures do not appear to get run or be treated as blocking when run as part of the integration tests.

I swear @jdangerx already tackled this in #3687 but it seems to be back from the dead?

I verified this by running the VCE RARE subset of the DAG using the `fast_etl` job in the Dagster UI (getting a failure) while the integration tests in the merge-queue requirements / local integration tests have been passing.

**Note:** The asset checks not running during tests is driving down our test coverage.  In #3959 there's a significant amount of asset checking code, and as a result it dropped the test coverage below the required threshold. The required threshold has been temporarily reduced, but this will only get worse as we refactor the data validation and bring them into the main ETL.

```[tasklist]
- [ ] Figure out why asset checks are not running in tests (again)
- [ ] Verify that the VCE row count check fails in the integration tests.
- [ ] Fix VCE row-counts check to close out #3926
- [ ] After it's fixed, bump required test coverage back up to 92.7%
```

**Comment by jdangerx** [comment]
Looks like we have two failing asset checks when running `etl_fast` that block #3990 from getting merged:

* `core_ferc714__yearly_planning_area_demand_forecast` seems to fail the `_check` pandera schema check - @cmgosnell do you have bandwidth to look into this?
* `out_vcerare__hourly_available_capacity_factor`'s `check_rows` fails - that's already tracked in #3926 . @aesharpe or maybe @zschira do you have bandwidth for this one?

**Comment by cmgosnell** [comment]
I can take a look at the 714 fail. I will try to get to it today but it might be tomorrow.
