### ISSUE TITLE
allowing for compression of all tables

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/pudl#395]
Right now really only `hourly_emissions_epacems` is set up to be stored as a compressed file in the datapackages. This is done in the load step and is a special case that is only used for this table.

If we were to generalize it, I can imagine putting compression information inside of the datapackage settings in the yml file that generates the bundle of datapackages. Right now the load step does not need any of the datapackaging settings, so we'd need to pass those through. I'd imagine we could add a `compression` dictionary to either the dataset specific info or the datapackage. It would be good to include compression into the parameter validation  process to double check if the tables you include in the settings for compression are included in the settings. We'd probably want the compression to work like the partitions work so we'd want something like `pudl.load.metadata.compile_partitions` and whenever a table needs to be compressed... we compress it in the load step.

**Comment by zaneselvans** [comment]
No longer relevant with removal of datapackage outputs.
