### ISSUE TITLE
Integrate 2018 EIA860 data

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#396]
The EIA has released the official 2018 data for [Form 860](https://www.eia.gov/electricity/data/eia860/), so we need to integrate it.

**Comment by briannacote** [comment]
Hi there! I have a super basic question comment here. Are we able to use 2018 EIA 860 and EIA 923 data yet? I get the following error when I try so perhaps my software is out of date?

<img width="860" alt="Screen Shot 2019-12-06 at 3 51 51 PM" src="https://user-images.githubusercontent.com/50969585/70361929-7c439980-1840-11ea-81ed-9c1c6d7d11ce.png">

**Comment by zaneselvans** [comment]
Hi yes! It's been integrated into the codebase but hasn't been released yet. We've been sidetracked with customer contract work. If you're installing from the github repo, you can pull the latest version and it should work.  If you're installing from `conda`/`pip` then it'll be a little while before we get it released.

**Comment by briannacote** [comment]
Thanks for the head's up. I had done pip so that makes sense. I hope all is well!
