### ISSUE TITLE
EIA 860 2018 Annual Data

### ISSUE THREAD

**Issue by briannacote** [catalyst-cooperative/pudl#398]
Hello,

I am curious when EIA 860 2018 Annual Data (now out of Early Release) may be available to download through your tools?

Thank you!
Brianna

**Comment by zaneselvans** [comment]
Yep yep, we're on it, see Issue #396! We're trying to make an installable software release before [the OpenMod workshop at NREL Sep. 18-19](https://wiki.openmod-initiative.org/wiki/Open_Energy_Modelling_Workshop_-_NREL_2019), and will then get on integrating the 2018 EIA860 and FERC Form 1 data, which are both available now.

So right now I would probably guess the last week of September.

**Comment by briannacote** [comment]
Thank you!
