### ISSUE TITLE
Clean up constants.py

### ISSUE THREAD

**Issue by gschivley** [catalyst-cooperative/pudl#418]
The file is pretty huge right now and it's hard to explain exactly what is needed to add a new data source. This came up during the OpenMod do-a-thon. Not sure if the solution is to split so that each data source has it's own settings.py file (the number of files would also grow over time) or just reformat some to make the division between data sources a bit more clear.

**Comment by zaneselvans** [comment]
Yes, it's kind of a dumping ground. See also #210 and #52. Ideally there would be... almost nothing in there -- it's data and metadata, not code.

**Comment by gschivley** [comment]
I should have looked for other issues first. Will close this one.
