### ISSUE TITLE
Integrate better project management e.g. GitLab

### ISSUE THREAD

**Issue by swinter2011** [catalyst-cooperative/pudl#422]
We want more project management features than we've been able to easily integrate with GitHub. Using Jira+Exalate has been a janky mess.

### Features we want:
* Weights / time estimates / work tracking on a per-issue basis.
* Scrum-style sprint planning / workflow.
* Integration of per-project time tracking would allow us to remove this from our time tracking spreadsheet.
* Full-on time tracking would allow us to get rid of that spreadsheet altogether.
* Eventually we want some kind of pipeline to deploy both software and data releases onto Paneo (aka JupyterHub/BinderHub/Kubernetes w/ a persistent data store).
* We will need private repositories for doing proprietary contract work outside the PUDL project scope.

## The DIY Option:
One (also janky) option is to track the time estimates and actual work that goes into issues in our time tracking spreadsheet -- we already have to have a table of all the issues we're working on and what project they are associated with.

## The Off-The-Shelf Option:
[GitLab](https://gitlab.com) appears to provide all of the features we're looking for on one platform (issue weights, sprint planning, etc.).  We have [the repo mirrored there already](https://gitlab.com/catalyst-cooperative/pudl).

### Outstanding GitLab questions:
* Can we be hosted there as an open source project? They have a "no profit" clause for open source... and what does that mean?
* If they won't give us an open source license, what biz plan would work for us?
* What would we need to do in order to replicate the functionality of all of our existing GitHub integrations?

### GitHub Integrations to Replicate:
**Automated docs build/hosting (Read The Docs)**
  - This is a simple webhook, should be easy to replicate.

**Automated tox/pytest based testing (TravisCI)**
  - This would likely be simplest to replace w/ GitLab's internal CI/CD pipeline, which has a CI minutes quota per month.
  - We could still use TravisCI if we want to (unlimited CI resources for open source projects)

**Test coverage tracking (CodeCov)**
* If we continue to use TravisCI, this will keep working
* If we use GitLab's internal CI/CD, it would be different, but there's still a way to do it.

**Archiving of releases (Zenodo)**
No direct option exists here, but it's something folks have asked for both at GitLab and Zenodo. Seems like there's some recent effort that has gone into it. We can also post these files manually, since releases aren't that frequent (this would also allow us to avoid archiving pre-releases).  We could also

**Code quality checking (Codacy)**
* Can be integrated with GitLab.
* Internal GitLab code quality checks can also be used instead.

**Comment by zaneselvans** [comment]
Another option that might be even simpler is [ZenHub](https://www.zenhub.com/), which I'm looking into now. It integrates directly w/ Github via a browser plugin, and is free for open source projects.
