### ISSUE TITLE
Recover the Lost Plants of EIA

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#431]
In the process of doing the EIA 923 data integration for 2018 (#420) and generating PUDL IDs for FERC/EIA (#428), I discovered that somehow there's 167 EIA plants which appear in the ID Mapping spreadsheet, but which are nowhere to be found in the `plants_entity_eia` table.  Which seems wrong? Are these plants really no longer in the underlying EIA data/spreadsheets? Or are we somehow losing them / failing to harvest them from the data during ETL?

If they're really no longer included in the data, we should probably remove them from the mapping process.  And if they **are** still included in the data, then we need to figure out how we are losing them.

<details>
  <summary>Expand to see the 167 Lost Plants of EIA</summary>
<pre>
plant_id_eia,plant_name_eia
600,lewes
796,ray roberts
1159,manilla
1174,paullina
1277,fredonia
1281,greensburg
1309,neodesha
2019,warren
2154,rich hill
2218,benkelman
2666,feeder dam
3465,hiram clarke
3525,presidio
3558,brownfield
3566,coleman
3608,robstown
3623,vernon
3625,whitesboro
3848,naches drop
3849,naches
4104,black river falls
4249,boardman
5756,kms joliet power partners lp
6339,st michael
7412,john harmon gen
7478,yuma axis
7859,northwest wind
8801,oil storage
8807,cen storage
8808,oil storage
8811,yktn term a
8813,bartow sth
8815,bartow nth
8826,mcduffie
8830,spindletop
10097,crozer chester medical center
10178,memphis hardwood flooring
10179,merrimac paper
10251,los angeles cold storage
10257,diamond walnut
10317,baylor university cogen
10376,entenmanns cogeneration facility
10401,pepeekeo power plant
10403,laidlaw energy & environmental
10406,alsip paper condominium association
10552,lowe paper simkins industries
10557,lebanon methane recovery
10581,altamont power llc
10596,borden chemicals plastics cogen
10602,centaur generator facility
10626,kannapolis energy partners
10683,bcp
10701,wausau papers of new hampshire
10736,jeanerette sugar
10851,fibermark warren glen mill
10886,gaylord container antioch
50040,nicor gas
50057,salk institute
50065,veterans home of california
50113,renegy susanville
50117,university of california
50142,sparks regional medical center
50173,rowan university
50221,r j reynolds tobaccoville utility plant
50238,starwood hotels resorts
50249,abitibi consolidated lufkin
50264,southeast missouri state university
50291,us agri-chemicals fort meade
50313,summit property pharmaceutical
50317,love box
50319,palomar medical center
50342,chicago baking
50356,specialty minerals
50358,general electric erie pa power
50405,warbasse cogen facility
50428,paper pak industries
50538,black hills ontario facility
50557,txi riverside cement power house
50601,riverdale mills
50725,blackjack creek treating
50726,blue water gas plant
50727,flomaton treating facility
50911,bassett table
50912,j d bassett manufacturing
50925,san jose convention center
50934,southernmost waste to energy
50958,nitram
50991,pryor power plant
52012,valero refining texas houston
52013,valero refining texas city
52018,lotus engineering
52164,mesa (zpii)
52201,sunnyside cogen partners
52203,gude
54061,minnesota wood products
54090,international paper louisiana mill
54208,hidalgo smelter
54222,alyeska seafoods
54243,brown williamson tobacco
54248,rock tenn dallas mill
54252,byxbee park sanitary landfill
54253,s&l cogeneration
54293,velcro usa
54313,chicago
54331,sonoco products
54339,smurfit newsprint
54359,ppg place
54443,north riley
54445,rincon facility
54455,art institute of chicago
54516,dixon marquette
54522,green tree chemical technologies
54602,voss lantz
54603,voss taylor
54612,amalgamated sugar llc nyssa
54645,trw radio systems
54652,hutchinson creek
54664,pekin paperboard
54704,centerpoint energy field svs.
54767,st marys hospital
54798,duraco products
54804,central wayne air quality
54825,building 64
54828,3200 wildwood plaza
54838,gould electronics foil division
54866,bradford dyeing association
54871,offshore systems
54884,the american sugar refining co brooklyn
54940,austin state hospital
54942,phelps dodge chicago rod
54947,west pharmaceutical services
54948,fullerton
54971,lone star steel
54976,morton salt grand saline
54999,savannah resource recovery facility
55012,haverhill paperboard
55038,westroads shopping center
55055,biodyne beecher
55073,wheeler landfill gas recovery
55150,exxonmobil baton rouge cogen
55331,philadelphia water department southwest
55336,pwd northwest facility
55521,san gorgonio windplant
55537,cargill hammond
55863,paia hydro
55883,foothills generating llc
55884,rolling hills
55958,big cajun 1 peakers
55975,seward
55982,chena 6
56023,zilwaukee generating station
56024,berlin gorham
56042,bethlehem energy center
56043,wwtp
56136,bennett mountain
56175,phoenix wind power llc
56197,smithfield
56508,mmc midsun llc
56685,dinwiddie 1 and 2
56689,petersburg
56691,richmond
56769,victorville 2 hybrid power project
57092,adage hamilton biopower
57691,lower turnbull hydro
60767,seashore solar
60812,gruber solar center
99999,state-fuel level increment
</pre>
</details>

**Comment by zaneselvans** [comment]
@cmgosnell do you have any insight on this? Seems pretty weird.

**Comment by cmgosnell** [comment]
I poked around at this for a bit and could not find any of these plants in the EIA spreadsheets. My best bet on this is that these plants were in EIA spreadsheets when we pulled the original list of plants for id mapping and have since been removed in revisions. Also, this feels like such a small number of plants that makes this feel like a low priority.

**Comment by cmgosnell** [comment]
we didn't actually fix this but decided to close this due to the small number of plants and the fact that there aren't larger implications that we know of.
