### ISSUE TITLE
ISO/RTO LMP

### ISSUE THREAD

**Issue by swinter2011** [catalyst-cooperative/pudl#437]
Integration of historical RTO/ISO Locational Marginal Pricing (LMP) data from as many US grid operators as possible. Will build upon experiences of Patrick Brown at MIT, and the overall structure of WattTime's PyISO library. May include data at up to 5 minute time resolution, for 10 years, from ~13,000 pricing nodes. May end up being ~1TB of data / ~10 billion records, and will likely require cloud based compute and storage resources. If other data fields are easily obtained simultaneously, great! (e.g. total load, net trade, and total generation by balancing area, load forecasts at several timescales).

**Comment by cmgosnell** [comment]
we de-prioritized this due to licensing issues
