### ISSUE TITLE
PUDL on Pangeo

### ISSUE THREAD

**Issue by swinter2011** [catalyst-cooperative/pudl#438]
[Pangeo](https://pangeo.io) is a federation of [JupyterHub](https://jupyterhub.readthedocs.io/en/stable/) installations that each provide access to computational resources and domain specific datasets in a cloud computing environment, mainly serving various geoscience research communities.  The same basic arrangement would also be great for giving people easy access to a live version of the data in PUDL, along with other public data and open source software that's useful for doing energy system modeling, electricity market analysis, etc.  This could include packages like PyPSA or Calliope, along with data from renewables.ninja, PV Watts, and WINDS, models of regional grid topology, historical load curves and climatic data, etc.

In combination with static data packages for platform agnostic redistribution of the data, and the availability of the open source data processing pipeline, this would round out the access options nicely!

Get the PUDL software and data installed on a BinderHub instance with cloud compute and storage resources using the systems developed by the Pangeo project, providing easy access via a Jupyter Notebook server for folks that want the easiest possible access to all the data, on a platform that makes working with it easy.

**Comment by zaneselvans** [comment]
Supplanted by 2i2c hub stuff.
