### ISSUE TITLE
EPA CEMS resource metadata contains all years when resource pertains to single year

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#452]
The metadata in each of the individual EPA CEMS resources lists *all* of the years of data that are contained across all of the resources, rather than the years which pertain to that resource.  The metadata in each resource should be correct for that resource.

**Comment by zaneselvans** [comment]
The resource has all the years/states from the run stored in the parameters (which is correct), but the `start_date` and `end_date` of the resource pertain to the whole dataset, not the resource.

In addition, there's no metadata in the resource indicating what state the data pertains to.

**Comment by cmgosnell** [comment]
Okay.. @zaneselvans and i touched base about this and talked about some changes that would expand the scope of this issue. 

Would do two main things:
- pull the etl parameters out of the "source" metadata at the package and resource level - put parameters in their own dict in the metadata.
- for CEMS resources, use the standardized names to determine what the year and state for the resource parameters (instead of the datasource etl parameters like everything else.

dp metadata would end up look something like this:

```
{
"name": "whatever",
"other-stuff": "sure",
"sources": {
   "title": "blah",
   "path": "interwebz",
  },
"parameters": {
   "dataset1_years": [list of years],
   "dataset1_tables": [list of years],
   "dataset2_years": [list of years],
   "dataset2_states": [list of years],
   "dataset3_years": [list of years],
   "dataset3_states": [list of years],
  },
"resources": [
  {
    "name": "table.."
    "sources": {
       "title": "dataset1",
       "path": "interwebz",
      },
    "parameters": {
       "dataset1_years": [list of years],
       "dataset1_tables": [list of years],
      },
  },
  {
    "name": "table2.."
    "sources": {
       "title": "dataset2",
       "path": "interwebz",
      },
    "parameters": {
       "dataset2_years": [list of years],
       "dataset2_states": [list of years],
      },
  },
  {
    "name": "cems_table_2016_co"
    "sources": {
       "title": "dataset3",
       "path": "interwebz",
      },
    "parameters": {
       "dataset3_years": [2016],
       "dataset3_states": ["CO"],
      },
  },
]
}
```

With these changes, I'd like to remove start and end date at the resource level. Having these with the parameters seem like an unnecessary duplication of information.

**Comment by zaneselvans** [comment]
`parameters` is pretty generic and could be confusing. Can we call it `pudl_etl_parameters` instead at the datapackage level?

I thought we were talking about putting a metadata element that is not explicitly referencing the ETL parameters into at least the resource level metadata. The term that seems to be used in metadata standards [like the Dublin Core](https://www.dublincore.org/resources/userguide/creating_metadata/#Guidelines_for_describing_the_coverage.2C_spatial_or_temporal_character_of_a_resource) for this kind of thing is "coverage" and either "spatial" or "temporal". So if we have the ETL parameters and/or the output resource name (for CEMS) as the inputs to work with, we should be able to generate something like the following for output:

```
  {
    "name": "hourly_emissions_epacems_2016_co"
    "sources": {[
        "title": "EPA Air Markets Program Data",
        "path": "https://ampd.epa.gov/ampd/",
      ]}, # For CEMS, should we also include the EIA 860 and/or EIA 923 sources, since they contribute?
    "coverage": {
        "spatial": { # We're already using: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3
            "country": "USA", # Resources not broken out by state would just have "country"
            "state": "CO"
        },
        "temporal": {
            "start_date": "2016-01-01",
            "end_date": "2016-12-31"
        }
  },
```
I think we could also have just a 4-digit year in the `start_date` and `end_date` fields and it would be correctly converted into a real ISO8601 date if someone ran e.g. `pd.to_datetime()` on it. Or we could call it `start_year` and `end_year` to make it obvious that it is only being stored at annual resolution for now.
