### ISSUE TITLE
CEMS UTC offset adjustments in the wrong direction?

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#495]
@jrea-rmi raised the following question about CEMS data:

> I assume all of the data is reported with a local timestamp, and that the pudl etl process converts this to a utc timestamp. However, I'm wondering if the utc conversion was done backwards? (Or if my thinking is backwards?) For example, plant_id_eia 3 is in Alabama, and its first timestamp is 2016-12-31T18:00:00Z. At that utc time, the local time in Alabama would be noon, not midnight, right?

This does seem off, doesn't it @karldw? Could there be a sign error in the UTC conversion? It looks like the relevant code would be in `pudl.transform.epacems.fix_up_dates()`:
```py
    # Add the offset from UTC. CEMS data don't have DST, so the offset is
    # always the same for a given plant.
    df["operating_datetime_utc"] = df["op_datetime_naive"] + df["utc_offset"]
```
So in the case of Alabama, the UTC offset in winter is -06:00. **Adding** -06:00 to the naive time would make it even further away from UTC, so we ought to be **subtracting** -06:00 (aka adding 06:00), shouldn't we? The UTC offset is the number of hours you need to add to UTC to get the local time, right? @cmgosnell which looks right to you?

**Comment by karldw** [comment]
Ah, that's great. Yes, I think you're exactly right. Thank you, @jrea-mi, for finding my bug!

When I noticed dates showing up as the previous year, i thought "oh, that's just some timezone nonsense" and didn't think any harder about it.

**Comment by jrea-rmi** [comment]
Glad to hear that helped!
