### ISSUE TITLE
Improve robustness and completeness of column mapping process

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#528]
The list of columns which are expected to exist in spreadsheets / dataframes / database tables is a little bit chaotic, and not rigorously enforced across the ETL process. Places where these lists appear include:
* The original EIA spreadsheets themselves.
* The column mapping CSVs that are used to rename the columns read from individual "pages" ripped out of the spreadsheets, before they are concatenated together across years (and occasionally across tabs in a given sheet, e.g. in the case of proposed / existing / retired generators)
* The column datatype dictionary in `pudl.constants`
* The JSON `TableSchema` definitions which we store in the MegaData metadata.

When we move between these different spaces, we need to have some way that we require the mapping to be both complete and accurate -- i.e. that there are no extra columns floating around, and there are no columns which should have been caught which were lost because they weren't enumerated.

Otherwise, if a typo is made in the column maps, it won't necessarily cause anything to fail -- a year's worth of that column's content will simply get nulled out. Similarly, there may be columns with no data type associated with them, or we might forget to add a new column that appears in a new year of data.

**Comment by TrentonBush** [comment]
@zaneselvans I think our metadata overhaul closed this issue, right?

**Comment by zaneselvans** [comment]
Oh yeah, this is super done.
