### ISSUE TITLE
More detailed instructions on how to update to new versions of pudl

### ISSUE THREAD

**Issue by grgmiller** [catalyst-cooperative/pudl#534]
**Is your feature request related to a problem? Please describe.**
As mentioned in https://github.com/catalyst-cooperative/pudl/issues/533 it seems like at least two people  were confused about how to update pudl correctly from 0.2.0 to 0.3.0 when it is already installed on your local machine.

**Describe the solution you'd like**
Add more complete documentation to https://catalystcoop-pudl.readthedocs.io/en/v0.3.0/install.html# on how to update pudl from one version to another. 

Maybe it is as simple as:
in your `environment.yml` file add `catalystcoop.pudl=0.3.0` and save, then run: 
```
conda update conda
#if using --clobber it will overwrite all existing files in the workspace
conda env update pudl --clobber
```

Another option is to remove the environment completely and reinstall it:
```
conda env remove --name pudl
#if using --clobber it will overwrite all existing files in the workspace
conda env create --name pudl --file environment.yml --clobber
```

**Comment by cmgosnell** [comment]
I believe this (very reasonable) desire is satisfied in our recently [updated docs](https://catalystcoop-pudl.readthedocs.io/en/latest/dev/dev_setup.html#updating-the-pudl-dev-environment) but please reopen this issue if this still feels confusing!

**Comment by grgmiller** [comment]
Thank you!
