### ISSUE TITLE
use zenodo archives to download new datastore

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/pudl#540]
- use DOIs to grab archives (compatible DOIs stored)
- use `pudl_settings` for storage location
  - based on `.pudl.yml`
  - `pudl_settings = pudl.workspace.setup.get_defaults()`
- have one directory per data set/zenodo archive

**Comment by ptvirgo** [comment]
- use ZENODO_TOKEN for the zen_storage module as well, instead of having mutliple key configs
