### ISSUE TITLE
Allow parallel processing of EPA CEMS ETL

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#558]
The EPA CEMS ETL is by far the slowest part of the entire ETL process, and it is embarrassingly easy to parallelize -- each of the state-years (all 1200 of them) could be done independently if we wanted to. Probably just doing each of the 25 years in parallel would be good enough, and knock the processing time down to 15 minutes instead of 6 hours. This would get done in the `pudl.transform.epacems()` function I think.

**Comment by cmgosnell** [comment]
subsumed within #1147
