### ISSUE TITLE
use standardized extractor for eia 860

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/pudl#560]

**Comment by ptvirgo** [comment]
Use the datapackage.json to correctly get the location of the zipped source archives.

The python zip library allows for accessing the contents of a zip file without writing extracted contents to disk:
https://docs.python.org/3.8/library/zipfile.html

We need a way hand off the contents of zenodo-archived zip files to the extract process.

**Comment by ptvirgo** [comment]
The "get_file" function on ../code/pudl/exctract/eia861.py currently expects the path to the excel sheets.  The "get_xlsx_dict" uses "get_file" to retrieve the sheets.  Once get_xlsx_dict hands off it's dict, the extract process can proceed per usual.

**Comment by ptvirgo** [comment]
*file_name_map.csv* maps the expected contents (as required for the etl) of an eia861 archive to the file name within the zip file.  (For example, every year the csv of the sales information might have a different filename.  file_name_map.csv denotes the correct name.)

**Comment by ptvirgo** [comment]
"get_datastore_path" needs to go away

**Comment by ptvirgo** [comment]
zenodo_downloader needs to be tweaked!  storage dir should be <pudl_in>/<dataset name>/*data*/ ...
