### ISSUE TITLE
Document codes and data structures associated with the EIA 176

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#562]
The full dataset can be downloaded from [here](https://www.eia.gov/naturalgas/ngqs/all_ng_data.zip), and consists of about 60MB worth of CSVs (uncompressed). Lots of data about natural gas production and consumption.

**Comment by karldw** [comment]
Things I've learned this morning:
- The `LINE` variable is the form line number multiplied by 100
    - For a couple of fields, the question associated with the line number has changed over time (see https://www.eia.gov/naturalgas/ngqs/ngqs_user_guide.pdf#page=21)
- The `ATYPE` variable refers to the column of the answer. For the questions I'm interested in, `VL` is gas volume in 1000s of cubic feet,  `CS` is revenue in dollars, and `CT` is customer count. I figured these out by comparing the numbers in the bulk download with the [data browser](https://www.eia.gov/naturalgas/ngqs/#?year1=1997&year2=2018&company=Name). I'm not sure if they're documented somewhere.
- There are duplicates for name-state-year, even when ID-state-year is unique.

**Comment by zaneselvans** [comment]
Reopening with a more prescribed scope since we are going to integrate this data, and Karl has done some data sleuthing already.

**Comment by MichaelTiemannOSC** [comment]
Noting that 176 can and should be cross-checked against 857

https://www.eia.gov/dnav/ng/TblDefs/NG_DataSources.html#s176
https://www.eia.gov/dnav/ng/TblDefs/NG_DataSources.html#s857

**Comment by zaneselvans** [comment]
I think this is superceded by the subtasks within #2603 now.
