### ISSUE TITLE
Further integration of nullable integers

### ISSUE THREAD

**Issue by karldw** [catalyst-cooperative/pudl#563]
The new releases of pyarrow and pandas [support](https://issues.apache.org/jira/browse/ARROW-5379) reading and writing nullable integers to parquet files! That means some of the existing parquet schema manipulation is unnecessary, like the workaround I wrote [here](https://github.com/catalyst-cooperative/pudl/blob/6e917514788691991f1dd0ac1a2c842a76a4f1e2/src/pudl/convert/epacems_to_parquet.py#L86-L146).

That code will still work, but new code that writes parquet files can be simpler.

(Feel free to close this issue. I just wanted it documented somewhere.)

Ref: #252

**Comment by zaneselvans** [comment]
Great! Would you be willing to go ahead and make the required changes? The current master branch uses Pandas 1.0 and while it is breaking PyTest for some reason that I am trying to debug, it strangely seems to work fine in normal usage.

**Comment by karldw** [comment]
I have some upcoming deadlines, so probably shouldn't write any code for PUDL until May. I'm happy to come back to this then if it hasn't already been fixed.

**Comment by zaneselvans** [comment]
Hey @karldw I *think* I addressed this issue in the closing commit above -- just swapping out the `float32` for `pandas.Int32Dtype()` and using nullable pandas types for the EPA CEMS ETL dataframes -- let me know if it should be re-opened!
