### ISSUE TITLE
Docs request: datapackage details onto readthedocs

### ISSUE THREAD

**Issue by karldw** [catalyst-cooperative/pudl#564]
**Is your feature request related to a problem? Please describe.**
When I'm hunting for a particular variable, I'm often unsure which dataset it's in, or if PUDL has a cleaned version.

**Describe the solution you'd like**
It would be great to have the readthedocs site describe the tables and variables that are present in the current zenodo release. Things like table names, variable names, and years covered would be really useful.
It seems like you've already done the hard part by creating writing the computer-readable datapackage.json descriptions. (I'm not familiar with the details, so I'm sure it's more difficult than I realize.)

**Describe alternatives you've considered**
Just download the datapackage.json file and search.

**Additional context**
This issue particularly comes up for FERC form 1, where some tables are left uncleaned.

**Comment by zaneselvans** [comment]
This is definitely doable and something I've been thinking about.  A couple of examples of data package metadata posted on the web in a more readable form:
* The [Glacier Thickness Database](https://gitlab.com/wgms/glathida) repo on Gitlab
* Datahub.io for example my attempt to package up the [MSHA Mines & Production data](https://datahub.io/zaneselvans/pudl-msha)

**Comment by cmgosnell** [comment]
this is done now with our [data dictionaries](https://catalystcoop-pudl.readthedocs.io/en/latest/data_dictionaries/pudl_db.html).
