### ISSUE TITLE
epacems_to_parquet stops after converting only part of the data

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#565]
Eric Gimon found that when he was running the `epacems_to_parquet` script to convert the data in release 1.1.0, the process consistently died somewhere in 2003.  He's running PUDL within the Windows Linux Subsystem on Windows 10, using the Anaconda python distribution.

**Comment by rousik** [comment]
Can we get logs for that run? This might help zone in on the problem faster.

**Comment by zaneselvans** [comment]
Hmm, that script doesn't really log much except for which year/state it's working on. Do you have a windows machine that you can play around with things on by chance? This has been an issue for us -- we're all on Linux or OS X so it's been hard for us to help users on Windows.

**Comment by rousik** [comment]
Unfortunately I'm in the same camp (linux + osx only). I did expect that when the process "dies" it would at least spew out some exception or error message but maybe it doesn't. I hoped cloud win images might help us but I suspect licencing/costs will put a stop on that :(

**Comment by rousik** [comment]
https://azure.microsoft.com/en-us/free/ this might possibly be helpful

**Comment by zaneselvans** [comment]
It looks like it's just straight-up free for open source projects, with unlimited CI/CD minutes and up to 10 parallel processes, if we can just figure out what we would need to do to intall and test the software on Windows w/o actually having access to Windows!
* https://azure.microsoft.com/en-us/blog/announcing-azure-pipelines-with-unlimited-ci-cd-minutes-for-open-source/
* https://azure.microsoft.com/en-us/services/devops/pipelines/

**Comment by rousik** [comment]
I was thinking virtual machines where we could play with it remotely, not sure if the pipeline plan does offer any of that, but we may poke it. What's the severity/priority of this?

**Comment by zaneselvans** [comment]
Ah I see. I think this is a low priority overall, but something we've run into before.  The path we've mostly been on so far to make everything as easy as possible for folks to setup and use is to containerize PUDL, and also make it available via a remote JupyterHub running on The Google.

**Comment by zaneselvans** [comment]
We are going start directly generating parquet outputs, rather than datapackages that need to be converted, so I'm going to close this.
