### ISSUE TITLE
Develop emissions analysis module

### ISSUE THREAD

**Issue by grgmiller** [catalyst-cooperative/pudl#575]
In order to make the CEMS data more usable for analyzing GHG emission factors at the generator level, I am beginning work on `pudl.analysis.emissions` which will create a "cleaned" CEMS dataframe that will containing:
 - operating_datetime_utc
 - plant_id_eia
 - generator_id
 - gross_generation_mwh
 - net_generation_mwh
 - co2_mass_tons

This module will contain functions that:
 - calculate `gross_generation_mwh` from `gross_load_mw` and `operating_time_hours`
 - calculate parasitic loss factors / gross-to-net ratios to convert `gross_generation_mwh` to `net_generation mwh`
 - fill missing `co2_mass_tons` data using `heat_input_mmbtu` and fuel type proportions calculated from `bf_eia923`
 - using techniques similar to those used in the `analysis.mcoe` module, aggregate boiler-level data to generator-level data (after ensuring correct mapping of EPA `unit_ids` to EIA `generator_ids` using the crosswalk provided by the EPA)

I plan to use this as a starting point for the eGRID project. 
 
Feedback/thoughts on this module are welcome. I am starting in my fork of pudl located at https://github.com/grgmiller/pudl.

**Comment by zaneselvans** [comment]
@TrentonBush You might want to get in touch with @grgmiller about the CEMS / RMI emissions work.

**Comment by grgmiller** [comment]
I am closing this because this need has been met by the OGE project: https://github.com/singularity-energy/open-grid-emissions
