### ISSUE TITLE
integrate the new datastore with the epaipm etl

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/pudl#581]

**Comment by ptvirgo** [comment]
NEEDS page scraper results aren't right. We need these:

- transmission_single_epaipm: https://www.epa.gov/sites/production/files/2019-03/table_3-21_annual_transmission_capabilities_of_u.s._model_regions_in_epa_platform_v6_-_2021.xlsx
- load_curves_epaipm: https://www.epa.gov/sites/production/files/2019-03/table_2-2_load_duration_curves_used_in_epa_platform_v6.xlsx
- plant_region_map_epaipm: https://www.epa.gov/sites/production/files/2019-03/needs_v6_november_2018_reference_case_0.xlsx
