### ISSUE TITLE
integrate the new datastore with the ferc1 etl

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/pudl#583]

**Comment by ptvirgo** [comment]
src/pudl/extract/ferc1.py :: get_strings(...) is not handling the bytestream effectively.  Caller, get_dbc_map, needs it on the way to producing an intermediary object called tf_dict.

Getting tf_dict to match the attached form for the ferc1 2018 source should address the problem.

[https://app.zenhub.com/files/80646423/a1736e58-a701-435f-9116-2ce891b412fc/download](https://app.zenhub.com/files/80646423/a1736e58-a701-435f-9116-2ce891b412fc/download)

**Comment by ptvirgo** [comment]
Expected final output of the get_dbc_map function.

[https://app.zenhub.com/files/80646423/4e8c7053-c703-4082-afaf-511613369b14/download](https://app.zenhub.com/files/80646423/4e8c7053-c703-4082-afaf-511613369b14/download)
