### ISSUE TITLE
Treatment of missing values during CEMS transformation

### ISSUE THREAD

**Issue by grgmiller** [catalyst-cooperative/pudl#604]
The EPA cems transformation process currently replaces missing values for `gross_load_mw` and `heat_content_mmbtu` with the following code:
<code>
raw_df.fillna({
                    "gross_load_mw": 0.0,
                    "heat_content_mmbtu": 0.0
                })
</code>

I was wondering if there is a strong reason why these missing values are being filled?

As I've been exploring this data further, I have been finding that a null value and a zero value are not interchangable. For example, during startup, heat input and operating time can both be nonzero, but gross load can be zero. 

I'd like to be able to identify some methods to fill missing values in CEMS using estimated values, but the current datapackage makes it difficult to identify which values are missing and which are actually reported as zero, since all the missing values have been filled. 

I would propose removing the above fillna code in the pudl/src/pudl/transform/epacems.py file. 

I don't think that keeping these values as NA should break any other code further down the line, as the `co2_mass_tons` column also contains some missing values that were left alone.

**Comment by karldw** [comment]
Three quick thoughts:
- How often are gross load or heat content `NA` and when operating time is a positive number?
- This change could break some assumptions in downstream code for people building things with the data. Worth highlighting in a release note if you make this change.
- If you make this change, you should also change the schema of the CEMS parquet files [here](https://github.com/catalyst-cooperative/pudl/blob/72ef9490d0a9b12a1b7830bee8432a7fdf90a0c7/src/pudl/convert/epacems_to_parquet.py#L128). (Just change the relevant lines from `float_not_null` to `float_nullable`)

**Comment by grgmiller** [comment]
Hi @karldw these are some good points. I have not re-run the whole ETL process yet without the fillna, so I'm not sure how many missing gross load or heat content values there are. However, at least for the 2018 CEMS data, the co2 mass data (for which the missing values were not replaced) contains about 1.3 million missing values, or about 10% of the total observations when operating time is a positive, non-zero number. 

Perhaps instead of getting rid of the fillna completely, there could be an option to run the ETL without filling missing values in case you want that.

One thing I'm curious about though is the inconsistent treatment of missing values... why were gross load and heat content replaced, but co2 mass left alone? @gschivley do you have any insight on that?

**Comment by karldw** [comment]
If I remember correctly, we were [fairly confident](https://github.com/catalyst-cooperative/pudl/issues/171#issuecomment-449230223) that NA values in gross load or heat content were zeros, but weren't as confident filling the emissions numbers. (But see @gschivley's [comment](https://github.com/catalyst-cooperative/pudl/issues/360#issuecomment-518213976) about how heat rates are calculated.) 
To repeat Greg's frequent suggestion to me, the [plain english guide to the part 75 rule](https://www.epa.gov/sites/production/files/2015-05/documents/plain_english_guide_to_the_part_75_rule.pdf) might be worth a look.

**Comment by aesharpe** [comment]
Update: removed the `fillna(0)` for both gross load and heat content.

**Comment by grgmiller** [comment]
Just to add some additional support for doing this... according to the EPA's [Power Sector Emissions Data Guide](https://www.epa.gov/system/files/documents/2022-07/CAMD%27s%20Power%20Sector%20Emissions%20Data%20Guide%20-%2007182022.pdf): 

> A blank in the data (emissions, heat input, load) is not the same thing as a zero. A blank likely
indicates that the EGU is not required to report a particular parameter based on the program(s)
it is affected by. Checking the program code(s) for the EGU may help explain why certain
parameters appear or do not appear in the data. Refer to Table 1 under “What data are
collected?” for more information on program reporting requirements.
