### ISSUE TITLE
make the pudl.output.eia860.generators_eia860() the backbone of the mcoe outputs

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/pudl#608]
we need to figure out how to do this... probably has many dependencies like issue #254 

We need to make a decision about how to merge annual records with monthly data tables in which the entities don't show up in the data tables. Should we make a complete monthly time series w/ nulls for every month? Probably, but where and how should we implement that? See TODO in [pudl.helpers.merge_on_date_year](https://catalystcoop-pudl.readthedocs.io/en/latest/api/pudl.helpers.html#pudl.helpers.merge_on_date_year)

**Comment by zaneselvans** [comment]
I think this is more or less fixed now. If you run `pudl_out.mcoe(all_gens=True) you'll get all of the generator-years or generator-months, with MCOE data columns that are populated, or Null, depending on whether that generator-year/month has MCOE output.
