### ISSUE TITLE
Identify and fix the most important missing BA/Util geometries

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#618]
Many of the historical geometries that are generated using the EIA 861 + US Census data are very consistent with HIFLD in 2017-2018. Many of them are also self-consistent across the years for which we have data (2001-2018). However, there are some big holes that we need to fill in order to have workable territories for the major FERC 714 planning areas at least back to 2010.

# Alter Geometries:

## MISO (2009-2010)
* MISO territory for 2010 is unreasonably small, and non-existent for 2009 and earlier years.
* However, MISO reports demand for 2009-2010 in FERC 714.
* However, based on [this workshop report](https://www.purdue.edu/discoverypark/sufg/docs/publications/2014%20July%20Workshop%20-%20LRZ%20Allocation%20Factors.pdf) it looks like there's essentially no difference between the 2011+ years and 2009-2010.
* **Backfill 2009-2010 with the 2011 geometry.**

## Southwest Power Pool (2006-2013)
* SWPP has demand for all years but is missing geometry for 2006-2013
* SPS has demand and geometry for 2006-2013, but nothing later.
* SPS and SWPP merged in 2014.
* SWPP geometry grows a lot between 2014 & 2015, population and demand grows modestly.
* They [expanded into SD, ND, MT](https://rmi.org/shifting-currents/).
* Seems legit, and unrelated to the SPS merger, which appears to have been handled.
* Need to backfill 2006-2013 geometries for SWPP... is the pre-expansion 2014 geometry likely to work?
* Demand is consistent as far back as 2010. 2009 is 10% lower, 2006-2008 another 15% lower.
* Incorporated Nebraska utilities in 2009 (April 1st, hence the middling demand)
* **Backfill 2010-2013 with the 2014 geometry.**
* **Backfill 2006-2009 with 2014 map minus Nebraska.**

## Louisville Gas & Electric and Kentucky Utilities (2006-2012)
* Reports demand for all years, but lacks geometries in the early ones.
* Demand reported is consistent across all years.
* Population and service territory area in 2013 are almost 2x bigger than later years.
* **Backfill 2006-2013 with the 2014 geometry.**

## American Electric Power Company (2011-2013)
* Identified as a BA
* Has geometries through 2010, but not thereafter.
* Appears in the BA assn table only as a BA.
* Makes sense that it's only getting a geometry by virtue of its constituent utilities.
* Demand reported 2006-2013 is pretty constant.
* Big increase in territory (3x) and smaller increase in population (1.5x) between 2008 & 2009.
* Early geometries are in the midwest. Later geometries bring in a bunch of Texas, Arkansas, Louisiana.
* Appears that AEP really did expand into those areas.
* However, the FERC-714 demand doesn't change when those areas are integrated, so it seems like the demand being reported probably just pertains to the original service territory in the midwest & appalachia.
* **Limit service territory to counties in OH, IN, VA, WV, TN, KY, MI**

## Entergy Corporation/Services (2013)
* Reports demand consistent with past years in 2013
* However, geometry isn't present.
* **Forward fill 2013 with geometry from 2012**

# Treat as Utilities not Balancing Authorities:

## PG&E (2006-2010)
* PG&E shows up as a BA in the EIA-861 only in 2002.
* It shows up in all years as a utility, with service territory, etc.
* As a utility, it shows up within CISO.
* Because it's showing up as a BA that one time, we're assuming it's a BA. But it never gets any territory associated with it outside of 2002, or as a utility.
* This seems like a reporting irregularity.
* **Force PG&E to be treated as a utility by replacing it in 2002 with CISO in the BA table during ETL.**
* **This should mean it gets categorized correctly across all years and gets a territory assigned automatically.**

## San Diego Gas & Electric Company (2011-2019)
* Has a geometry in earlier years (2006-2010), but it's missing from 2011 forward.
* Reports consistent demand across all years in FERC-714
* EIA-861 service territory table shows it having the same counties for all years 2001-2019 (San Diego & Orange)
* Why isn't it getting a service territory for the later years?
* It's being identified as a BA because it shows up in the BA table from 2001-2010, but after that it's gone.
* It also shows up in all the years of EIA 860 as a utility.
* **Force it to be treated as a utility**

## Dayton Power & Light (2011-2019)
* Shows up as a BA in EIA-861 in 2001-2010
* Also shows up as a utility in EIA-861 in 2005-2019
* Has the same territory listed by its utility ID in all 19 years of service territory data.
* **Force it to be treated as a utility**

## Consumers Energy Company
* Like PG&E it appears as a BA a few times (2003-2006) but really it appears to act like a utility.
* Has service territory (counties) in all years, and shows up in other utility tables as a utility.
* However, because it shows up at least once as a BA, we use the BA territory generation process, which doesn't work if you're really a utility. So it ends up getting no territory assigned (even though it's got counties)
* **Force Consumers Energy Company to be treated as a utility, not a BA**

# Unfixable Service Territories

## Mid-Continent Area Power Pool (2006)
* No `eia_code` is provided for this respondent,and it's unclear what it corresponds to.
* [Wikipedia suggests](https://en.wikipedia.org/wiki/Midwest_Reliability_Organization) it's the predecessor to the Midwest Reliability Organization which is a NERC region.
* Respondent only appears in 2002.

## FirstEnergy (2006-2008)
* Ohio-based IOU with several different `utility_id_eia` values over the years.
* OH based sales are reported in PJM for 2013 and later years via EIA-861.
* Listed as a Power Marketer / Retail Power Marketer in the EIA-861.
* Never shows up as a utility in the BA associations.
* Never shows up in the service territory table.
* Doesn't appear to be fixable.

## Westar Energy / KPL (2006-2008)
* Several utilities named Westar
* One in EIA-861 with complete geometries has sales that don't track with the FERC-714 demand.
* No obvious reconciliation to be had. 

# Wholesalers Without Service Territories
There are 28 respondents that appear to be some kind of wholesale organization, mostly cooperative G&Ts and public power entities without their own service territories. They account for about 34% of the reported demand that's not associated with any service territory. A few are listed below from early investigation. The others were excluded if they:
* Report demand in the FERC-714.
* Never appear in the EIA-861 service territory table (with counties).
* Are listed in EIA-860 or EIA-861 as a utility.
* Appear to have a parent BA in the EIA-861 `balancing_authority_assn_eia861` table.

## Oglethorpe Power Corp (2006-2019)
* Electricity supply cooperative in Georgia.
* Has no geometry for any year, and doesn't show up in the EIA-861. Does appear in EIA-860.
* Is it maybe just a supplier with no customers or service territory of its own?
* Is it's demand being included already with Southern Company (SOCO) which covers all of Georgia?
* In early years of EIA-861 which explicitly link utilities to the balancing authorities they are part of, Oglethorpe is associated with SOCO, but it has no counties associated with it in the service territory tables.

## Northeast Utilities Service Company (2006-2014)
* No geometry for any year in which it appears in FERC-714.
* aka New England Hydro-Transmission Corp.
* Eventually got bought out by Eversource.
* Appears in early EIA-861 years in association with NE-ISO (in the BA table)
* Does not show up anywhere within the service territory table.

## Central Electric Power Cooperative (2006-2019)
* Reports demand in all years, but never has a geometry.

# Other Issues
* PJM territory gets much smaller as you go back in time. Is that right?
* Is the area near Houston being excluded from ERCOT?
* PACE & PACW are separate balancing areas but a single utility. Need to merge them somehow. See #616

**Comment by zaneselvans** [comment]
For 2013 and later, the list of counties for each territory is being compiled based on the utilities that show up in association with a given BA in the `sales_eia861` table (in earlier years, the utilities associated with a given BA were listed explicitly in the `balancing_authority_eia861` table). So what does it mean that a county shows up in one of these maps? I think it means that a utility that serves that county sold electricity to end users in the BA in question. Is that a good proxy here, or not? That makes these territories the union of all the counties served by all the utilities that participated in sales within the BA.

I think there's another level of geographic specificity available here if we want it, which is the state in which the sales took place -- for 2013 and later we have the state, BA code, and utility available in the `sales_eia861` table, so rather than pulling in all of the counties associated with each utility, we could just pull in the counties associated with the utility that are inside the state(s) that show up in the `sales_eia861` table.

Presumably the same kind of utility - BA associations will show up in many of the other EIA 861 tables. Should things like energy efficiency, demand response, and advanced metering infrastructure also be used to infer which counties are included in a BA territory?

**Comment by zaneselvans** [comment]
Yup, it turns out using only the subset of counties that are in the states which are mentioned in the `sales_eia861` table records cleans up pretty much all of these big territorial weirdnesses so yay!  A few examples (only for 2013-2018, since adding the state screws up the earlier years which don't have access to state information w/o separating the processes more)

## ERCO
![image](https://user-images.githubusercontent.com/596279/83724378-cd70f200-a605-11ea-874e-0d63dbd4ce33.png)

## PJM
![image](https://user-images.githubusercontent.com/596279/83724409-da8de100-a605-11ea-8158-efd8b4b55fb3.png)

## MISO
![image](https://user-images.githubusercontent.com/596279/83724525-0c06ac80-a606-11ea-9365-33300f2325d7.png)

**Comment by karldw** [comment]
Is this map helpful?
https://www.wecc.org/Administrative/Balancing_Authorities_JAN17.pdf

For instance, according to that link, CISO should not include Sacramento (BANC), Los Angeles (LDWP), or the Turlock irrigation district. (These are geographically small, but probably a non-negligible number of MWh.)

**Comment by zaneselvans** [comment]
Bringing the image in here for reference:
![image](https://user-images.githubusercontent.com/596279/83845284-2b690c80-a6ce-11ea-958d-574a5296bd9a.png)

**Comment by zaneselvans** [comment]
I could imagine a process where we subtract the small BAs from the large ones spatially -- for example to remove BANC, TIDC, & LDWP from the potentially overzealous CISO map, but I'm not sure how generalizable this is going to be. I wish there was some way to verify within the 714 hourly demand data that those demand curves were really reported separately, rather than the small BA demand showing up in both their own time series, and the time series of the larger enclosing BAs.  Is that a ridiculous concern?

Also in the particular application that we're looking at, I think we're going to end up layering these areas together, along with their hourly demand, and then having to choose at each location which of potentially several demand series to use.  So we could say something like "use the most geographically specific demand series available" which would mean in the areas where a small BA overlaps a large one, the small demand series would take precedence which might be functionally the same thing as excising those counties from larger BA in the input map.

**Comment by zaneselvans** [comment]
@ezwelty as I think you've already seen, the code that builds these geometries is in `pudl.analysis.service_territory` and it gets specifically applied to the case of building the weird mishmash of FERC 714 utility + balancing authority / planning area geometries in the `pudl.output.ferc714` module.

**Comment by ezwelty** [comment]
@zaneselvans 
> American Electric Power Company (2011-2013) [...] 
> Limit service territory to counties in OH, IN, VA, WV, TN, KY, MI

This doesn't seem quite right. In the earliest years (2006-2008) before the major expansion in 2009, the geometry spans the following states: ['OH', 'IN', 'VA', 'WV', 'TX', 'MI', 'OK', 'AR', 'TN', 'KY']. Should I just forward-fill 2009-2013 with either 2006, 2007, or 2008?

**Comment by zaneselvans** [comment]
Just looking at my notes above, what I recall is that there wasn't an increase in demand corresponding to the expansion into the counties in TX/AR/LA that are disconnected from the main midwestern territory, which made me suspect that actually demand from those regions was not being integrated into the FERC 714 data, and so in this case I was trying to cobble together a territory that specifically matches the apparently reported demand, rather than reflecting what was reported in the EIA 861. So this is something that would only ever make sense to do in the context of working with these territories and the FERC 714. Does that seem reasonable? Was I wrong about the constant historical demand, even when the territory and population increased?

**Comment by ezwelty** [comment]
@zaneselvans I follow the logic, and you are right that there is an abrupt increase in service territory in 2009 without a corresponding increase in FERC 714 demand. All I'm saying is that the earliest years do include counties in TX, OK, and AR, states that were not on your list. It seems weird to exclude these utility-states combinations, since they are present in the years before the expansion.

**Comment by ezwelty** [comment]
@zaneselvans Investigating the re-assigning of entities from balancing authorities to utilities... One thing to consider is that these "faux-BAs" have utilities associated with them. For Pacific Gas & Electric, San Diego Gas & Electric, and Dayton Power & Light, it makes sense that the utilities associated with them as BAs would be reassigned to their parent BA. For example, in 2002, PG&E is listed as both a utility of CISO, and a BA with several utilities, which in that year only are not listed as utilities of CISO. So it makes sense that the utilities assigned to PG&E be reassigned to its parent, CISO.

However, this gets weird for Consumers Energy Company, which as BA (2003-2006) only includes one utility (40211 in Indiana). It is not clear which BA to reassign this nested utility, if any. The BA parent to Consumers Energy Company (12427) is never listed as containing utility 40211, but several other BAs are associated with this utility.

More generally, should I check if there are BAs with utilities that themselves (as BAs) have utilities in `balancing_authority_assn_eia861`. I presume this nesting would indicate a problem?

**Comment by ezwelty** [comment]
@zaneselvans So after the fixes you enumerated, there are still 111 EIA identifiers that show as both a utility and a balancing authority with utilities other than themselves in the same year in `balancing_authority_assn_eia861`.

**Comment by zaneselvans** [comment]
Hmm. I had not really looked into the potential for these multi-layered nesting relationships, and what to do about them, or really gone into detail on whether these relationships all made sense purely from the point of view of the EIA 861 data. I was chasing down big missing / bad territories in the FERC 714 data. I'm not sure what the right thing to do is in here.
