### ISSUE TITLE
integrate dbfread into setup.py

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/pudl#632]
integrate our fork of dbfread into our standard dependencies.

**Comment by zaneselvans** [comment]
https://python-packaging.readthedocs.io/en/latest/dependencies.html#packages-not-on-pypi

**Comment by ptvirgo** [comment]
Done when:
   * our fork of DBFread is correctly installed as a pudl dependency instead of the current unusable one.
   * running etl / tests uses zenodo archives for source data
   * zipped zenodo archives are handled by dbfread without requiring on-disk zipping
