### ISSUE TITLE
Make harvesting process more explicit

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#641]
Currently much of the logic involved in the entity harvesting process is implicit -- a fixed set of columns is stripped out of every table and associated with the entity that that attribute is really associated with.  However, there are some cases which this process can't address (see #613 and #640 for examples). It also means that the harvesting process depends on all post-transform tables being available, so a global search can be performed for the columns to be harvested. This means we can't take advantage of potential parallelism in task of harvesting these attributes.

A few things we might look at:
* For each table, we need to be storing metadata about all the columns that exist at the end of phase 1 of the transform process -- when the table is still denormalized, but every column is a value that will end up in the database *somewhere* -- meaning we will know its data type, valid ENUM values, the entity it should be associated with, etc.
* In the metadata we store about a table, we need to explicitly note which columns are part of the primary key, and which columns are data -- anything else that's left at the end of phase 1 of the transform process is a denormalized column that will be stripped out during the harvesting process one way or another.
* However, given that there's potentially more than one way that a column could need to be harvested -- in association with more than one type of entity, or as both a fixed value and as part of an association table -- we may need to separate the harvesting from the column removal processes.
* To manage these dependencies and the different ways that different columns need to be harvested in different tables, do we need to make the calls to the harvesting process more explicit about their inputs? E.g. when we are generating the `balancing_authority` annual entity table, for each column that will end up in the final table, do we need to explicitly list all of the other tables from which those values will be obtained?
* How can we separate the value harvesting from removal of denormalized columns?
* How do we specify which kind of harvesting we're doing (constant, annual, association)?

**Comment by cmgosnell** [comment]
Issues being addressed in #806
