### ISSUE TITLE
plan to move RMI repo modules into PUDL

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/pudl#702]
Because we re thinking about doing another release soon, we should consider moving chunks of the [RMI repository](https://github.com/catalyst-cooperative/rmi-ferc1-eia). This way there will be a way to use these tools with the data release (without needing to run through the ETL process).

Make a plan to move and integrate into PUDL:
- [x] Cleaned depreciation data
- [x] EIA Master Unit List: `make_plant_parts_eia.py` (pretty stable/done)
- [x] EIA & Depreciation Connected: `connect_deprish_to_eia.py` (quasi stable)
- [x] EIA & FERC Connected: `connect_ferc1_to_eia.py` (pretty stable/done)
- [x] Connected Depreciation & FERC: `connect_ferc1_to_eia.py`(under construction)

**Comment by cmgosnell** [comment]
#### Proposal for clean depreciation data:
In general, my proposal is to treat the depreciation studies like any another data set that we pull into the PUDL data base. It just so happens that we have compiled this one and already given it PUDL id's (utility and plant ids). It will be a one table data set.

#### Storage/format:
- We could convert it to a CSV (rn it is a tab in an excel sheet).
- Store the studies Steve collected in a zenodo archive. Set up archive just like all of our other data set archives. This is just a data set that we have created/compiled, so it makes sense to me to treat it like the rest of our data sets.
   - Can we use the zen_storage for this? @ptvirgo ? We are not downloading it from the web, but I assume we could upload it in the same way.
#### Extract
- Simple CSV extract object.
#### Transform
- Transform class could take extracted df, tidy, deal w/ common plant records, fill in missing values. This is basically done right now (over in the rmi repo).
- On the missing values: Different utilities report different things, but generally speaking you can calculate every value from the reported values. So the raw data has all of the columns but nulls. We could calculate everything and store everything. We could fill in only a set of columns that we would need to calculate everything. As in, we would need either "net_salvage" ($'s) or "net_salvage_pct". While we could remove 3-4 calculable columns, I don't think this is the way to go because we more or less need to clean and fill in all columns in order to fill in only the completely necessary columns. So we would be cleaning, filling in, using and then dropping them only to recalculate them in the outputs... all to remove ~3-4 columns. Seems more straightforward to keep them all.
#### Load
- no real change needed here from our standard process.
- we'll need to generate metadata for the table to 
#### Output Layer
- bc this is only one table and I don't believe any normalization would need to happen, integrating this into the outputs would be very simple. We could check in the RMI and other users of these studies if there is any common calculable values that we could include.
#### Overall/Integration
- We'll need the FERC glue tables to exist in order to use the id's as primary keys.
- For the rest of the RMI project, we could interact with this data through a `pudl_out` object

Thoughts @zaneselvans  or anyone??

**Comment by cmgosnell** [comment]
#### EIA Master Unit List
Honestly, this one seems very simple. I don't think we want to integrate this into the database, and thus it should probably stay as an output layer. It is already organized as two classes that interact with a `pudl_out` object. To integrate this into pudl, I'd propose pulling the classes which generate the master unit list into their own analysis module.

The main decision point here is deciding if and where to store the master unit list once it is generated. The master unit list take a while to generate (~15-20 minutes if you are generating the most fleshed out version). More than half of this time is spent in the `get_qualifiers` method... I'm sure we could clean/speed that up. Nonetheless, I've been pickling the output so that I can use it in many other contexts without needing to regenerate it every time. I currently have a little function that takes a path for the master unit list, if it is there, it just grabs the existing master unit list and if it isn't it generates it for you and leaves it at the path. This is not something we generally do right now it PUDL but if we are comfortable integrating something like this in this context it makes working with the data soooo much easier.

**Comment by cmgosnell** [comment]
#### EIA & Depreciation Connected
Similarly to the EIA Master Unit List, this feels pretty simple. It is already organized into classes which interact with `pudl_out`, which we have generally 👍 as analysis modules. There are a few special considerations here:
- the training data/overrides. this process requires training data for the logistic regression model. We need to store it somewhere for the model to access. I would propose putting this somewhere in `pudl/package_data`. It is a two column CSV with several hundred records - it is only 22 kb, so nbd.
- also we need to make a decision about storing the master unit list, because that is required for this module.. like all of the rest of them.

**Comment by zaneselvans** [comment]
As to what depreciation data we store in the database, what if we retained all of the columns as originally compiled, but didn't fill in the missing-but-calculable values, instead leaving that for the output layer? That would be more in line with our current practice of trying primarily to store the original data, and calculating useful derived values in the output layer, and it would make it clear what the original data was.

I think storing this as a single-table (tabular?) datapackage on Zenodo that we can pull from just like all of our other input data makes sense. I think we need to be **especially** dilligent about the metadata on this one, because it is an original work, and pretty unique and valuable. I think we should include references to all of the data sources, so that it can potentially be used in PUC proceedings and stand up to scrutiny / verification.

I don't think I feel great about building the caching of the MUL on disk into the output system. If users want to save the file somewhere and read it in on their own for convenience they can do that already, right? It just seems like the more different layers of cached data there are, more common invalid caches are going to become, and that can be very annoying to debug. Also I still suspect that this can be sped up by a factor of 10 or more if we figure out how to vectorize it.

Are we imagining putting any of these `connect_X_to_Y` modules in the `glue` subpackage?

**Comment by cmgosnell** [comment]
#### EIA & Depreciation Connected
This is the fuzzy matching connection. It relies on overrides. Those overrides are stored right now in the depreciation spreadsheet. I would again propose storing these in a CSV, but right now these overrides are set up in such a way that RMI (or other users) could have semi-easy access to the spreadhsheet outputs and the overrides, so we'll have to think a bit more about how to keep the overrides and the outputs as accessible as is needed. Doing this would require integrating the depreciation studies into pudl (or temporarily creating `pudl_out` access). Also.. requires access to the master unit list - the current process uses pickled dataframe.

#### Connected Depreciation & FERC
This relies on the output from the above module and the output from the "EIA & FERC Connected" process. This is the cumulation of all of the these processes. But the outputs of the previous processes are also useful outputs in and of themselves. I think the most complicated thing here is storage and how to deal with the dependencies.
