### ISSUE TITLE
Fix Incorrectly Mapped FERC-EIA PUDL IDs

### ISSUE THREAD

**Issue by jrea-rmi** [catalyst-cooperative/pudl#736]
A couple of errors in matching FERC respondent_id to utility_id_pudl and utility_id_eia

- Entergy Louisiana LLC: FERC respondent_id 454, matches to utility_id_pudl 114. However, utility_id_eia 11241 is the same utility, but matches utility_id_pudl 107.
- MDU Resources Group: FERC respondent_id 95, matches to utility_id_pudl 178. However, utility_id_eia 12199 is the same utility, but matches utility_id_pudl 193.
- Catalyst Old River Hydroelectric Limited Partnership: FERC respondent_id 18, matches to utility_id_pudl 53. However, utility_id_eia 12199 ("First National Bank - Commerce") also reports Sidney A. Murray Jr hydro as its only plant and appears to be the same utility, but matches utility_id_pudl 6371.
- NSTAR electric Company is respondent_id 309, utility_id_pudl 230. There's no utility_id_pudl for utility_id_eia 54913, which has the same solar plants listed in eia860 as FERC  and appears to be the same utility.

**Comment by jrea-rmi** [comment]
another couple of missing utilities in utilities_eia, found in the EIA ownership table: 

THE ALLEGHENY GENERATING COMPANY is respondent_id 5. The only plant they own is Bath County, which is operated by Virginia Electric & Power. In the EIA Ownership table, they show up as "First Energy Solutions Corp.", utility_id_eia 6458 which doesn't have a pudl ID.

Wheeling Power Company is respondent_id 192. It owns half of the Mitchell (WV) plant, which operated by Kentucky Power Co. The EIA Ownership table shows that this is utility_id_eia 20521, which doesn't have a utility_id_pudl

Cheyenne Light, Fuel and Power Company is respondent_id 403 and only owns parts of plants operated by Black Hills. The EIA Ownership table says their utility_id_eia is 3461, which doesn't have a utility_id_pudl

**Comment by zaneselvans** [comment]
@aesharpe @cmgosnell Did we address this issue?

**Comment by zaneselvans** [comment]
And @bendnorman if you do take on #1069 you might want to look into this if these IDs haven't been dealt with yet.

**Comment by zaneselvans** [comment]
Are these in 2010? Are they related to the messed up owner / operator reporting that @cmgosnell found (See #1116 which was recently fixed)

**Comment by swinter2011** [comment]
The utilities in Jon's first comment have all been correctly matched.

utility_id_eia 6458("first energy services") has PUDL ID 10312 in the most recent version of the matching spreadsheet. First Energy owns both of the parent companies that own The Allegheny Generating Company, which continues to report to FERC, so I don't think we want to assign them the same PUDL IDs.

Wheeling Power Company and Cheyenne Light, Fuel and Power Company need to be linked. It will be no problem to link Brame and Rodemacher as well. I'll check in with Austen tomorrow to make sure I'm updating the right version of the matching spreadsheet.

**Comment by swinter2011** [comment]
I've made these changes and sent the file to Austen to check in.
