### ISSUE TITLE
Heat rate bug for cogen plants

### ISSUE THREAD

**Issue by gschivley** [catalyst-cooperative/pudl#739]
### Describe the bug
It appears that `pudl_out.hr_by_unit()` uses all of the boiler fuel consumption for cogen coal plants, which can lead to very high heat rates.

### Bug Severity
How badly is this bug affecting you?
 - **Medium:** With some effort, I can work around the bug.

### To Reproduce
The pre-packaged `hr_by_unit` appears to use boiler fuel consumption. But the plant-level fuel consumption separates fuel for electricity from total fuel. Some cogen facilities use most of their fuel for heat, leading to heat rates of >150 mmbtu/MWh.

### Expected behavior
Maybe use the plant-level split of fuel for electricity vs total fuel, and apply it to fuel from each boiler? I'm not quite sure what the best work-around is.

**Comment by cmgosnell** [comment]
We're working on this in #975
