### ISSUE TITLE
investigate difference in net get from generation_eia923 vs generation_fuel_eia923 tables

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/pudl#750]
gen table = generation_eia923
gen_fuel = generation_fuel_eia923

I assume this is all a vestige of reporting requirements.

- is gf always bigger?
It is nearly always bigger.
  - when both tables are grouped at the plant/year level and merged together, the net gen in the gen_fuel table is larger or = in 87% of the records
  - 85% of the "missing" net gen (net gen that doesn't show up in in the gen table) is from plants that just don't show up in the gen table at all
![image](https://user-images.githubusercontent.com/25487998/93609576-07d68300-f99a-11ea-93fe-f8aba8283898.png)
- what is the scale of the difference?
  - 58% of the net gen reported in the gen_fuel is reported in the gen table
  - About 9% of plants have records which both have data in both tables and have a non-zero difference between the net gen. 
- does it change over time?
  - It looks like it gets much cleaner after 2014 (i know, i know this graph is very ugly)
![image.png](https://images.zenhubusercontent.com/5d8a28980d75970001f88513/8b19fb0f-cc6b-4cf3-a0b2-d3eb41584f89)
  stacked version: 
![image.png](https://images.zenhubusercontent.com/5d8a28980d75970001f88513/fb03efb4-bc5b-4ec9-a30f-09a4ccd3dce6)
- how often are the missing gens different PMs?
  - % of plants w/ gen v gen_fuel diff that have >1 prime mover: 91.39%
  - % of plants for which the generators missing from the gen table are all only one prime_move_code: 92.07%

**Comment by zaneselvans** [comment]
Have you made a plot of the annual ratio of generation reported in one table vs the other?

**Comment by cmgosnell** [comment]
It is kinda hard to see in one graph:
![image](https://user-images.githubusercontent.com/25487998/93629909-12534580-f9b7-11ea-8936-7e66b3095d71.png)

But here they are broken out by these chunks of time:
![image](https://user-images.githubusercontent.com/25487998/93630214-9e656d00-f9b7-11ea-8f35-83e58dca54fd.png)
![image](https://user-images.githubusercontent.com/25487998/93630162-842b8f00-f9b7-11ea-8c5b-abe8e9fd360b.png)

**Comment by zaneselvans** [comment]
I was thinking just a line plot, with time on the x axis, and ratio on the y axis.

**Comment by cmgosnell** [comment]
![image](https://user-images.githubusercontent.com/25487998/93632780-e9817f00-f9bb-11ea-9af9-6b5f2844afbc.png)

**Comment by zaneselvans** [comment]
Okay great, so it seems like the overwhelming majority of the issue here is the lack of combustion turbine reporting prior to May 2014.

**Comment by cmgosnell** [comment]
Hm.. well, no. This is only the plants which had some reporting to the gen table. I remade it w/ a note.. and made the second w/ all of the missing net gen. Maybe it is going up over these last few years due to more gas on the system?

![image](https://user-images.githubusercontent.com/25487998/93634392-89400c80-f9be-11ea-8e94-3aad4e54fd3a.png)
![image](https://user-images.githubusercontent.com/25487998/93634430-952bce80-f9be-11ea-854d-401f3ab1ff16.png)
