### ISSUE TITLE
Speed up EPA CEMS datapackage.json validation

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#765]
Currently, the validation of the `datapackage.json` file is very slow, if you have a fast net connection, it can be the slowest part of downloading the full EPA CEMS dataset (1300 resources) because the *entire* datapackage.json file is validated after the download of each resource.  The combination of small resources, and a large number of them (resulting in a big datapackage.json file) creates this problem.
* Can we limit the validation to looking only at the newly downloaded resource? We could, but all of the resource descriptors are being re-written each time a new download happens, so this will miss many opportunities for errors.
* Can we only do a validation of the entire data package only when the whole dataset is being validated?  We could, but we'd need to make sure that this kind of validation is done automatically at various points in the process. Would work fine for the `--validate` option on the script.
* Can we only validate after all the resources have been gotten? Again this would work fine in the bulk download script context, but in the download-as-you-go programmatic context, when are you "done" downloading the data? We'd need to incorporate the post-download validation into each application of the programmatic download process.

**Comment by cmgosnell** [comment]
no longer relevant
