### ISSUE TITLE
FERC Form 1 Field Definitions

### ISSUE THREAD

**Issue by mcraig10** [catalyst-cooperative/pudl#769]
Hello,

A student and I are newcomers to PUDL & FERC Form 1. We are trying to extract remaining or accrued depreciated asset value. I have successfully run PUDL and found your database design diagram of all the table names, but we are at a loss as to where we can find explanations and definitions for what each column means. E.g., what exactly is "cost_per_kw" in the f1_steam table? I emailed FERC to no avail yet. Do you have any such resource? Thanks.

**Comment by zaneselvans** [comment]
If you are intent on using the cloned FERC Form1 database -- which is just a direct copy of whatever appeared in the published FERC Form 1 FoxPro database -- then your best bet is to look at a PDF of the blank FERC Form 1 alongside the database tables you're interested in, and try to figure out which columns & rows in the PDF correspond to the columns that you see in the database. There's **[a CSV file in the docs directory](https://github.com/catalyst-cooperative/pudl/blob/master/docs/ferc/form1/ferc_form1_database_notes.csv)** within the repository that list which DBF files correspond to which database table names, and pages on the paper form.

For the subset of the FERC 1 tables that we've organized and pulled into the PUDL database, there are metadata which explain what each column contains. We really need to get this posted obviously on the web. Right now it will be output as part of the tabular datapackage that the ETL process generates. Unfortunately the field and table comments are not pulled into the SQLite database metadata that is generated from those data packages.

However, we have also been compiling depreciation data separately, both from the FERC Form 1 and from various depreciation proceedings at PUCs across the country, which might be more immediately useful to you. @swinter2011 and @cmgosnell have been working on that **[in this repository](https://github.com/catalyst-cooperative/rmi-ferc1-eia)** in collaboration with the **[Rocky Mountain Institute](https://rmi.org)**.

**Comment by cmgosnell** [comment]
We have [data dictionaries](https://catalystcoop-pudl.readthedocs.io/en/latest/data_dictionaries/pudl_db.html) for the FERC tables we have integrated into PUDL. For the raw tables, we have very [brief descriptions](https://catalystcoop-pudl.readthedocs.io/en/latest/data_dictionaries/ferc1_db.html) but nothing more.
