### ISSUE TITLE
Add official EIA861 2019 data

### ISSUE THREAD

**Issue by aesharpe** [catalyst-cooperative/pudl#789]

**Comment by karldw** [comment]
Yes! There's an EPA API you can query. 

Here's searching for plant 880023 in the CEMS data (CAMDBS is "Clean Air Markets Division Business System"): https://ofmpub.epa.gov/enviro/frs_rest_services.get_facilities?pgm_sys_acrnm=CAMDBS&output=JSON&pgm_sys_id=880023

If you hit IDs with no results, you can remove `pgm_sys_acrnm=CAMDBS` and search for an ID across all EPA facility datasets.

And here's a code snippet to query and return a one-row pandas dataframe, slightly tweaked from https://github.com/catalyst-cooperative/pudl/issues/178#issuecomment-460005289

```python
from json import JSONDecodeError
from functools import lru_cache
import requests
import pandas as pd

# Cache this so we don't have to keep loading the same page
@lru_cache(512)
def download(url):
    return requests.get(url)

def one_plant_info(plant_id_eia):
    url_template = "https://ofmpub.epa.gov/enviro/frs_rest_services.get_facilities?pgm_sys_acrnm=CAMDBS&output=JSON&pgm_sys_id={}"
    url = url_template.format(plant_id_eia)
    request = download(url)
    if request.status_code > 399:
        print("Failed to retrieve data for ", plant_id_eia)
        return None
    try:
        json_data = request.json()["Results"]["FRSFacility"]
    except (JSONDecodeError, KeyError):
        print("Failed to parse json info for ", plant_id_eia)
        return None
    return pd.json_normalize(json_data)

one_plant_info(880023)

```

**Comment by cmgosnell** [comment]
thank you so much! this is great!

Weirdly the only plant id that was missing w/ the 2019 data seems to be `880109` from OH, which appears to have no data from the api.

**Comment by karldw** [comment]
Strange that it's not in the API -- looks like it's a paper plant? Pulling from their monitoring plan here: https://gaftp.epa.gov/dmdnload/xml/mp/880109_MP.zip

> Pratt Paper (OH), LLC is submitting this monitoring plan within the ECMPS Client Tool to serve as the Low Mass Emissions (LME) Unit Certification Application for Boiler #&#8288;1. The application is also being submitted hardcopy to USEPA Clean Air Markets Division, USEPA Region 5, and Ohio EPA. Ohio EPA will also receive a copy uploaded to the eBusiness Air Services web portal.
