### ISSUE TITLE
Use Docker to run software & data release

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#798]
Use docker to containerize the ETL process rather than having people run several different scripts and do a bunch of software environment setup which they hate and are bad at.

**Comment by rousik** [comment]
We can achieve this goal in a variety of ways. Ideally, we would do the following steps in the container:
1. Run the ETL
2. Validate output files (includes converting csv files to sqlite and/or parquets)
3. Upload the resulting files somewhere (perhaps storage bucket?)

There are open questions about this process, specifically:
1. are we expecting to run container locally or on gcloud? (eventually we might want to spin up multiple containers to enable parallel execution)
2. where to upload the resulting files 
3. how much setup can be contained in the docker image itself and how much needs to be outside (e.g. gcloud setup)

There may be some upcoming changes to the landscape, particularly if we add prefect as an orchestrator as this may take over control of the runtime to some degree.

**Comment by zaneselvans** [comment]
The nightly builds have pretty much taken care of this.
