### ISSUE TITLE
integrate YTD EIA 923 updates in ETL

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/pudl#813]
- [x] the 923M files are already being scraped by the datastore because the final annual and monthly update are all in the same page :-)  
- [ ] map metadata
  - the columns, tabs and file names are self explanatory here
- [ ] ensure extract step runs and update accordingly
- [ ] ensure transform step runs and update accordingly

**Comment by cmgosnell** [comment]
duplicate w/ #1794  ooops i should have looked before making a new issue

**Comment by zaneselvans** [comment]
The monthly year to date data and the early release data are different aren't they? Some respondents report month by month, others report monthly data once a year, and still others report only annual data.
