### ISSUE TITLE
Apply uniform canonical dtypes to dataframes in pudl_out

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/pudl#818]
Right now we standardize our dtypes with `helpers.convert_cols_dtypes` in the transform step, but there isn't a standard dtype conversion happening in the output layer. As you'd expect, his is leading to dtype errors in the outputs. All the nullable ints are turned into floats, the zips are turned into ints. It is all bad and annoying. We can fix this! I believe I have tried once w/ some EIA tables and I recall there being a problem with one column from one of the tables... maybe plants... that make it not 100% straightforward.

**Comment by rousik** [comment]
Do we envision running the `convert_cols_dtypes` on everything before it gets dumped to csvs? I suppose that the prefect-ized etl should allow us to easily plug this step there.

**Comment by zaneselvans** [comment]
See also the discussion in [this comment](https://github.com/catalyst-cooperative/pudl/pull/1377#discussion_r772366742) about using the `format_df` method in the Metadata classes.

**Comment by zaneselvans** [comment]
With the move away from using `PudlTabl` / `pudl_out` entirely this isn't an issue any more, though appropriate data types will still need to be applied when reading tables out of the database. See #1973
