### ISSUE TITLE
Re-convert column datatypes for output tables

### ISSUE THREAD

**Issue by aesharpe** [catalyst-cooperative/pudl#819]
Column datatypes are confirmed/forced post-transform, but not always after extraction from the database for the output tables. This causes problems for columns that rely on datatype to depict accurate information. EX: `zip_code` columns that are zero-padded and need to be converted to strings and then fed additional prefix zeros. The helper function `zero_pad_zips` helps during the transform phase and might also help during the output phase.

Also important to ensure that the datatype conversions are the same during the transform step as the output step so as not to have dual dtype data locations.

**Comment by zaneselvans** [comment]
With the move away from using `PudlTabl` / `pudl_out` entirely this isn't an issue any more, though appropriate data types will still need to be applied when reading tables out of the database. See #1973
