### ISSUE TITLE
Documentation page for EIA-923

### ISSUE THREAD

**Issue by aesharpe** [catalyst-cooperative/pudl#834]

**Comment by MichaelTiemannOSC** [comment]
This comment refers to a documentation challenge for EIA_923: how to reconcile generator-based net_generation_mwh data and generation_fuel-based net_generation_mwh data: https://github.com/catalyst-cooperative/pudl/issues/595#issuecomment-826369709

The documentation should help the reader understand why in 2012, Plant #3 (Barry) reports 13,262,529 MWh via the generation_fuel table, but when we add up the generators we only find 8,170,220 MWh net generation.  Surely the documentation can help us understand which data is tell us what, and thus how to make best use of what's available for a given use case.
