### ISSUE TITLE
Integrate EIA860 data back to 2001 (dbf files)

### ISSUE THREAD

**Issue by aesharpe** [catalyst-cooperative/pudl#848]
2001-2003 EIA860 files are dbf. We'll need to create a little dbf reader to suck those in!

Extend the `pudl.extract.eia860` module to be able to use a mix of Excel and DBF extractors to read in raw dataframes and concatenate them together before handing off to the transform modules.

**Comment by bendnorman** [comment]
- [ ] 2003
- [ ] 2002
- [ ] 2001
