### ISSUE TITLE
Many resources are missing metadata

### ISSUE THREAD

**Issue by ezwelty** [catalyst-cooperative/pudl#855]
Quite a few resources listed in `constants.pudl_tables` have no metadata in `/package_data/meta/datapkg/datapackage.json`. Is there a description of the desired output format that I am missing? Should I infer draft metadata for these from current output?

### `glue`

- `plants`: Should this be `plants_pudl`, which is listed in `datapackage.json`?
- `plants_ferc`: Should this be `plants_ferc1`, which is listed in `datapackage.json`?
- `utilities`: Should this be `utilities_pudl`, which is listed in `datapackage.json`?
- `utilities_ferc`: Should this be `utilities_ferc1`, which is listed in `datapackage.json`?

### `eia861`

- advanced_metering_infrastructure_eia861
- balancing_authority_eia861
- demand_response_eia861
- demand_side_management_eia861
- distributed_generation_eia861
- distribution_systems_eia861
- dynamic_pricing_eia861
- energy_efficiency_eia861
- green_pricing_eia861
- mergers_eia861
- net_metering_eia861
- non_net_metering_eia861
- operational_data_eia861
- reliability_eia861
- sales_eia861
- service_territory_eia861
- utility_data_eia861

### `ferc714`

- adjacency_ba_ferc714
- demand_forecast_pa_ferc714
- demand_hourly_pa_ferc714
- demand_monthly_ba_ferc714
- description_pa_ferc714
- gen_plants_ba_ferc714
- id_certification_ferc714
- interchange_ba_ferc714
- lambda_description_ferc714
- lambda_hourly_ba_ferc714
- net_energy_load_ba_ferc714
- respondent_id_ferc714

**Comment by zaneselvans** [comment]
All of the `eia861` and `ferc714` tables are just now being integrated, and we haven't compiled metadata for them yet, but we should! I think @aesharpe may have some portion of the `eia861` metadata already.

I think you're right on the glue table mappings, but there may be some unpleasant references to resolve elsewhere in the code and the EIA/FERC Plant/Utility mapping spreadsheet to get them all to have consistent names. But I think we should do that too.

**Comment by cmgosnell** [comment]
> plants: Should this be plants_pudl, which is listed in datapackage.json? 
 plants_ferc: Should this be plants_ferc1, which is listed in datapackage.json?
utilities: Should this be utilities_pudl, which is listed in datapackage.json?
utilities_ferc: Should this be utilities_ferc1, which is listed in datapackage.json?

Yes to all of these!

**Comment by ezwelty** [comment]
@cmgosnell I updated the metadata for the `glue` tables. Metadata for `ferc714` and `eia861` tables can be added as needed in the future.
