### ISSUE TITLE
Filled vs. unfilled pudl_out.gen_eia923() have different columns

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#860]
We have the option of filling in missing `net_generation_mwh` values in the `pudl_out.gen_eia923()` method, which is enabled by setting `fill_net_get=True` in the creation of the `pudl_out` object.

The shape / content of the dataframe which is returned by the `pudl_out.gen_eia923()` method is currently different, depending on whether the filling is enabled. If the idea is to provide two versions of the same output, one that's the data as reported, and another that has missing values filled in, the output from both should have the same form so they can be used interchangeably.

Here's what they look like right now:

### Unfilled:
* report_date
* plant_id_eia
* plant_id_pudl
* plant_name_eia
* utility_id_eia
* utility_id_pudl
* utility_name_eia
* generator_id
* net_generation_mwh

### Filled:
* plant_id_eia
* generator_id
* report_date
* net_generation_mwh
* fuel_consumed_mmbtu

**Comment by cmgosnell** [comment]
haha i forgot a `gen =` [here](https://github.com/catalyst-cooperative/pudl/blob/97da0b35fabcdbb12af2d3a2dc3e66a039b74128/src/pudl/analysis/allocate_net_gen.py#L180).

But I didn't know what to do about the `fuel_consumed_mmbtu` column. It is useful to have this allocated gen-based consumption but it normally lives in the generation fuel table.

**Comment by cmgosnell** [comment]
done
