### ISSUE TITLE
Speed up EPA CEMS processing

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#877]
After seeing the big speedups that @ezwelty was able to eek out of the FERC 714 hourly demand ETL process and missing value imputations, I've become suspicious that the EPA CEMS ETL does not need to take anywhere near as long as it currently does.  I did some poking around to see where the biggest bottleneck is, and it seems to be the datastore -- not the extract or transform methods. I know @rousik has also been messing around with a different datastore setup on the prefect branch too.

I didn't track down the source of the slowness, but I wouldn't be surprised if it's my fault, and related to the re-validation of the `datapackage.json` file whenever it's accessed, or if there's some issue where the entire year's worth of per-state data is unzipped separately for each month's worth of data being extracted.

For example, the following code is essentially reading 70,000 rows out of a zipped CSV file, and it takes 21 seconds. Clearly something is very wrong.

```py
%%time
import pudl
import pathlib
import sqlalchemy as sa

pudl_settings = pudl.workspace.setup.get_defaults()
pudl_engine = sa.create_engine(pudl_settings['pudl_db'])
epacems_years = [2019, ]
epacems_states = ["id", ]

ds = pudl.extract.epacems.EpaCemsDatastore(
    pathlib.Path(pudl_settings["pudl_in"]),
    sandbox=False
)

epacems_raw_dfs = pudl.extract.epacems.extract(
    epacems_years,
    epacems_states,
    ds
)

raw_dfs = {}
for df in epacems_raw_dfs:
    raw_dfs.update(df)
```

Running the same code for 2019 Texas data, which has 3.2 million records, takes 32 seconds. So it seems like there's probably a big fixed overhead of ~20 seconds per state-year, which would add up to almost 7 hours across 25 years and 50 states.

**Comment by rousik** [comment]
I'm currently trying to analyze impact of parallel dask execution by comparing one year worth of epacems (10 or all states) on the `prefect` branch. I should be able to run the same thing with `sprint29` and do three way comparison that should tell us how much the datastore refactoring helped. I *believe* I have done the right thing by only opening the zip archive once for each (state, year) combo. 

The current (`sprint29`) code is unfortunately going to open and parse the archive repeatedly, once for every month. See [this method.](https://github.com/catalyst-cooperative/pudl/blob/150342295bbb5e577650cf0e9940fdae10c492ae/src/pudl/extract/epacems.py#L21)

**Comment by rousik** [comment]
I'm happy to take over this issue as this is pretty close to my current focus.

**Comment by rousik** [comment]
When running for 1 year worth of data with 10 states (first 10 alphabetically) the timing of epacems ETL is as follows:

1. `sprint29` branch ~ 8 minutes
2. `prefect` branch with serial task execution ~ 5 minutes
3. `prefect` branch with default dask executor ~ 3.5 minutes

Merging `prefect` into `sprint29` should already give us noticeable speed-up (and I guess that this may become even more significant when we process larger datasets). With dask we can also easily access horizontal scaling (add more dask workers for more benefits from parallel execution)

**Comment by zaneselvans** [comment]
I'm kind of surprised it only dropped from 8 minutes to 5 minutes. But maybe there are other bottlenecks besides the multiple unzippings.

**Comment by zaneselvans** [comment]
This has been superceded by other refactoring around CEMS.
