### ISSUE TITLE
Zenodo http requests are dysfunctional when we get rate-limited

### ISSUE THREAD

**Issue by rousik** [catalyst-cooperative/pudl#879]
Zenodo has rate-limiting feature where http requests can be rejected with 429 response code. When we run with dask executor (allowing massive paralellism) and not fully populated local caches (requiring us to pull resources from zenodo), our naive http retry (try again immediately) will not work. Once we hit the rate-limiting threshold, retries will make matters worse until the entire ETL fails.

There are several possible solutions and/or workarounds we could do:

1. Rate limiting the data fetching might be a way to prevent this, but this may not be trivial, because data fetching is not clearly delineated (we effectively don't know what we will need to fetch until extract tasks ask for it) and because the tasks will be distributed (cross-task synchronization may be difficult to implement)
2. Implementing exponential back-off when 429 is encountered - instead of immediate retry, wait some random time that increases with every failure. This should ease the pressure on zenodo.

In a way, the simplest and most practical workaround to this is to not rely on zenodo and pull resources from GCS instead.

**Comment by zaneselvans** [comment]
The more we've interacted with it, the more it's felt like the Zenodo API isn't actually intended to be used programmatically. I kind of think we should move toward treating Zenodo as cold-storage -- a resource of last resort that ensures (in conjunction with the released & archived code version) that everything can be reproduced even years down the line if need be, but that for most day-to-day use we'll be using GCS or local versions of the data.

**Comment by rousik** [comment]
Turns out that http adapters will already do exponential backoff. The problem I'm experiencing is permanent black listing from Zenodo :(
