### ISSUE TITLE
pudl_datastore: allow for synchronizing caching layers

### ISSUE THREAD

**Issue by rousik** [catalyst-cooperative/pudl#882]
`datastore_refactor` branch contains `LayeredCache` which allows use of variety of caching layers (GCS and local filesystem). It would be useful to have a feature where you can run `pudl_datastore` such that it synchronizes content to the closest cache layer (e.g. either from zenodo to GCS or from GCS to local filesystem). This could be useful for development scenarios where we do not want to hit GCS too frequently but where we do not necessarily want to have zenodo rate-limiting/rejections.

**Comment by zaneselvans** [comment]
I think something like this is now working, and the multi-layer cache makes life much easier, with Zenodo really just used as cold-storage.
