### ISSUE TITLE
Investigate use of fsspec for local-vs-cloud data storage

### ISSUE THREAD

**Issue by rousik** [catalyst-cooperative/pudl#886]
As we are refactoring the pipeline to support running in cloud, variety of storage can either happen on a local disk or using cloud storage (e.g. GCS). This applies to Datastore, temporary storage of pipeline data (e.g. csv files) and final datapackage archives.

When implementing temporary DataFrame storage I have found out that `pd.to_pickle` supports variety of storage backends out of the box and it mentions `fsspec` library. Perhaps there is something that supports both local and remote storage mechanisms such that we won't have to implement this by hand in variety of places.

**Comment by zaneselvans** [comment]
I've been coming across [`fsspec`](https://filesystem-spec.readthedocs.io/en/latest/) a lot in reading about the Intake library too. It's got a bunch of built-in local caching mechanisms too, for a variety of different kinds of caches -- whole files, chunks of files, directory structures, etc. which Inake can be told to make use of with remote file access methods.  Seems very useful. The drivers I've been investigating for our purposes are:
* [intake-parquet](https://intake-parquet.readthedocs.io/en/latest)
* [intake-sql](https://intake-sql.readthedocs.io/en/latest/)
* also [DirCache](https://filesystem-spec.readthedocs.io/en/latest/api.html#fsspec.dircache.DirCache) to cache partitioned Parquet datasets.

**Comment by rousik** [comment]
Right now the prefect code does a lot of if-else branching depending on whether the files should be written to a local disk or a remote storage, if we use fsspec and correctly code around it, we might simply set the corresponding paths (e.g. parquet_dir and datapkg_dir) and let the code write the files to where it should.

**Comment by bendnorman** [comment]
We ended up migrating to dagster. See #1487 for the reasoning.
