### ISSUE TITLE
Integrate EIA-860 Schedule 6 and EIA-923 Schedule 8 (Emissions Controls)

### ISSUE THREAD

**Issue by grgmiller** [catalyst-cooperative/pudl#889]
Currently, environmental control data from the EIA-860 schedule 6 and EIA-923 Schedule 8 do not seem to be included in the PUDL data packages or databases. In the raw EIA data downloads, these files are:
- 6_1_EnviroAssoc_Y20XX
- 6_2_EnviroEquip_Y20XX
- EIA923_Schedule_8_Annual_Environmental_Information_20XX_Final

However, they contain some tables and columns that will be necessary for the eGRID project, specifically:
 - 860 Schedule 6A, 'Emissions Control Equipment', 'Boiler / Particulate Control Associations', 'Boiler / SO2 Control Associations', 'Boiler / NOx Control Associations', 'Boiler / Mercury Control Associations'
 - 860 Schedule 6B, 'Emission Standards and Control Strategies'
 - 860 Schedule 6C, 'Boiler Information - Design Parameters'
 - 923 Schedule 8C, 'Air Emissions Control Info'

The type of data that we will need for each boiler for the eGRID project include:
- firing type (6C)
- bottom type (6C)
- Existing mercury control strategy (6B)
- S02 control technology / equipment type (6A)
- NOx control technology / equipment type (6A)
- Mercury control technology / equipment type (6A)
- Particulate Matter control technology / equipment type (6A)

It appears that there is not necessarily a 1:1 association between boiler ID and control equipment (sometimes there are several NOx control equipment types on a single boiler), so this might not fit in the `boilers_entity_eia` table.

**Comment by zaneselvans** [comment]
This seems like it might also be important information for distinguishing major emissions control investments from ongoing capital additions to plants, and for a variety of environmental justice / air pollution estimation applications.

**Comment by grgmiller** [comment]
See https://github.com/catalyst-cooperative/pudl/issues/1189#issuecomment-1180768753 for info on integrating these sheets

**Comment by zaneselvans** [comment]
I think all of the tables you've broken out here is now covered in the issues that are tracked by #1189 so I'm going to close this, but please take a look and let us know if something has been left out and we'll add it to the list(s)!

I took your #1950 and turned it into #2447
