### ISSUE TITLE
Run January 2021 data release

### ISSUE THREAD

**Issue by rousik** [catalyst-cooperative/pudl#895]
To demonstrate progress and allow grant reviewers to interact with the recent work, we should be able to run the reproducible data release with the most recent codebase (sprint29 with prefect).

Ideally, this would be ready within 1-2 weeks when the grant is expected to be reviewed.

Tasks that we would like to accomplish as part of this efforts are:

- [ ] Merge `prefect` branch into `sprint29` after ensuring that it doesn't cause changes to the outputs 
- [ ] Switch epacems to use parquet files instead of generating csv-based datapackage
- [ ] Populate pudl database as part of the ETL pipeline run
- [ ] Integrate data validation (of pudl database) into ETL pipeline run
- [ ] Ensure that gcs datastore cache has fails gracefully (is skipped) if we lack authentication or if the bucket does not exist (it should already fail gracefully when the individual files are not present).

**Comment by zaneselvans** [comment]
Closing this issue since we're way beyond that timeframe and need to have a renewed conversation about how to get the Prefect ETL code integrated, and change how output data is generated (direct to SQLite + parquet, rather than Data Packages)
