### ISSUE TITLE
Enable Diskless ETL

### ISSUE THREAD

**Issue by rousik** [catalyst-cooperative/pudl#899]
Currently the ETL runs assuming that all the output data will be dumped to local disk. This is not very suitable for cloud execution in a container (we need to export the data to storage bucket) and also prevents distributed execution because some codepaths will read files from disk (this is not possible if you run the write and read tasks on different machines).

This bug is to track the effort to refactor our use of local disk and replace it with something more generic like `fsspec`.

Below is list of things that will likely cause problem and will need fixing:
- `pathlib.Path` does not seem to support non-local files and it breaks them (e.g. `gs://somepath` is turned into `gs:/path` when fed through `Path`)
- creating directories may not be necessary when we use non-local filesystem. fsspec should be able to do that at file open thus simplifying the code
- review cases where we need to write and re-read files from disk. This may have been an "easy hack" but perhaps it is not necessary to do that.

**Comment by bendnorman** [comment]
We ended up migrating to dagster. See #1487 for the reasoning.
