### ISSUE TITLE
Create a PUDL user Docker container

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#904]
Create a Docker image that can:
* Be archived alongside the SQLite and Parquet data to let users access them locally via Jupyter
* Specify the software environment for users on our 2i2c JupyterHub

We currently have a container on DockerHub that's built with `repo2docker` based on the `environment.yml` file in the https://github.com/catalyst-cooperative/pudl-tutorials repository. However, we don't know how to run it independent of running repo2docker to create it.  We also don't know how to mount external files and directories into it, so that the user has access to the SQLite and Parquet datasets. So, we need to figure those things out.

These problems are also touched on [in this issue in the 2i2c pilot-hubs repo](https://github.com/2i2c-org/pilot-hubs/issues/184)

**Comment by zaneselvans** [comment]
Okay, assuming you have a directory named `pudl_dir` in your current directory, and it contains all your pudl working data (the `sqlite`, `parquet`, and `data` directories) then running this command should get you a notebook server and the tutorial notebooks and let you run them all locally.

```bash
docker run \
    --mount type=bind,source=$(pwd)/pudl_dir/.,target=/home/jovyan/shared \
    --publish 127.0.0.1:8888:8888 \
    catalystcoop/pilot-hub:latest jupyter lab --ip 0.0.0.0
```

We should think a little about what the easiest setup for the user will be, to use this for local analysis downloading the container on the fly, and also using an archive of everything. We could replace the `notebooks` directory that's inside the container with an externally mounted `notebooks` directory so that the user can put whatever notebooks they want there, and also see the files that they output from any of those notebook.

**Comment by rousik** [comment]
Perhaps using docker-compose might be the best option as that could have
the right parameters (mounts and exposed ports) set correctly.

**Comment by zaneselvans** [comment]
Ah, okay, so `docker-compose` lets you set these kinds of parameters for a single container, it's not just about making multiple containers work together.

**Comment by zaneselvans** [comment]
Okay I created a `docker-compose.yml` and a `.env` file to set some environment variables. That's much better.
