### ISSUE TITLE
Set up cloud environment for pudl_etl

### ISSUE THREAD

**Issue by rousik** [catalyst-cooperative/pudl#918]
The goal of this effort is to set up our cloud environment such that it will be possible to run `pudl_etl` completely in the cloud.

Here's the basic set of tasks needed:

- [ ] Set up gcs bucket containing zenodo cache
- [ ] Set up short-lived gcs bucket for pipeline cache (dataframes and task results, automatic garbage collection of stale objects)
- [ ] Set up gcs bucket for pipeline outputs (datapackages and parquet files)
- [ ] Document how to run ETL on cloud
- [ ] Create github action that can be used to kick off data release on cloud

**Comment by rousik** [comment]
wiring this to github action is a stretch-goal but very useful from toil-reduction and ease-of-use standpoint

**Comment by zaneselvans** [comment]
One way or another, much of this has been implemented with nightly builds.
