### ISSUE TITLE
Error loading into a local SQLite database

### ISSUE THREAD

**Issue by jgrooviest** [catalyst-cooperative/pudl#937]
I am following the quick start instructions to creating a local SQLite database from the [ferc1, epaipm] databases (I didn't want to download the entire CEMS database after reading that it is 100x the size of the other databases), and when I try to supply my Anaconda prompt with the script (without the forward slashes, thus on one line),

> datapkg_to_sqlite \
    -o pudl-work/datapkg/pudl-example/pudl-merged \
    pudl-work/datapkg/pudl-example/ferc1-example/datapackage.json \
    pudl-work/datapkg/pudl-example/epaipm-example/datapackage.json

I get an error returned that appears to be due to the `-o` argument:

> usage: datapkg_to_sqlite [-h] [--pkg_bundle_name PKG_BUNDLE_NAME]
> datapkg_to_sqlite: error: unrecognized arguments: -o pudl-work/datapkg/pudl-example/pudl-merged pudl-work/datapkg/pudl-example/ferc1-example/datapackage.json pudl-work/datapkg/pudl-example/epaipm-example/datapackage.json

This is after a successful build using `pudl_etl pudl-work/settings/etl_example.yml`, so I'm not entirely sure what is the problem. 

Operating system: Windows 10
Python version: 3.8.8
conda environment: a fresh environment setup based on:
> conda create --yes --name pudl --channel conda-forge \
    --strict-channel-priority python=3.8 \
    catalystcoop.pudl jupyter jupyterlab pip

Let me know if you need more info.

**Comment by zaneselvans** [comment]
Hey sorry, the README is not up to date. You can run `datapkg_to_sqlite --help` to see the script's current usage. We're in the process of updating the docs right now. It should work if you get rid of the `-o` flag and its argument (it just merges the datapackages together in a temporary location now).

**Comment by jgrooviest** [comment]
Is there an intermediate step to build the datapackage? After running the pudl_etl script, I get directories with individual datapackages, but running `datapkg_to_sqlite` with the path to the individual `datapackage.json` files returns this error:

> usage: datapkg_to_sqlite [-h] [--pkg_bundle_name PKG_BUNDLE_NAME]
datapkg_to_sqlite: error: unrecognized arguments: pudl-work/datapackage/pudl-example/ferc1-example/datapackage.json pudl-work/datapackage/pudl-example/epaipm-example/datapackage.json

Documentation is asking for --pkg_bundle_name. I'm not sure what exactly this is supposed to be.

**Comment by zaneselvans** [comment]
Ah sorry, can you tell me more about how you're trying to run everything? It sounds like you're downloading the processed data from Zenodo maybe? But then also trying to run the ETL?  Which data do you want access to? Have you checked out https://data.catalyst.coop -- it will let your browse through a lot of the data online. What years of data do you need access too, and which datasets? I apologize that the quickstart is so out of date at the moment.

**Comment by jgrooviest** [comment]
No worries about the quickstart/readme!

I'm going to see about the online browser and whether that will work. I guess it wasn't entirely clear what the python package added, so I figured it was needed to access or select data.

**Comment by zaneselvans** [comment]
In general we're moving away from expecting users to run the whole data processing pipeline on their own, and trying to publish data that's ready to use. The bulk of the code in the package is dedicated to the pipeline.  There are also some analyses that are built on top of the data it produces.

We also have a JupyterHub set up with a recent version of all of the outputs and the software installed, in collaboration with https://2i2c.org if you would like to give that a try.

**Comment by jgrooviest** [comment]
Got it. I'll take a look at the JupyterHub if the online browser doesn't work for me. 

Thanks!
