### ISSUE TITLE
Issue running conda setup for dev

### ISSUE THREAD

**Issue by cschloer** [catalyst-cooperative/pudl#949]
### Describe the bug
Running the conda dev development commands described [here](https://catalystcoop-pudl.readthedocs.io/en/latest/dev_setup.html#create-and-activate-the-pudl-dev-conda-environment) results in an error for me.

```
(base) ~/Projects/catalyst/pudl (sprint31) $ conda env create --name pudl-dev --file devtools/environment.yml
Collecting package metadata (repodata.json): done
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                               /  
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                               -  

UnsatisfiableError: The following specifications were found to be incompatible with each other:
....
```

I've truncated the rest because it goes on for a while describing the conflicts. I can add it if it's not reproducible.

### Bug Severity
How badly is this bug affecting you?
 - **Low:** I'm able to just install dependencies on my own I believe.

### To Reproduce
Running
```
conda config --set channel_priority strict
conda env create --name pudl-dev --file devtools/environment.yml
```

from the sprint31 branch

### Expected behavior
I would expect it to return without an error and create the pudl-dev environment.

### Software Environment?
 - OS: Ubuntu 20.04.2
 - Python version 3.8.8
 - How did you install PUDL? git clone

**Comment by zaneselvans** [comment]
Hmm, okay yes, if I use `conda` I also get a failure here. But if I use `mamba` (which is what I typically do) it succeeds. If you want to switch to `mamba` for environment creation and updating for the moment, I think it should work. But we can try and track down the issue here in parallel.

**Comment by zaneselvans** [comment]
Okay, I have pushed an update to the setup.py and environment.yml files which seems to result in an environment that is solvable by both conda and mamba. Sorry for the hassle, and thanks for catching this! I've created issue #950 to integrate conda environment creation into our CI so this can't happen again.

**Comment by cschloer** [comment]
Great thanks! No worries at all.
