### ISSUE TITLE
Data validation failure due to non-unique plant_id_pudl in a single plant_id_ferc1

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#954]
A modest number of `plant_id_ferc1` values (the algorithmically assigned IDs which tie together records across years in the `plants_steam_ferc1` table) are showing up in association with **more than one** `plant_id_pudl` value, which in theory should never happen. This could either be due to a manual mapping error in the eia-ferc1 glue, or it could be that the algorithm is incorrectly associating records that do not really belong to the same PUDL plant.

Previously there was a single instance of this kind of failure, and so we marked the data validation test `xfail` but now there are... 55 of them, and we don't know when / why they have appeared.  Note that the `plant_id_ferc1` values below may not be identical if you run the ETL again, since they are algorithmically assigned.  The `plant_id_pudl` values should be consistent though. Also note that it's fine for a single `plant_id_pudl` to have several different `plant_id_ferc1` values inside it, but not vice versa.

```
2021-03-24 15:18:07 [    INFO] test.validate.plants_steam_ferc1_test:125 Found 55 plant_id_ferc1 values associated with 104 non-unique plant_id_pudl values.
```
```py
plant_id_ferc1: [
    11, 52, 75, 76, 104, 105, 117, 118, 190, 212, 219, 244, 283, 309, 382, 383, 393, 457,
    547, 548, 549, 550, 604, 674, 676, 686, 690, 714, 731, 744, 775, 779, 815, 853, 936,
    1068, 1072, 1090, 1112, 1135, 1175, 1197, 1239, 1263, 1373, 1395, 1405, 1408, 1441,
    1545, 1578, 1587, 1611, 1663, 1808
]
plant_id_pudl: [
    597, 1835, 1139, 2508, 1244, 246, 8310, 648, 1247, 328, 450, 6347, 11642, 1666, 1190,
    11992, 12064, 523, 12149, 12138, 12194, 12196, 1541, 8118, 12230, 554, 286, 12175,
    381, 407, 1195, 12043, 435, 350, 500, 200, 1068, 11493, 257, 8550, 40, 1294, 12158,
    1063, 7718, 9, 1206, 12148, 249, 12193, 12219, 12063, 11581, 1376, 12021, 1188, 11875,
    12242, 428, 12195, 11633, 12117, 12146, 2, 11767, 8277, 468, 11580, 1135, 12307, 12159,
    1390, 1295, 1213, 1141, 625, 11618, 1111, 1276, 250, 242, 453, 1273, 1228, 651, 1297, 212,
    1242, 1075, 562, 563, 41, 372, 608, 605, 1286, 388, 9940, 7833, 11495, 11496, 12376,
    12363, 14372
]
```

**Comment by cmgosnell** [comment]
hey @zaneselvans  it would be most helpful if you could indicate which `plant_id_pudl`'s are grouped together. Sifting through the list alone would be difficult - especially because the `plant_id_ferc1`'s are not stable

**Comment by zaneselvans** [comment]
You mean which `plant_id_ferc1` values are associated with which `plant_id_pudl` values? This should get you a dataframe showing how they map to each other:
```py
plant_dupes = (
    pudl_out.plants_steam_ferc1()[["plant_id_pudl", "plant_id_ferc1" ]]
    .drop_duplicates()
    .groupby("plant_id_ferc1")
    .count()
    .rename(columns={"plant_id_pudl": "dupes"})
    .query("dupes>1")
    .reset_index()
    .merge(pudl_out.plants_steam_ferc1()[["plant_id_pudl", "plant_id_ferc1"]])
    .drop_duplicates()
    .loc[:,["plant_id_ferc1", "plant_id_pudl", "dupes"]]
)
```
For me there are 117 rows in `plant_dupes` also attached.
[plant_dupes.txt](https://github.com/catalyst-cooperative/pudl/files/6207834/plant_dupes.txt)

**Comment by swinter2011** [comment]
The two plants algorithmically assigned plant_id_ferc1 52 are different plants. plant_id_pudl 496 is owned by Northern States Power Company (Minnesota) and has construction year 1911. plant_id_pudl 1822 is owned by Baltimore Gas and Electric Company and has construction year 1970.

**Comment by swinter2011** [comment]
Two of the three plants algorithmically assigned plant_id_ferc1 1654 are the martin solar energy facility (plant_id_pudl 11656, martin solar energy and plant_id_pudl 13650 martin solar energyr). The third (plant_id_pudl 371, martin) is a fossil facility.
