### ISSUE TITLE
Enrich and organize PUDL data dictionary

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#960]
We have **[a simple data dictionary](https://catalystcoop-pudl.readthedocs.io/en/latest/pudl_db_index.html)** documenting the PUDL DB automatically generated in our docs build now. Using it a bit in writing some code already, so it's definitely useful!  Right now it's got:
* [x] field name
* [x] field type
* [x] field description

I'm finding that it would also be helpful to have:
* [x] Fields ordered alphabetically (it's kinda random right now)
* [ ] But put primary key fields first, with some indication that they are primary key columns.

Once we get the new metadata system up and running this should pretty easy I think.

**Comment by MichaelTiemannOSC** [comment]
Primary key fields with some kind of indication for sure!

Suggest ordering PK based on datatype first, then alphabetically.

For fields, split into words using '_', then build lists based on word groupings (ignoring common works like "for", "of" etc).  Also break the first word on studlyCaps if they are present.   If there's a heavy use of a common word (typically first, second, or last), those fields should group together alphabetically.

**Comment by cmgosnell** [comment]
we will need to fully redo this when we have our new metadata structure
