### ISSUE TITLE
Set up dependabot

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#986]
The @dependabot can help us keep our dependencies up to date. It makes automatic PRs integrating new versions of the dependencies into the files specifying dependencies when they are detected, and then the tests get run automatically, and we can see whether the updates break anything. If they don't we can just merge the PR.

In theory it is already parsing dependencies listed in `setup.py` and `pyproject.toml`, but thus far it doesn't seem to be *doing* anything about them, while it does catch updates to dependencies for our GitHub Actions. 

Debug why the current configuration isn't triggering PRs from @dependabot and modify our setup to use frozen dependencies that are regularly updated and tested through automated PRs.

**Comment by TrentonBush** [comment]
Documenting my troubleshooting process here in case it helps in the future:

Dependabot has separate logs for the PUDL package updates (which don't work) and the GitHub Actions package updates (which do work). 

GH Actions log (partial):
```
updater | INFO <job_230903816> Starting job processing
updater | INFO <job_230903816> Starting update job for catalyst-cooperative/pudl
updater | INFO <job_230903816> Checking if conda-incubator/setup-miniconda 2.1.1 needs updating

...<50 more lines of checks here>...

updater | INFO <job_230903816> Finished job processing
```

And PUDL package log (partial):

```
updater | INFO <job_230903817> Starting job processing
updater | INFO <job_230903817> Starting update job for catalyst-cooperative/pudl
updater | INFO <job_230903817> Finished job processing
```

Comparing them shows that Dependabot first scans for and parses relevant manifests (not shown in above quotes), which is successful for both cases. It then iteratively checks each discovered dependency. But it does not check a single dependency for PUDL! So it is probably not discovering them.

After digging through the docs looking for reasons, I found this:
`The dependency graph analyzes manifests as they’re pushed to GitHub. The dependency graph ... can't resolve variables used within manifests. If you use variables within a manifest ... then that dependency will not be included in the dependency graph.`

Our current `setup.py` uses variables to define the various lists of dependencies (dev, test, install_requires, etc). Removing those and sticking the lists straight into the `setup()` call fixed the issue.

Now to review a million auto-generated dependency PRs....

**Comment by TrentonBush** [comment]
Dependabot now successfully discovers and checks dependencies and makes PRs.

The next step is to enable automatic CI runs and possible auto-merge upon success. That is currently blocked by external GitHub Actions feature development. I made issue #1342 to address that separate concern.
