### ISSUE TITLE
Attempt to run on Amazon Sagemaker results in __init__ error for PudlTabl

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [catalyst-cooperative/pudl#997]
### Describe the bug
I've created a Python 3.7 instance of SageMaker and done the necessary conda installs to run PUDL.  I've created a .yaml file and copied other patterns of success to get my PUDL notebook running.  However, it fails here:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-37a0dd203959> in <module>
      9 
     10 #pudl_engine.table_names()
---> 11 pudl_out = pudl.output.pudltabl.PudlTabl(pudl_engine, freq='AS') #annual frequency

TypeError: __init__() got multiple values for argument 'freq'
### Bug Severity
How badly is this bug affecting you?
 - **High:** This bug is preventing me from using PUDL.

### To Reproduce
Start with a conda_mxnet_latest_p37 kernel and uncomment these conda installs:

# %conda install geopandas
# %conda install -c conda-forge catalystcoop.pudl
# %conda install contextily

Then try to run the PUDL sample notebooks to initialize PUDL.

### Expected behavior
I expect it to work, like it does in my desktop docker world and on 2c2i

### Software Environment?
Amazon Sagemaker, installed via conda (above)
 - How did you install PUDL? (e.g. `git clone`, `pip`, or `conda`)
When I install everything via pip, I have different problems: the eia_860_generators function is out of step with my pudl.sqlite dictionary, referencing balancing_authority_code instead of balancing_authority_code_eia.

### Additional context
A surprising amount of stuff works even with that failure, but critical stuff doesn't work, so I'd like to fix it.

**Comment by zaneselvans** [comment]
The PyPI / conda-forge version (0.3.2) of PUDL is quite out of date at this point. If you want current dependencies and data, the only option right now is to install from the repo, or pull down our draft Docker image + archived data as explained in the [PUDL Examples repo](https://github.com/catalyst-cooperative/pudl-examples). This is not ideal. We need to get the data build automated so there's always a release candidate ready to go. The current version of PUDL requires Python 3.8 or 3.9. There are a couple of minor data validation errors that still need to be tracked down. The docs are done. And then I think I just need to turn the crank on running the ETL pipeline and publishing the packages. And yet it still seems hard to get it over the finish line.

**Comment by zaneselvans** [comment]
Hey there, do you want to give `catalystcoop.pudl=0.4.0` which has more modern requirements and should work with the current data... let us know if it works!
